<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">
<meta name="author" content="Amy Herring">
<meta name="dcterms.date" content="2026-10-21">
<title>STA 198 – ANOVA: Analysis of Variance</title>
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
<link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
<style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
<link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-f0195dcd610196b9111c6e10e98695f4.css">
<link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
<link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
<style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<link href="../site_libs/font-awesome/css/all.min.css" rel="stylesheet">
<link href="../site_libs/font-awesome/css/v4-shims.min.css" rel="stylesheet">
<link href="../site_libs/panelset/panelset.css" rel="stylesheet">
<script src="../site_libs/panelset/panelset.js"></script><script src="../site_libs/kePrint/kePrint.js"></script><link href="../site_libs/lightable/lightable.css" rel="stylesheet">
<meta property="og:title" content="ANOVA: Analysis of Variance – STA 198">
<meta property="og:description" content="Introduction to Global Health Data Science">
<meta property="og:site_name" content="STA 198">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center"><h1 class="title">ANOVA: Analysis of Variance</h1>
  <p class="subtitle">Introduction to Global Health Data Science</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Amy Herring 
</div>
        <p class="quarto-title-affiliation">
            Duke University <br> STA/GLHLTH 198 Fall 2026
          </p>
    </div>
</div>

  <p class="date">2026-10-21</p>
</section><section><section id="data-artisanal-and-small-scale-gold-mining-in-the-peruvian-amazon" class="title-slide slide level1 center"><h1>Data: Artisanal and Small-Scale Gold Mining in the Peruvian Amazon</h1>

</section><section id="mercury-and-community" class="slide level2"><h2>Mercury and Community</h2>
<p><a href="https://theconversation.com/gold-rush-mercury-legacy-small-scale-mining-for-gold-has-produced-long-lasting-toxic-pollution-from-1860s-california-to-modern-peru-133324">Artisinal and small-scale gold mining is largest source of mercury pollution worldwide</a>.</p>
<p>Are mercury concentrations in hair related to community of residence?</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-3"><a></a><span class="fu">library</span>(readr)</span>
<span id="cb1-4"><a></a>mercury <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"../data/mercury_reg.csv"</span>)</span>
<span id="cb1-5"><a></a><span class="fu">head</span>(mercury)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 18
     id withinid   hid   cid community      age SESassets lhairHg
  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1     1        1     1     1 Boca Colora…    29    -1.09   0.676 
2     2        1     2     1 Boca Colora…    31     0.235 NA     
3     3        3     2     1 Boca Colora…    26     0.235  0.0908
4     4        2     2     1 Boca Colora…     5     0.235 NA     
5     5        1     3     1 Boca Colora…    45    -0.157 NA     
6     6        3     3     1 Boca Colora…    38    -0.157 NA     
# ℹ 10 more variables: sex &lt;dbl&gt;, wcba &lt;dbl&gt;, urban &lt;dbl&gt;,
#   mining &lt;dbl&gt;, agriculture &lt;dbl&gt;, FM_buffer &lt;dbl&gt;,
#   IM_buffer &lt;dbl&gt;, longitude &lt;dbl&gt;, latitude &lt;dbl&gt;,
#   native &lt;dbl&gt;</code></pre>
</div>
</div>
</section><section id="relationship-between-mercury-and-individual-community" class="slide level2"><h2>Relationship between mercury and individual community</h2>
<p>One way to explore this relationship is through a linear regression model, with <em>dummy</em> or <em>indicator variables</em> for community as predictors.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>res <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a></a>  <span class="fu">fit</span>(lhairHg <span class="sc">~</span> community, <span class="at">data =</span> mercury) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a></a>  <span class="fu">tidy</span>() </span>
<span id="cb3-5"><a></a><span class="fu">print</span>(res,<span class="at">n=</span><span class="dv">23</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="section" class="slide level2" data-background-color="white"><h2></h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 5
   term                     estimate std.error statistic  p.value
   &lt;chr&gt;                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)                0.614     0.0644     9.54  3.55e-21
 2 communityBoca Isiriwe      1.20      0.159      7.56  5.77e-14
 3 communityBoca Manu         0.833     0.129      6.43  1.56e-10
 4 communityCaychihue        -1.10      0.132     -8.36  1.09e-16
 5 communityChoque           -0.778     0.117     -6.68  3.04e-11
 6 communityDiamante          1.06      0.109      9.67  1.00e-21
 7 communityHuepetuhe        -0.694     0.0732    -9.48  5.96e-21
 8 communityIsla de los Va…   1.12      0.245      4.57  5.18e- 6
 9 communityMasenawa          1.20      0.401      3.00  2.74e- 3
10 communityPalotoa Teparo    0.350     0.148      2.36  1.82e- 2
11 communityPuerto Azul       1.22      0.230      5.27  1.45e- 7
12 communityPuerto Luz        0.494     0.0991     4.98  6.67e- 7
13 communityPunquiri         -0.678     0.176     -3.84  1.26e- 4
14 communityPuquiri           0.0842    0.192      0.439 6.61e- 1
15 communityQuebrada Neuva   -0.812     0.0966    -8.41  7.21e-17
16 communityQueros           -0.707     0.245     -2.89  3.93e- 3
17 communityQuimiri          -0.621     0.274     -2.26  2.38e- 2
18 communityQuincemil        -0.822     0.0858    -9.57  2.55e-21
19 communitySalvacion        -0.732     0.0850    -8.61  1.31e-17
20 communitySan Lorenzo      -0.245     0.124     -1.98  4.82e- 2
21 communitySetapo            0.517     0.319      1.62  1.05e- 1
22 communityShintuya          0.130     0.122      1.07  2.86e- 1
23 communityShipitiari        0.532     0.161      3.30  9.65e- 4</code></pre>
</div>
</div>
</section><section id="section-1" class="slide level2" data-background-color="white"><h2></h2>
<ul>
<li><p>When the categorical explanatory variable has many levels, they’re encoded to <strong>indicator</strong> or <strong>dummy variables</strong></p></li>
<li><p>Each coefficient describes the expected difference between hair mercury levels in that particular community compared to the baseline level</p></li>
<li><p>Here, the community mean hair mercury levels are different from those in Boca Colorado (the <em>referent</em> group, selected alphabetically) with the exception of Puquiri, Setapo, and Shintuya.</p></li>
<li><p>What if we want to make comparisons between pairs of communities that don’t involve Boca Colorado? We’ll address that shortly!</p></li>
</ul></section><section id="anova" class="slide level2"><h2>ANOVA</h2>
<p>When our predictor variable is categorical and the response is (approximately) normal (perhaps after transformation), often this type of model is fitted as an <strong>ANOVA</strong> model. <strong>ANOVA or Analysis of Variance</strong> refers to an approach when we have all categorical predictors, in which the hypothesis of interest is related to the degree of variability in the means across groups (versus within-group variability).</p>
<p>We can think of ANOVA as a special case of regression, when all predictors are categorical. Philosophically, ANOVA is more of a tool to break apart different sources of variation in data.</p>
</section><section id="section-2" class="slide level2" data-background-color="white"><h2></h2>
<p>First, let’s explore hair Hg levels (in log ppm) by community in our data visually.</p>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-1-1">Plot</a></li>
<li><a href="#tabset-1-2">Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="w09-02-anova_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-1-2">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">ggplot</span>(<span class="at">data =</span> mercury,</span>
<span id="cb5-2"><a></a>       <span class="fu">aes</span>(<span class="at">x =</span> community, <span class="at">y =</span> lhairHg,</span>
<span id="cb5-3"><a></a>           <span class="at">color =</span> community)) <span class="sc">+</span></span>
<span id="cb5-4"><a></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb5-5"><a></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="st">"NULL"</span>,</span>
<span id="cb5-6"><a></a>       <span class="at">y =</span> <span class="st">"Hair Hg (log ppm)"</span>,</span>
<span id="cb5-7"><a></a>       <span class="at">x =</span> <span class="st">"Community"</span>) <span class="sc">+</span></span>
<span id="cb5-8"><a></a>  <span class="fu">theme</span>(</span>
<span id="cb5-9"><a></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(</span>
<span id="cb5-10"><a></a>      <span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb5-11"><a></a>      <span class="at">vjust =</span> <span class="dv">1</span>,</span>
<span id="cb5-12"><a></a>      <span class="at">hjust =</span> <span class="dv">1</span>,</span>
<span id="cb5-13"><a></a>      <span class="at">size =</span> <span class="dv">6</span></span>
<span id="cb5-14"><a></a>    ),</span>
<span id="cb5-15"><a></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb5-16"><a></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="hypothesis-of-interest" class="slide level2"><h2>Hypothesis of Interest</h2>
<p>We might be interested in testing whether all the community means are the same or not.</p>
<p><span class="math display">\[H_0: \mu_{Boca Col}=\mu_{Boca Isi}=\cdots=\mu_{Shipitiari}\]</span></p>
<p>versus the alternative hypothesis that at least one of the community means is different.</p>
<p>One way to do this would be to use t-tests on all possible pairs of communities. In this case, with 23 communities we would need to do <span class="math inline">\(\begin{pmatrix} 23 \\ 2 \end{pmatrix}=253\)</span> tests! In addition to being time-consuming, carrying out multiple tests typically leads to an <em>inflated type I error rate</em>.</p>
</section><section id="multiple-comparisons" class="slide level2"><h2>Multiple Comparisons</h2>
<div style="font-size:0.9em;">
<ul>
<li><p>Suppose all means are truly equal, and we conduct all 253 pairwise tests</p></li>
<li><p>Suppose also the tests are independent and done at a 0.05 significance level</p></li>
<li><p>Then the probability we fail to reject all 253 tests (the right decision) is <span class="math inline">\((1-0.05)^{253}=0.95^{253} \approx 0\)</span>, and the probability of rejecting at least one of the 253 null hypotheses, called the <strong>family-wise error rate</strong>, is <span class="math inline">\(\approx 1 &gt;&gt;0.05\)</span></p></li>
<li><p>In reality, this is a little more complicated (tests are not independent), but we still have the problem of an inflated type I error rate.</p></li>
<li><p>ANOVA extends the t-test and is one way to control the overall type I error rate at a fixed level <span class="math inline">\(\alpha\)</span>, if we only test pairwise differences when the <em>chunk</em> or <em>overall test</em> is rejected</p></li>
</ul>
</div>
</section><section id="anova-null-hypothesis" class="slide level2"><h2>ANOVA Null Hypothesis</h2>
<p>In ANOVA, we typically follow this testing procedure.</p>
<ul>
<li>
<p>First, you conduct an <em>overall</em> or <em>chunk</em> test of the null hypothesis that the means of all of the groups are equal.</p>
<ul>
<li><p>If you reject this null hypothesis, then we usually <em>step down</em> to see which means are different from each other. A <em>multiple comparisons</em> correction is sometimes used for these pairwise comparisons of means.</p></li>
<li><p>If you do not reject the null hypothesis, this means our data are consistent with a population in which the means are all equal. Generally, no further testing should be done.</p></li>
</ul>
</li>
</ul></section></section><section><section id="multiple-comparisons-in-action" class="title-slide slide level1 center"><h1>Multiple Comparisons in Action</h1>

</section><section id="overall-test" class="slide level2"><h2>Overall Test</h2>

<img data-src="../img/jb1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:60.0%"></section><section id="extra-test-1-wild-blackberry" class="slide level2"><h2>Extra Test 1: Wild Blackberry</h2>

<img data-src="../img/jbpurple.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-2-root-beer" class="slide level2"><h2>Extra Test 2: Root Beer</h2>

<img data-src="../img/jbbrown.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-3-cotton-candy" class="slide level2"><h2>Extra Test 3: Cotton Candy</h2>

<img data-src="../img/jbpink.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-4-island-punch" class="slide level2"><h2>Extra Test 4: Island Punch</h2>

<img data-src="../img/jbblue.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-5-blueberry" class="slide level2"><h2>Extra Test 5: Blueberry</h2>

<img data-src="../img/jbteal.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-6-pink-grapefruit" class="slide level2"><h2>Extra Test 6: Pink Grapefruit</h2>

<img data-src="../img/jbsalmon.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-7-strawberry-jam" class="slide level2"><h2>Extra Test 7: Strawberry Jam</h2>

<img data-src="../img/jbred.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-8-berry-blue" class="slide level2"><h2>Extra Test 8: Berry Blue</h2>

<img data-src="../img/jbturquoise.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-9-pomegranate" class="slide level2"><h2>Extra Test 9: Pomegranate</h2>

<img data-src="../img/jbmagenta.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-10-buttered-popcorn" class="slide level2"><h2>Extra Test 10: Buttered Popcorn</h2>

<img data-src="../img/jbyellow.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-11-black-pepper" class="slide level2"><h2>Extra Test 11: Black Pepper</h2>

<img data-src="../img/jbgrey.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-12-ear-wax" class="slide level2"><h2>Extra Test 12: Ear Wax</h2>

<img data-src="../img/jbtan.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-13-soap" class="slide level2"><h2>Extra Test 13: Soap</h2>

<img data-src="../img/jbcyan.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-14-green-apple" class="slide level2"><h2>Extra Test 14: Green Apple</h2>

<img data-src="../img/jbgreen.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="extra-test-15-strawberry-cheesecake" class="slide level2"><h2>Extra Test 15: Strawberry Cheesecake</h2>

<img data-src="../img/jbmauve.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="green-apple" class="slide level2"><h2>GREEN APPLE!</h2>

<img data-src="../img/greenbeans.png" class="quarto-figure quarto-figure-center r-stretch" style="width:25.0%"></section><section id="green-jelly-beans-again" class="slide level2"><h2>Green Jelly Beans Again</h2>
<p>Disclaimer: So, uh, we did the green study again and got no link. It was probably a – “RESEARCH CONFLICTED ON GREEN JELLY BEAN-ACNE LINK; MORE STUDY RECOMMENDED!” headline.</p>
<p>Later, we’ll learn how to control type I error rate for many comparisons.</p>
</section></section><section><section id="back-to-anova" class="title-slide slide level1 center"><h1>Back to ANOVA</h1>

</section><section id="why-analyze-variance" class="slide level2"><h2>Why Analyze Variance?</h2>
<p>ANOVA stands for <em>analysis of variance</em>.</p>
<p>What does variance have to do with our null hypothesis, which is about equality of means, say <span class="math inline">\(H_0: \mu_1=\mu_2=\cdots=\mu_K\)</span> for K means?</p>
</section><section id="general-anova-setup" class="slide level2"><h2>General ANOVA Setup</h2>
<ul>
<li><p><span class="math inline">\(H_0:  \mu_1=\mu_2=\cdots=\mu_K\)</span></p></li>
<li>
<p><span class="math inline">\(H_A:\)</span> at least one of the means is different</p>
<ul>
<li>NOT ONLY <span class="math inline">\(H_A: \mu_1 \neq \mu_2 \neq \cdots \neq \mu_K\)</span> (this would force all means to be different)</li>
</ul>
</li>
<li><p>Let the response of subject <span class="math inline">\(j\)</span> in group <span class="math inline">\(i\)</span> be given by <span class="math inline">\(y_{ij}\)</span>, <span class="math inline">\(i=1,2,\ldots,K\)</span>, <span class="math inline">\(j=1,\ldots,n_i\)</span></p></li>
<li><p><span class="math inline">\(K\)</span> is the number of groups</p></li>
<li><p><span class="math inline">\(n_i\)</span> is the number of subjects in group <span class="math inline">\(i\)</span></p></li>
</ul></section><section id="section-3" class="slide level2" data-background-color="white"><h2></h2>
<div style="font-size:0.85em;">
<p>ANOVA model is <span class="math display">\[y_{ij}=\mu_i+\varepsilon_{ij}\]</span> where we assume the <span class="math inline">\(\varepsilon_{ij}\)</span> are independent and normally distributed with mean 0 and variance <span class="math inline">\(\sigma^2\)</span>.</p>
<ul>
<li><p><span class="math inline">\(\varepsilon_{ij}\)</span> represent random error about each group mean, <span class="math inline">\(\mu_i\)</span></p></li>
<li><p>Model assumes the <span class="math inline">\(y_{ij}\)</span> are independent and normally distributed with mean <span class="math inline">\(\mu_i\)</span> and variance <span class="math inline">\(\sigma^2\)</span></p></li>
<li><p>Sometimes you see the model broken out with <span class="math inline">\(\mu_i=\mu+\alpha_i\)</span>, where <span class="math inline">\(\mu\)</span> represents the overall or <em>grand mean</em> and <span class="math inline">\(\alpha_i\)</span> represents each group’s deviation from the overall mean</p></li>
<li><p>Alternatively <em>reference cell</em> coding, like we used when fitting the regression model, could be used, where one group is the <em>referent group</em> and the other coefficients represent differences between each group and the referent group</p></li>
</ul>
</div>
</section><section id="assumptions-of-anova" class="slide level2"><h2>Assumptions of ANOVA</h2>
<ul>
<li><p>Outcomes within groups are normally distributed</p></li>
<li><p><em>Homoscedastic variance</em> (same variance of individual observations in each group)</p></li>
<li><p>Samples are independent</p></li>
</ul></section><section id="checking-anova-assumptions-in-mercury-data-ppm-scale" class="slide level2"><h2>Checking ANOVA Assumptions in Mercury Data: PPM Scale</h2>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-2-1">Plot</a></li>
<li><a href="#tabset-2-2">Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="w09-02-anova_files/figure-revealjs/facethistppm-1.png" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-2-2">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>mercury <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">exp</span>(lhairHg))) <span class="sc">+</span></span>
<span id="cb6-3"><a></a>    <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>community) <span class="sc">+</span></span>
<span id="cb6-5"><a></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mercury (ppm)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="checking-anova-assumptions-in-mercury-data-log-scale" class="slide level2"><h2>Checking ANOVA Assumptions in Mercury Data: Log Scale</h2>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-3-1">Plot</a></li>
<li><a href="#tabset-3-2">Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure><p><img data-src="w09-02-anova_files/figure-revealjs/facethist-1.png" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="tabset-3-2">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>mercury <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> lhairHg)) <span class="sc">+</span></span>
<span id="cb7-3"><a></a>    <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb7-4"><a></a>    <span class="fu">facet_wrap</span>(<span class="sc">~</span>community) <span class="sc">+</span></span>
<span id="cb7-5"><a></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mercury (log ppm)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="anova-assumptions" class="slide level2"><h2>ANOVA Assumptions</h2>
<ul>
<li><p>Normality: nothing looks terribly non-normal on the log scale, though some communities have relatively few measures</p></li>
<li><p>Equal variances: more or less ok on the log scale</p></li>
<li><p>Independence: this is an issue with these data, as some households provided multiple hair samples, and individuals within households may share exposure sources (e.g., meals), leading to correlated data within household. We will address this issue shortly.</p></li>
</ul></section><section id="anova-for-mercury-data" class="slide level2"><h2>ANOVA for Mercury Data</h2>
<div style="font-size:0.9em;">
<ul>
<li><p>Let the hair mercury of subject <span class="math inline">\(j\)</span> in community <span class="math inline">\(i\)</span> be given by <span class="math inline">\(y_{ij}\)</span>, <span class="math inline">\(i=1,2,\ldots, 23\)</span>, <span class="math inline">\(j=1,\ldots,n_i\)</span></p></li>
<li><p>We have 23 communities with <span class="math inline">\(n_i\)</span> subjects in each</p></li>
<li><p>For each community, calculate the sample mean and variance, so now we have <span class="math inline">\(\bar{y}_1\)</span> and <span class="math inline">\(s^2_1\)</span>, <span class="math inline">\(\bar{y}_2\)</span> and <span class="math inline">\(s^2_2\)</span>, and so on <span class="math inline">\(\bar{y}_i\)</span> and <span class="math inline">\(s^2_i\)</span>, <span class="math inline">\(i=1,\ldots,23\)</span></p></li>
<li>
<p>ANOVA is concerned with two different types of variances:</p>
<ul>
<li><p><em>Within-groups variance</em>: variance of the individual observations around their respective community means</p></li>
<li><p><em>Between-groups variance</em>: variance of the community means around the overall mean of all observations, <span class="math inline">\(\bar{y}_\cdot\)</span></p></li>
</ul>
</li>
</ul>
</div>
</section><section id="overall-variance" class="slide level2"><h2>Overall variance</h2>
<p>Variance of <span class="math inline">\(y\)</span> is estimated as <span class="math display">\[s^2=\frac{\sum_{i=1}^K \sum_{j=1}^{n_i} (y_{ij}-\bar{y})^2}{n-1},\]</span> where <span class="math inline">\(n=\sum_{i=1}^K n_i\)</span> is the total sample size across all communities.</p>
<div style="font-size:0.65em;">
<p>While the double summation may look confusing, it is not too bad. The inner <span class="math inline">\(\sum_{j=1}^{n_i}\)</span> is just taking the sum of the squared differences between each individual log hair mercury concentration <span class="math inline">\(y_{ij}\)</span> and the overall average log concentration <span class="math inline">\(\bar{y}\)</span> for the people in community <span class="math inline">\(i\)</span>. The outer sum is over the <span class="math inline">\(K=23\)</span> total communities so we end up getting the sum of squared differences for every sampled person in every community.</p>
</div>
<p>ANOVA breaks the overall variance down into two parts: variance within groups, and variance between groups.</p>
</section><section id="within-groups-variance" class="slide level2"><h2>Within-groups variance</h2>
<p>Each community’s variance <span class="math display">\[{s}^2_i=\frac{\sum_{j=1}^{n_i} (y_{ij}-\overline{y}_i)^2}{n_i-1}\]</span> is a measure of the variance of the individuals around that community mean. There is a separate variance here for each community.</p>
</section><section id="within-groups-variance-1" class="slide level2"><h2>Within-groups variance</h2>
<div style="font-size:0.75em;">
<p>Recall <span class="math inline">\({s}^2_i=\frac{\sum_{j=1}^{n_i} (y_{ij}-\overline{y}_i)^2}{n_i-1}.\)</span></p>
<p>To get a pooled estimate of the common variance of individuals around their community means, we can calculate</p>
<p><span class="math display">\[
\begin{aligned}
{s_W}^2 &amp;= \frac{(n_1-1){s_1}^2 + (n_2-1){s_2}^2 + \cdots + (n_K-1){s_K}^2}{n - K} \\[1.5ex]
        &amp;= \frac{\sum_{i=1}^K \sum_{j=1}^{n_i} (y_{ij}-\bar{y}_i)^2}{n-K},
\end{aligned}
\]</span></p>
<p>where <span class="math inline">\(K\)</span> is the number of groups and <span class="math inline">\(n=n_1+n_2+\cdots+n_K\)</span>.</p>
<p>We can think of this within-groups variance as the inherent variability in the population.</p>
</div>
</section><section id="between-groups-variance" class="slide level2"><h2>Between-groups variance</h2>
<p>The between groups variance is estimated by <span class="math display">\[s_B^2=\frac{n_1(\bar{y}_1-\bar{y}_\cdot)^2+n_2(\bar{y}_2-\bar{y}_\cdot)^2 + \cdots + n_K(\bar{y}_K-\bar{y}_\cdot)^2}{K-1}.\]</span></p>
<p>We can think of the between-groups variance as the variability among the group means, scaled up by group size. If all groups share the same population mean, it also reflects the inherent variability in the population. If the population means differ, it picks up that extra signal as well. So it is the sum of inherent variability <em>and</em> any kind of systematic variability due to the group/community effect.</p>
</section><section id="f-test" class="slide level2"><h2>F test</h2>
<div style="font-size:0.85em;">
<p>Both <span class="math inline">\({s_W}^2\)</span> and <span class="math inline">\({s_B}^2\)</span> are estimates of the population variance <span class="math inline">\(\sigma^2\)</span> if <span class="math inline">\(H_0\)</span> is true. Now, if the sample means vary around the overall mean (this variance measured by <span class="math inline">\({s_B}^2\)</span>) more than the individual observations vary around the sample means (measured by <span class="math inline">\({s_W}^2\)</span>), we have evidence that the corresponding group population means are in fact different (so that all <span class="math inline">\(K\)</span> means are not the same).</p>
<p>How do we compare the variances? Consider <span class="math display">\[F=\frac{\text{inherent variability + group effect}}{\text{inherent variability}}.\]</span> If there is little to no group effect (no group effect implies <span class="math inline">\(H_0\)</span> is true), this ratio will be very close to 1.</p>
</div>
</section><section id="f-test-1" class="slide level2"><h2>F test</h2>
<div style="font-size:0.85em;">
<p>Thus the F statistic is given by <span class="math display">\[F={s_B}^2/{s_W}^2,\]</span> which if <span class="math inline">\(H_0\)</span> is true has an <span class="math inline">\(F\)</span> distribution with <span class="math inline">\(K-1\)</span> and <span class="math inline">\(n-K\)</span> df. The df associated with <span class="math inline">\({s_B}^2\)</span> are called the <em>numerator degrees of freedom</em> and correspond to the total number of groups minus 1. The df associated with <span class="math inline">\({s_W}^2\)</span> are called the <em>denominator degrees of freedom</em> and equal the total sample size minus the number of groups (we lose one df for each group mean we estimate). For ANOVA the test is inherently one-tailed, rejecting <span class="math inline">\(H_0\)</span> only if <span class="math inline">\(F\)</span> is considerably larger than one. (This does not mean we have a one-sided alternative; we just look at one tail of the F distribution to get the p-value, as the F statistic is never negative because variances cannot be negative.)</p>
<p>If there are only two groups, then the F test gives the same result as the t-test (with equal variances).</p>
</div>
</section><section id="f-distribution" class="slide level2"><h2>F Distribution</h2>

<img data-src="../img/fdists.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><p>The numerator and denominator degrees of freedom (ndf and ddf) determine the cutpoint for a given <span class="math inline">\(\alpha\)</span> level. The ndf is one less than the number of groups, and the ddf is the total number of observations minus the number of groups.</p>
</section><section id="visualizing-anova" class="slide level2"><h2>Visualizing ANOVA</h2>
<p>We can visualize the between and within groups variances, as well as how testing variances tells us about means, using <a href="https://gallery.shinyapps.io/anova_shiny_rstudio/">this cool R Shiny app</a>.</p>
</section><section id="anova-for-mercury-data-1" class="slide level2"><h2>ANOVA for Mercury Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="co">#: label: anovahg</span></span>
<span id="cb8-2"><a></a><span class="fu">summary</span>(<span class="fu">aov</span>(lhairHg<span class="sc">~</span>community,<span class="at">data=</span>mercury))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
community     22  909.6   41.34   52.82 &lt;2e-16 ***
Residuals   2285 1788.7    0.78                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
1775 observations deleted due to missingness</code></pre>
</div>
</div>
<p>Here’s the <strong>overall test</strong> of the null hypothesis that all 23 means are equal, versus the alternative that at least one mean is different. Based on that p-value, these data, or more extreme data, would be highly unlikely if the null hypothesis were true. Next, we probably wish to know which means are different!</p>
</section><section id="step-down-tests" class="slide level2"><h2>Step-Down Tests</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="co"># label: holm</span></span>
<span id="cb10-2"><a></a><span class="co"># Holm's correction gives us good protection against type I errors</span></span>
<span id="cb10-3"><a></a><span class="co"># under a wide variety of settings</span></span>
<span id="cb10-4"><a></a>hairpair <span class="ot">&lt;-</span> <span class="fu">pairwise.t.test</span>(mercury<span class="sc">$</span>lhairHg,    mercury<span class="sc">$</span>community, <span class="at">p.adj =</span> <span class="st">"holm"</span>)</span>
<span id="cb10-5"><a></a>sigpairs <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(hairpair) <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a></a>  <span class="fu">filter</span>(p.value<span class="sc">&lt;</span><span class="fl">0.05</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a></a>  <span class="fu">arrange</span>(group1,group2)</span>
<span id="cb10-8"><a></a><span class="fu">nrow</span>(sigpairs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 138</code></pre>
</div>
</div>
<p>OK, that’s a lot of differences! More community pairs are different than not.</p>
</section><section id="section-4" class="slide level2" data-background-color="white"><h2></h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">print</span>(sigpairs,<span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 138 × 3
   group1       group2         p.value
   &lt;chr&gt;        &lt;chr&gt;            &lt;dbl&gt;
 1 Boca Isiriwe Boca Colorado 1.13e-11
 2 Boca Manu    Boca Colorado 2.82e- 8
 3 Caychihue    Boca Colorado 2.31e-14
 4 Caychihue    Boca Isiriwe  5.64e-32
 5 Caychihue    Boca Manu     5.52e-30
 6 Choque       Boca Colorado 5.56e- 9
 7 Choque       Boca Isiriwe  1.35e-26
 8 Choque       Boca Manu     2.18e-24
 9 Diamante     Boca Colorado 2.30e-19
10 Diamante     Caychihue     1.68e-45
# ℹ 128 more rows</code></pre>
</div>
</div>
<p>Most communities do differ in levels of hair mercury!</p>
</section><section id="write-up-of-methods-and-results" class="slide level2"><h2>Write-up of Methods and Results</h2>
<div style="font-size:0.85em;">
<p>The data were analyzed using one-way ANOVA to test the overall hypothesis of no difference across communities, with planned step-down tests using a Holm correction for multiple comparisons when the overall hypothesis was rejected.</p>
<p>Using the overall F test (ndf=22, ddf=2285), a significant difference among the communities was identified (p&lt;0.0001). Step-down tests indicated that mercury levels differed across the majority of pairwise community comparisons.</p>
<p>One challenge to the validity of this analysis is that multiple measures were obtained per household. If shared exposures or other factors induced positive correlations in mercury measures among household members, our standard errors would be too small, and our estimated significance levels would be anti-conservative.</p>
</div>
</section></section><section><section id="wait-is-that-wrong-hold-that-thought." class="title-slide slide level1 center"><h1>Wait, is that wrong? Hold that thought.</h1>

</section><section id="bonferroni-correction" class="slide level2"><h2>Bonferroni Correction</h2>
<p>As we showed earlier, conducting multiple tests on a data set increases the <em>family-wise error rate</em>. One very conservative way to ensure this is not the case is to divide <span class="math inline">\(\alpha\)</span> by the number of tests to be done and to use that as the significance level. This procedure is called the Bonferroni correction. For example for two tests, to preserve an overall 0.05 type I error rate, the Bonferroni correction would use <span class="math inline">\(\frac{\alpha}{2}=0.025\)</span> as the significance level for each individual test instead of <span class="math inline">\(0.05\)</span>. Bonferroni is a conservative multiple comparisons correction (like saving your money in your mattress!), making it harder to reject the null hypothesis, but it is a safe bet in controlling the type I error rate. A less conservative method that also offers strong control of the error rate is Holm’s method, which we used in our code.</p>
</section><section id="violation-of-independence" class="slide level2"><h2>Violation of independence</h2>
<p>The violation of the independence assumption due to the inclusion of multiple household members is indeed a concern. To explore this, let’s calculate the fraction of households (coded using <code>hid</code>) that provided hair measures from more than one household member.</p>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby">
<li><a data-tabby-default="" href="#tabset-4-1">Output</a></li>
<li><a href="#tabset-4-2">Code</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 2
   community          avgct
   &lt;chr&gt;              &lt;dbl&gt;
 1 Boca Colorado      0.794
 2 Boca Isiriwe       0.973
 3 Boca Manu          0.903
 4 Caychihue          0.831
 5 Choque             0.807
 6 Diamante           0.842
 7 Huepetuhe          0.842
 8 Isla de los Valles 0.929
 9 Masenawa           0.6  
10 Palotoa Teparo     0.977
# ℹ 13 more rows</code></pre>
</div>
</div>
</div>
<div id="tabset-4-2">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>mercury <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(lhairHg)<span class="sc">==</span><span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a></a>  <span class="fu">group_by</span>(hid) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a></a>  <span class="fu">mutate</span>(<span class="at">hhobs=</span><span class="fu">n</span>(),</span>
<span id="cb15-5"><a></a>         <span class="at">multmeas=</span>(hhobs<span class="sc">&gt;</span><span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb15-6"><a></a>  <span class="fu">group_by</span>(community) <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a></a>  <span class="fu">summarize</span>(<span class="at">avgct=</span><span class="fu">mean</span>(multmeas))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section><section id="concerns-when-independence-is-violated" class="slide level2"><h2>Concerns when Independence is Violated</h2>
<p>Typically, observations within a household are positively correlated (e.g., if one family member has a high level of hair mercury, another family member is more likely to have high hair mercury). Ignoring this type of positive correlation within household can lead to estimated standard errors (and thus p-values) that are <strong>too small</strong> when we’re estimating group means, invalidating our inferences.</p>
</section><section id="simple-fix-limit-to-one-person-per-household" class="slide level2"><h2>Simple Fix: Limit to One Person Per Household</h2>
<p>The easiest solution to this problem is to limit the dataset to a single person per household. In this case, we’ll limit to the household member denoted <code>withinid=1</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>mercuryone <span class="ot">&lt;-</span> mercury <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a></a>  <span class="fu">filter</span>(withinid<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb16-3"><a></a></span>
<span id="cb16-4"><a></a><span class="fu">summary</span>(<span class="fu">aov</span>(lhairHg<span class="sc">~</span>community,<span class="at">data=</span>mercuryone))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
community    22  237.4  10.792   11.84 &lt;2e-16 ***
Residuals   669  610.0   0.912                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
434 observations deleted due to missingness</code></pre>
</div>
</div>
<p>Our dataset is much smaller now, but we still see differences across communities and reject the overall test.</p>
</section><section id="section-5" class="slide level2" data-background-color="white"><h2></h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a>hairpair <span class="ot">&lt;-</span> <span class="fu">pairwise.t.test</span>(mercuryone<span class="sc">$</span>lhairHg,    mercuryone<span class="sc">$</span>community, <span class="at">p.adj =</span> <span class="st">"holm"</span>)</span>
<span id="cb18-2"><a></a>sigpairs <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(hairpair) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a></a>  <span class="fu">filter</span>(p.value<span class="sc">&lt;</span><span class="fl">0.05</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a></a>  <span class="fu">arrange</span>(group1,group2)</span>
<span id="cb18-5"><a></a><span class="fu">nrow</span>(sigpairs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 55</code></pre>
</div>
</div>
</section><section id="section-6" class="slide level2" data-background-color="white"><h2></h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">print</span>(sigpairs,<span class="at">n=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 55 × 3
   group1    group2             p.value
   &lt;chr&gt;     &lt;chr&gt;                &lt;dbl&gt;
 1 Caychihue Boca Colorado 0.0210      
 2 Caychihue Boca Isiriwe  0.0000188   
 3 Caychihue Boca Manu     0.00279     
 4 Choque    Boca Isiriwe  0.000240    
 5 Choque    Boca Manu     0.0344      
 6 Diamante  Boca Colorado 0.00478     
 7 Diamante  Caychihue     0.0000000397
 8 Diamante  Choque        0.000000507 
 9 Huepetuhe Boca Colorado 0.000282    
10 Huepetuhe Boca Isiriwe  0.0000169   
# ℹ 45 more rows</code></pre>
</div>
</div>
<p>Now just 55 community pair comparisons are different – still a marked difference across communities.</p>
</section><section id="random-effects-anova" class="slide level2"><h2>Random Effects ANOVA</h2>
<div style="font-size:0.85em;">
<p>Another way to address multiple measures in each household is to add a <strong>random effect</strong> for household, to allow data from individuals within households to be positively correlated. This allows us to use all the data but controls for the within-household correlation that causes us to violate the independence assumption, replacing it with a <em>conditional independence</em> assumption: conditional on household, individuals are independent.</p>
<p>The random effect allows the model to capture correlation between residents of the same household.</p>
<p>NOTE: this discussion of <em>random effects ANOVA</em> is something you get for free with STA 198! I’m not going to expect you to fit these models, but I will expect you just to know that if you have correlated data, a <em>random effects model</em> is a good option!</p>
</div>
</section><section id="random-effects-results" class="slide level2"><h2>Random effects results</h2>
<div style="font-size:0.85em;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">library</span>(lme4)</span>
<span id="cb22-2"><a></a><span class="co"># need a factor version of hid</span></span>
<span id="cb22-3"><a></a>mercury <span class="ot">&lt;-</span> mercury <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a></a>  <span class="fu">mutate</span>(<span class="at">hhid=</span><span class="fu">as.factor</span>(hid))</span>
<span id="cb22-5"><a></a></span>
<span id="cb22-6"><a></a>m1<span class="ot">=</span><span class="fu">lmer</span>(lhairHg <span class="sc">~</span> community <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> hhid), <span class="at">data =</span> mercury)</span>
<span id="cb22-7"><a></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table
          npar Sum Sq Mean Sq F value
community   22 258.74  11.761  28.853</code></pre>
</div>
</div>
<p>As you can see, the F statistic is markedly smaller after accounting for within-household correlation. R does not provide a p-value here, as testing in this setting is quite tricky. The story at the end of the day is the same – community matters. If you want to learn more about these models (also called multi-level or hierarchical models), we have more classes for you to do just that!</p>
</div>
</section><section id="section-7" class="slide level2" data-background-color="white"><h2></h2>
<p>We can estimate the correlation, called the <strong>inter class correlation</strong> or <strong>ICC</strong>, as the ratio of the group variance to the total variance:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a><span class="fu">library</span>(performance)</span>
<span id="cb24-2"><a></a><span class="fu">icc</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Intraclass Correlation Coefficient

    Adjusted ICC: 0.488
  Unadjusted ICC: 0.331</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a><span class="co"># you want the adjusted ICC</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We interpret the ICC=0.49 as the correlation inside a household, or the fraction of variance explained by household membership. The correlation here is quite large. We should not be making any decisions based on the first analysis that included multiple individuals per household with no adjustment for correlated data (the analysis limiting to one person per household is still fine).</p>
</section><section id="section-8" class="slide level2" data-background-color="white"><h2></h2>
<div style="font-size:0.8em;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb27-2"><a></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb27-3"><a></a><span class="fu">library</span>(pbkrtest)</span>
<span id="cb27-4"><a></a>paired <span class="ot">&lt;-</span> m1 <span class="sc">%&gt;%</span></span>
<span id="cb27-5"><a></a>    <span class="fu">emmeans</span>(pairwise<span class="sc">~</span>community) </span>
<span id="cb27-6"><a></a></span>
<span id="cb27-7"><a></a>paired<span class="sc">$</span>emmeans</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> community           emmean     SE   df lower.CL upper.CL
 Boca Colorado       0.6170 0.0784 1103   0.4631   0.7708
 Boca Isiriwe        1.7817 0.2120  805   1.3646   2.1988
 Boca Manu           1.4431 0.1460  967   1.1569   1.7292
 Caychihue          -0.4783 0.1480 1014  -0.7694  -0.1872
 Choque             -0.1554 0.1260 1054  -0.4017   0.0909
 Diamante            1.6189 0.1100 1040   1.4026   1.8352
 Huepetuhe          -0.0541 0.0450 1007  -0.1424   0.0342
 Isla de los Valles  1.6244 0.3360  854   0.9656   2.2832
 Masenawa            1.9044 0.4760 1199   0.9706   2.8382
 Palotoa Teparo      0.9485 0.1770  895   0.6005   1.2964
 Puerto Azul         1.7967 0.2860  925   1.2359   2.3576
 Puerto Luz          1.1175 0.1140  791   0.8944   1.3406
 Punquiri           -0.0923 0.2090 1007  -0.5017   0.3171
 Puquiri             0.5921 0.2380 1026   0.1253   1.0588
 Quebrada Neuva     -0.1655 0.0963  966  -0.3545   0.0234
 Queros             -0.1532 0.3110  925  -0.7634   0.4570
 Quimiri             0.0981 0.3790  876  -0.6452   0.8415
 Quincemil          -0.1945 0.0746  995  -0.3408  -0.0482
 Salvacion          -0.1259 0.0727  963  -0.2685   0.0167
 San Lorenzo         0.3246 0.1500  847   0.0308   0.6185
 Setapo              1.1185 0.4440  916   0.2466   1.9905
 Shintuya            0.7482 0.1370  933   0.4788   1.0177
 Shipitiari          1.1867 0.1930  958   0.8085   1.5650

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Here we see estimated means by community.</p>
</div>
</section><section id="section-9" class="slide level2" data-background-color="white"><h2></h2>
<div style="font-size:0.7em;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a><span class="fu">options</span>(<span class="at">width =</span> <span class="dv">120</span>)</span>
<span id="cb29-2"><a></a>paired<span class="sc">$</span>contrasts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                            estimate     SE   df t.ratio p.value
 Boca Colorado - Boca Isiriwe        -1.16471 0.2260  835  -5.142  0.0001
 Boca Colorado - Boca Manu           -0.82609 0.1660  996  -4.990  0.0002
 Boca Colorado - Caychihue            1.09529 0.1680 1033   6.528  &lt;.0001
 Boca Colorado - Choque               0.77238 0.1480 1067   5.219  0.0001
 Boca Colorado - Diamante            -1.00188 0.1350 1060  -7.407  &lt;.0001
 Boca Colorado - Huepetuhe            0.67104 0.0904 1078   7.423  &lt;.0001
 Boca Colorado - Isla de los Valles  -1.00742 0.3450  865  -2.923  0.3310
 Boca Colorado - Masenawa            -1.28740 0.4820 1196  -2.669  0.5206
 Boca Colorado - Palotoa Teparo      -0.33148 0.1940  926  -1.710  0.9889
 Boca Colorado - Puerto Azul         -1.17977 0.2960  937  -3.981  0.0143
 Boca Colorado - Puerto Luz          -0.50051 0.1380  879  -3.625  0.0504
 Boca Colorado - Punquiri             0.70929 0.2230 1018   3.183  0.1821
 Boca Colorado - Puquiri              0.02490 0.2500 1034   0.099  1.0000
 Boca Colorado - Quebrada Neuva       0.78252 0.1240 1019   6.302  &lt;.0001
 Boca Colorado - Queros               0.77015 0.3210  935   2.402  0.7282
 Boca Colorado - Quimiri              0.51883 0.3870  884   1.341  0.9996
 Boca Colorado - Quincemil            0.81149 0.1080 1050   7.500  &lt;.0001
 Boca Colorado - Salvacion            0.74286 0.1070 1036   6.949  &lt;.0001
 Boca Colorado - San Lorenzo          0.29234 0.1690  896   1.730  0.9872
 Boca Colorado - Setapo              -0.50155 0.4510  921  -1.112  1.0000
 Boca Colorado - Shintuya            -0.13127 0.1580  972  -0.830  1.0000
 Boca Colorado - Shipitiari          -0.56975 0.2080  977  -2.738  0.4661
 Boca Isiriwe - Boca Manu             0.33862 0.2580  853   1.314  0.9997
 Boca Isiriwe - Caychihue             2.25999 0.2590  867   8.721  &lt;.0001
 Boca Isiriwe - Choque                1.93709 0.2470  862   7.849  &lt;.0001
 Boca Isiriwe - Diamante              0.16282 0.2390  849   0.680  1.0000
 Boca Isiriwe - Huepetuhe             1.83574 0.2170  813   8.452  &lt;.0001
 Boca Isiriwe - Isla de los Valles    0.15728 0.3970  839   0.396  1.0000
 Boca Isiriwe - Masenawa             -0.12270 0.5210 1121  -0.235  1.0000
 Boca Isiriwe - Palotoa Teparo        0.83323 0.2770  840   3.011  0.2745
 Boca Isiriwe - Puerto Azul          -0.01507 0.3560  880  -0.042  1.0000
 Boca Isiriwe - Puerto Luz            0.66420 0.2410  802   2.756  0.4523
 Boca Isiriwe - Punquiri              1.87400 0.2980  897   6.293  &lt;.0001
 Boca Isiriwe - Puquiri               1.18960 0.3190  920   3.730  0.0354
 Boca Isiriwe - Quebrada Neuva        1.94723 0.2330  830   8.347  &lt;.0001
 Boca Isiriwe - Queros                1.93486 0.3770  885   5.138  0.0001
 Boca Isiriwe - Quimiri               1.68353 0.4340  858   3.877  0.0212
 Boca Isiriwe - Quincemil             1.97619 0.2250  823   8.776  &lt;.0001
 Boca Isiriwe - Salvacion             1.90756 0.2250  820   8.494  &lt;.0001
 Boca Isiriwe - San Lorenzo           1.45704 0.2600  819   5.606  &lt;.0001
 Boca Isiriwe - Setapo                0.66316 0.4920  894   1.347  0.9996
 Boca Isiriwe - Shintuya              1.03344 0.2530  840   4.085  0.0097
 Boca Isiriwe - Shipitiari            0.59495 0.2870  870   2.074  0.9120
 Boca Manu - Caychihue                1.92138 0.2080  991   9.237  &lt;.0001
 Boca Manu - Choque                   1.59847 0.1920 1003   8.309  &lt;.0001
 Boca Manu - Diamante                -0.17580 0.1830  993  -0.962  1.0000
 Boca Manu - Huepetuhe                1.49713 0.1530  971   9.811  &lt;.0001
 Boca Manu - Isla de los Valles      -0.18133 0.3660  871  -0.496  1.0000
 Boca Manu - Masenawa                -0.46132 0.4980 1177  -0.927  1.0000
 Boca Manu - Palotoa Teparo           0.49461 0.2300  923   2.155  0.8775
 Boca Manu - Puerto Azul             -0.35369 0.3210  934  -1.102  1.0000
 Boca Manu - Puerto Luz               0.32558 0.1850  896   1.761  0.9841
 Boca Manu - Punquiri                 1.53538 0.2550  994   6.032  &lt;.0001
 Boca Manu - Puquiri                  0.85099 0.2790 1010   3.050  0.2507
 Boca Manu - Quebrada Neuva           1.60861 0.1750  967   9.206  &lt;.0001
 Boca Manu - Queros                   1.59624 0.3430  933   4.648  0.0009
 Boca Manu - Quimiri                  1.34491 0.4060  887   3.314  0.1289
 Boca Manu - Quincemil                1.63757 0.1640  973   9.999  &lt;.0001
 Boca Manu - Salvacion                1.56895 0.1630  966   9.630  &lt;.0001
 Boca Manu - San Lorenzo              1.11842 0.2090  903   5.352  &lt;.0001
 Boca Manu - Setapo                   0.32454 0.4680  921   0.694  1.0000
 Boca Manu - Shintuya                 0.69482 0.2000  951   3.469  0.0821
 Boca Manu - Shipitiari               0.25633 0.2420  961   1.061  1.0000
 Caychihue - Choque                  -0.32291 0.1940 1030  -1.662  0.9922
 Caychihue - Diamante                -2.09717 0.1850 1023 -11.347  &lt;.0001
 Caychihue - Huepetuhe               -0.42425 0.1550 1013  -2.737  0.4672
 Caychihue - Isla de los Valles      -2.10271 0.3670  878  -5.730  &lt;.0001
 Caychihue - Masenawa                -2.38269 0.4990 1181  -4.779  0.0005
 Caychihue - Palotoa Teparo          -1.42676 0.2310  942  -6.172  &lt;.0001
 Caychihue - Puerto Azul             -2.27506 0.3220  943  -7.066  &lt;.0001
 Caychihue - Puerto Luz              -1.59579 0.1870  924  -8.539  &lt;.0001
 Caychihue - Punquiri                -0.38600 0.2560 1009  -1.508  0.9979
 Caychihue - Puquiri                 -1.07039 0.2800 1023  -3.818  0.0259
 Caychihue - Quebrada Neuva          -0.31277 0.1770 1000  -1.768  0.9833
 Caychihue - Queros                  -0.32513 0.3450  941  -0.944  1.0000
 Caychihue - Quimiri                 -0.57646 0.4070  893  -1.417  0.9991
 Caychihue - Quincemil               -0.28380 0.1660 1010  -1.709  0.9889
 Caychihue - Salvacion               -0.35243 0.1650 1004  -2.133  0.8874
 Caychihue - San Lorenzo             -0.80295 0.2110  925  -3.810  0.0268
 Caychihue - Setapo                  -1.59683 0.4680  925  -3.409  0.0982
 Caychihue - Shintuya                -1.22656 0.2020  975  -6.068  &lt;.0001
 Caychihue - Shipitiari              -1.66504 0.2430  978  -6.846  &lt;.0001
 Choque - Diamante                   -1.77426 0.1670 1047 -10.622  &lt;.0001
 Choque - Huepetuhe                  -0.10134 0.1330 1048  -0.760  1.0000
 Choque - Isla de los Valles         -1.77980 0.3580  876  -4.967  0.0002
 Choque - Masenawa                   -2.05978 0.4920 1189  -4.185  0.0064
 Choque - Palotoa Teparo             -1.10385 0.2170  945  -5.081  0.0001
 Choque - Puerto Azul                -1.95215 0.3120  945  -6.254  &lt;.0001
 Choque - Puerto Luz                 -1.27288 0.1690  924  -7.517  &lt;.0001
 Choque - Punquiri                   -0.06309 0.2430 1019  -0.259  1.0000
 Choque - Puquiri                    -0.74748 0.2690 1032  -2.779  0.4342
 Choque - Quebrada Neuva              0.01014 0.1580 1020   0.064  1.0000
 Choque - Queros                     -0.00222 0.3350  942  -0.007  1.0000
 Choque - Quimiri                    -0.25355 0.3990  892  -0.635  1.0000
 Choque - Quincemil                   0.03911 0.1460 1038   0.268  1.0000
 Choque - Salvacion                  -0.02952 0.1450 1030  -0.204  1.0000
 Choque - San Lorenzo                -0.48004 0.1950  926  -2.457  0.6873
 Choque - Setapo                     -1.27392 0.4620  925  -2.759  0.4498
 Choque - Shintuya                   -0.90365 0.1860  986  -4.858  0.0003
 Choque - Shipitiari                 -1.34213 0.2300  985  -5.835  &lt;.0001
 Diamante - Huepetuhe                 1.67292 0.1190 1035  14.051  &lt;.0001
 Diamante - Isla de los Valles       -0.00554 0.3530  870  -0.016  1.0000
 Diamante - Masenawa                 -0.28552 0.4890 1190  -0.584  1.0000
 Diamante - Palotoa Teparo            0.67041 0.2090  933   3.211  0.1695
 Diamante - Puerto Azul              -0.17789 0.3060  939  -0.581  1.0000
 Diamante - Puerto Luz                0.50138 0.1580  901   3.167  0.1899
 Diamante - Punquiri                  1.71117 0.2360 1014   7.252  &lt;.0001
 Diamante - Puquiri                   1.02678 0.2620 1029   3.917  0.0181
 Diamante - Quebrada Neuva            1.78440 0.1460 1007  12.192  &lt;.0001
 Diamante - Queros                    1.77204 0.3300  937   5.371  &lt;.0001
 Diamante - Quimiri                   1.52071 0.3940  887   3.855  0.0228
 Diamante - Quincemil                 1.81337 0.1330 1025  13.626  &lt;.0001
 Diamante - Salvacion                 1.74474 0.1320 1016  13.214  &lt;.0001
 Diamante - San Lorenzo               1.29422 0.1860  910   6.961  &lt;.0001
 Diamante - Setapo                    0.50034 0.4580  923   1.093  1.0000
 Diamante - Shintuya                  0.87061 0.1760  973   4.944  0.0002
 Diamante - Shipitiari                0.43213 0.2220  977   1.946  0.9523
 Huepetuhe - Isla de los Valles      -1.67846 0.3390  856  -4.956  0.0002
 Huepetuhe - Masenawa                -1.95844 0.4780 1197  -4.097  0.0090
 Huepetuhe - Palotoa Teparo          -1.00251 0.1830  901  -5.480  &lt;.0001
 Huepetuhe - Puerto Azul             -1.85081 0.2890  927  -6.397  &lt;.0001
 Huepetuhe - Puerto Luz              -1.17154 0.1220  817  -9.584  &lt;.0001
 Huepetuhe - Punquiri                 0.03825 0.2130 1007   0.179  1.0000
 Huepetuhe - Puquiri                 -0.64614 0.2420 1026  -2.669  0.5205
 Huepetuhe - Quebrada Neuva           0.11148 0.1060  974   1.049  1.0000
 Huepetuhe - Queros                   0.09912 0.3140  927   0.315  1.0000
 Huepetuhe - Quimiri                 -0.15221 0.3810  877  -0.399  1.0000
 Huepetuhe - Quincemil                0.14045 0.0871  998   1.613  0.9947
 Huepetuhe - Salvacion                0.07182 0.0855  975   0.840  1.0000
 Huepetuhe - San Lorenzo             -0.37870 0.1560  859  -2.422  0.7131
 Huepetuhe - Setapo                  -1.17258 0.4470  917  -2.626  0.5553
 Huepetuhe - Shintuya                -0.80231 0.1450  940  -5.552  &lt;.0001
 Huepetuhe - Shipitiari              -1.24079 0.1980  960  -6.269  &lt;.0001
 Isla de los Valles - Masenawa       -0.27998 0.5820 1070  -0.481  1.0000
 Isla de los Valles - Palotoa Teparo  0.67595 0.3800  863   1.781  0.9819
 Isla de los Valles - Puerto Azul    -0.17235 0.4410  883  -0.391  1.0000
 Isla de los Valles - Puerto Luz      0.50692 0.3540  847   1.430  0.9990
 Isla de los Valles - Punquiri        1.71671 0.3950  893   4.344  0.0034
 Isla de los Valles - Puquiri         1.03232 0.4110  907   2.509  0.6474
 Isla de los Valles - Quebrada Neuva  1.78994 0.3490  862   5.126  0.0001
 Isla de los Valles - Queros          1.77758 0.4580  886   3.885  0.0205
 Isla de los Valles - Quimiri         1.52625 0.5060  866   3.016  0.2714
 Isla de los Valles - Quincemil       1.81891 0.3440  860   5.290  &lt;.0001
 Isla de los Valles - Salvacion       1.75028 0.3430  858   5.096  0.0001
 Isla de los Valles - San Lorenzo     1.29976 0.3680  853   3.536  0.0669
 Isla de los Valles - Setapo          0.50588 0.5570  893   0.908  1.0000
 Isla de los Valles - Shintuya        0.87615 0.3630  865   2.416  0.7179
 Isla de los Valles - Shipitiari      0.43767 0.3870  878   1.131  1.0000
 Masenawa - Palotoa Teparo            0.95593 0.5080 1157   1.882  0.9665
 Masenawa - Puerto Azul               0.10763 0.5550 1119   0.194  1.0000
 Masenawa - Puerto Luz                0.78690 0.4890 1172   1.608  0.9949
 Masenawa - Punquiri                  1.99669 0.5200 1165   3.842  0.0236
 Masenawa - Puquiri                   1.31230 0.5320 1162   2.466  0.6805
 Masenawa - Quebrada Neuva            2.06992 0.4860 1189   4.263  0.0046
 Masenawa - Queros                    2.05756 0.5690 1109   3.619  0.0509
 Masenawa - Quimiri                   1.80623 0.6080 1060   2.970  0.2997
 Masenawa - Quincemil                 2.09889 0.4820 1193   4.357  0.0031
 Masenawa - Salvacion                 2.03026 0.4810 1193   4.217  0.0056
 Masenawa - San Lorenzo               1.57974 0.4990 1162   3.166  0.1895
 Masenawa - Setapo                    0.78586 0.6510 1057   1.207  0.9999
 Masenawa - Shintuya                  1.15614 0.4950 1176   2.334  0.7752
 Masenawa - Shipitiari                0.71765 0.5130 1161   1.398  0.9993
 Palotoa Teparo - Puerto Azul        -0.84830 0.3360  917  -2.522  0.6373
 Palotoa Teparo - Puerto Luz         -0.16903 0.2110  863  -0.803  1.0000
 Palotoa Teparo - Punquiri            1.04077 0.2740  958   3.801  0.0276
 Palotoa Teparo - Puquiri             0.35637 0.2970  977   1.201  0.9999
 Palotoa Teparo - Quebrada Neuva      1.11399 0.2020  911   5.521  &lt;.0001
 Palotoa Teparo - Queros              1.10163 0.3580  918   3.078  0.2355
 Palotoa Teparo - Quimiri             0.85030 0.4180  879   2.033  0.9267
 Palotoa Teparo - Quincemil           1.14296 0.1920  909   5.942  &lt;.0001
 Palotoa Teparo - Salvacion           1.07433 0.1920  904   5.606  &lt;.0001
 Palotoa Teparo - San Lorenzo         0.62381 0.2320  875   2.688  0.5056
 Palotoa Teparo - Setapo             -0.17007 0.4780  913  -0.356  1.0000
 Palotoa Teparo - Shintuya            0.20021 0.2240  909   0.893  1.0000
 Palotoa Teparo - Shipitiari         -0.23828 0.2620  928  -0.910  1.0000
 Puerto Azul - Puerto Luz             0.67927 0.3080  906   2.209  0.8502
 Puerto Azul - Punquiri               1.88906 0.3540  953   5.339  &lt;.0001
 Puerto Azul - Puquiri                1.20467 0.3720  965   3.240  0.1571
 Puerto Azul - Quebrada Neuva         1.96229 0.3020  930   6.507  &lt;.0001
 Puerto Azul - Queros                 1.94993 0.4220  925   4.617  0.0010
 Puerto Azul - Quimiri                1.69860 0.4740  893   3.580  0.0582
 Puerto Azul - Quincemil              1.99126 0.2950  930   6.742  &lt;.0001
 Puerto Azul - Salvacion              1.92263 0.2950  928   6.520  &lt;.0001
 Puerto Azul - San Lorenzo            1.47211 0.3230  908   4.563  0.0013
 Puerto Azul - Setapo                 0.67823 0.5280  919   1.284  0.9998
 Puerto Azul - Shintuya               1.04851 0.3170  927   3.307  0.1312
 Puerto Azul - Shipitiari             0.61002 0.3450  935   1.770  0.9832
 Puerto Luz - Punquiri                1.20980 0.2380  952   5.092  0.0001
 Puerto Luz - Puquiri                 0.52540 0.2640  977   1.993  0.9395
 Puerto Luz - Quebrada Neuva          1.28302 0.1490  859   8.613  &lt;.0001
 Puerto Luz - Queros                  1.27066 0.3310  908   3.838  0.0242
 Puerto Luz - Quimiri                 1.01933 0.3950  868   2.578  0.5936
 Puerto Luz - Quincemil               1.31199 0.1360  846   9.651  &lt;.0001
 Puerto Luz - Salvacion               1.24336 0.1350  837   9.216  &lt;.0001
 Puerto Luz - San Lorenzo             0.79284 0.1880  826   4.218  0.0057
 Puerto Luz - Setapo                 -0.00104 0.4590  908  -0.002  1.0000
 Puerto Luz - Shintuya                0.36924 0.1780  872   2.071  0.9130
 Puerto Luz - Shipitiari             -0.06925 0.2240  911  -0.309  1.0000
 Punquiri - Puquiri                  -0.68439 0.3160 1018  -2.163  0.8735
 Punquiri - Quebrada Neuva            0.07323 0.2300 1000   0.319  1.0000
 Punquiri - Queros                    0.06087 0.3740  950   0.163  1.0000
 Punquiri - Quimiri                  -0.19046 0.4320  904  -0.440  1.0000
 Punquiri - Quincemil                 0.10220 0.2220 1005   0.461  1.0000
 Punquiri - Salvacion                 0.03357 0.2210 1002   0.152  1.0000
 Punquiri - San Lorenzo              -0.41695 0.2570  949  -1.624  0.9942
 Punquiri - Setapo                   -1.21084 0.4910  932  -2.467  0.6801
 Punquiri - Shintuya                 -0.84056 0.2500  984  -3.366  0.1112
 Punquiri - Shipitiari               -1.27904 0.2840  984  -4.503  0.0017
 Puquiri - Quebrada Neuva             0.75762 0.2570 1018   2.953  0.3108
 Puquiri - Queros                     0.74526 0.3910  961   1.904  0.9620
 Puquiri - Quimiri                    0.49393 0.4470  916   1.104  1.0000
 Puquiri - Quincemil                  0.78659 0.2490 1023   3.156  0.1949
 Puquiri - Salvacion                  0.71796 0.2490 1021   2.887  0.3554
 Puquiri - San Lorenzo                0.26744 0.2810  971   0.952  1.0000
 Puquiri - Setapo                    -0.52644 0.5040  939  -1.045  1.0000
 Puquiri - Shintuya                  -0.15617 0.2750 1002  -0.569  1.0000
 Puquiri - Shipitiari                -0.59465 0.3060  998  -1.942  0.9532
 Quebrada Neuva - Queros             -0.01236 0.3260  929  -0.038  1.0000
 Quebrada Neuva - Quimiri            -0.26369 0.3910  881  -0.675  1.0000
 Quebrada Neuva - Quincemil           0.02897 0.1220  977   0.238  1.0000
 Quebrada Neuva - Salvacion          -0.03966 0.1210  965  -0.329  1.0000
 Quebrada Neuva - San Lorenzo        -0.49018 0.1780  880  -2.754  0.4541
 Quebrada Neuva - Setapo             -1.28406 0.4550  918  -2.824  0.4005
 Quebrada Neuva - Shintuya           -0.91379 0.1680  944  -5.449  &lt;.0001
 Quebrada Neuva - Shipitiari         -1.35227 0.2150  959  -6.276  &lt;.0001
 Queros - Quimiri                    -0.25133 0.4900  895  -0.513  1.0000
 Queros - Quincemil                   0.04133 0.3200  929   0.129  1.0000
 Queros - Salvacion                  -0.02730 0.3190  927  -0.085  1.0000
 Queros - San Lorenzo                -0.47782 0.3450  910  -1.385  0.9994
 Queros - Setapo                     -1.27170 0.5420  919  -2.345  0.7676
 Queros - Shintuya                   -0.90142 0.3400  926  -2.652  0.5343
 Queros - Shipitiari                 -1.33991 0.3660  934  -3.663  0.0444
 Quimiri - Quincemil                  0.29266 0.3860  880   0.758  1.0000
 Quimiri - Salvacion                  0.22403 0.3860  879   0.581  1.0000
 Quimiri - San Lorenzo               -0.22649 0.4070  872  -0.556  1.0000
 Quimiri - Setapo                    -1.02037 0.5840  899  -1.748  0.9855
 Quimiri - Shintuya                  -0.65009 0.4030  882  -1.614  0.9947
 Quimiri - Shipitiari                -1.08858 0.4250  892  -2.562  0.6064
 Quincemil - Salvacion               -0.06863 0.1040  979  -0.659  1.0000
 Quincemil - San Lorenzo             -0.51915 0.1670  874  -3.104  0.2215
 Quincemil - Setapo                  -1.31303 0.4510  918  -2.914  0.3364
 Quincemil - Shintuya                -0.94275 0.1560  946  -6.033  &lt;.0001
 Quincemil - Shipitiari              -1.38124 0.2070  962  -6.684  &lt;.0001
 Salvacion - San Lorenzo             -0.45052 0.1660  868  -2.707  0.4906
 Salvacion - Setapo                  -1.24440 0.4500  917  -2.764  0.4461
 Salvacion - Shintuya                -0.87413 0.1550  939  -5.626  &lt;.0001
 Salvacion - Shipitiari              -1.31261 0.2060  958  -6.372  &lt;.0001
 San Lorenzo - Setapo                -0.79388 0.4690  909  -1.693  0.9901
 San Lorenzo - Shintuya              -0.42361 0.2030  885  -2.085  0.9076
 San Lorenzo - Shipitiari            -0.86209 0.2440  914  -3.532  0.0676
 Setapo - Shintuya                    0.37028 0.4650  917   0.796  1.0000
 Setapo - Shipitiari                 -0.06821 0.4840  922  -0.141  1.0000
 Shintuya - Shipitiari               -0.43849 0.2370  949  -1.853  0.9716

Degrees-of-freedom method: kenward-roger 
P value adjustment: tukey method for comparing a family of 23 estimates </code></pre>
</div>
</div>
<p>We can also examine estimated differences between means (these do have a multiple comparisons adjustment applied).</p>
</div>
</section><section id="section-10" class="slide level2" data-background-color="white"><h2></h2>
<p>To learn more about <em>random effects models</em>, also known as <em>hierarchical</em> or <em>multilevel</em> models, check out STA 210 or STA 221 (regression analysis) sometime!</p>
</section></section><section><section id="regression-models-with-categorical-explanatory-variables" class="title-slide slide level1 center"><h1>Regression models with categorical explanatory variables</h1>

</section><section id="categorical-predictor-with-2-levels" class="slide level2"><h2>Categorical predictor with 2 levels</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<div class="sourceCode" id="cb31"><pre class="sourceCode numberSource small number-lines code-with-copy"><code class="sourceCode"><span id="cb31-1"><a></a># A tibble: 2,308 × 3</span>
<span id="cb31-2"><a></a>   lhairHg assets_sc[,1] native_cat</span>
<span id="cb31-3"><a></a>     &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt;     </span>
<span id="cb31-4"><a></a> 1  0.676         -0.837 Non-native</span>
<span id="cb31-5"><a></a> 2  0.0908         0.197 Non-native</span>
<span id="cb31-6"><a></a> 3  1.67          -0.280 Non-native</span>
<span id="cb31-7"><a></a> 4  0.450         -0.280 Non-native</span>
<span id="cb31-8"><a></a> 5  0.704         -0.280 Non-native</span>
<span id="cb31-9"><a></a> 6 -0.512         -0.280 Non-native</span>
<span id="cb31-10"><a></a> 7 -0.125          0.826 Non-native</span>
<span id="cb31-11"><a></a> 8 -0.103          0.826 Non-native</span>
<span id="cb31-12"><a></a> 9  0.351         -1.27  Non-native</span>
<span id="cb31-13"><a></a>10  0.0444        -1.27  Non-native</span>
<span id="cb31-14"><a></a>11  0.662         -0.359 Non-native</span>
<span id="cb31-15"><a></a>12  1.01           1.29  Non-native</span>
<span id="cb31-16"><a></a>13 -0.149          1.29  Non-native</span>
<span id="cb31-17"><a></a>14  0.881          0.517 Non-native</span>
<span id="cb31-18"><a></a>15  1.51           0.517 Non-native</span>
<span id="cb31-19"><a></a>16  0.328         -0.658 Non-native</span>
<span id="cb31-20"><a></a>17  0.0553         0.533 Non-native</span>
<span id="cb31-21"><a></a>18  0.768          1.29  Non-native</span>
<span id="cb31-22"><a></a>19  0.431          1.30  Non-native</span>
<span id="cb31-23"><a></a>20  1.55           1.30  Non-native</span>
<span id="cb31-24"><a></a># ℹ 2,288 more rows</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li>
<code>Native</code>: community classified as native by Peruvian government</li>
<li>
<code>Non-native</code>: community does not have native classification</li>
</ul>
</div></div>
</section><section id="mercury-native-community-relationship" class="slide level2"><h2>Mercury &amp; native community relationship</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a></a>  <span class="fu">fit</span>(lhairHg <span class="sc">~</span> native_cat, <span class="at">data =</span> mercury) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term                 estimate std.error statistic   p.value
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)              1.12    0.0416      26.9 4.97e-139
2 native_catNon-native    -1.11    0.0476     -23.2 2.94e-107</code></pre>
</div>
</div>
</section><section id="mercury-and-native-communities" class="slide level2"><h2>Mercury and native communities</h2>
<div style="font-size:0.7em;">
<p>Define <span class="math inline">\(\text{Non-native}_i\)</span>=1 if non-native community and 0 otherwise.</p>
<p><span class="math display">\[\widehat{y_i} = 1.12 - 1.11~\text{Non-native}_i\]</span></p>
<ul>
<li>
<strong>Slope:</strong> Residents of non-native communities, on average, are expected to have Hg concentrations that are -1.11 log ppm lower, on average, than residents of native communities. Alternatively, the hair Hg is expected to be lower, on average, by a factor of <span class="math inline">\(e^{-1.11}=0.33\)</span> among residents of non-native communities. The geometric mean of hair Hg is estimated to be <span class="math inline">\(100\left(1-e^{-1.11}\right)=67\%\)</span> lower among residents of non-native communities than among residents of native communities, holding other predictors fixed.
<ul>
<li>Compares baseline level (<code>Native</code>) to the other level (<code>Non-native</code>)</li>
</ul>
</li>
<li>
<strong>Intercept:</strong> Individuals living in native communities (<code>Non-native</code>=0) are expected to have hair mercury exposures of 1.12 log ppm.</li>
</ul>
</div>
</section><section id="relationship-between-mercury-and-individual-community-1" class="slide level2"><h2>Relationship between mercury and individual community</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>com_fit <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a></a>  <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a></a>  <span class="fu">fit</span>(lhairHg <span class="sc">~</span> community, <span class="at">data =</span> mercury) </span>
<span id="cb34-4"><a></a></span>
<span id="cb34-5"><a></a><span class="fu">tidy</span>(com_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 5
   term                     estimate std.error statistic  p.value
   &lt;chr&gt;                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)                 0.614    0.0644      9.54 3.55e-21
 2 communityBoca Isiriwe       1.20     0.159       7.56 5.77e-14
 3 communityBoca Manu          0.833    0.129       6.43 1.56e-10
 4 communityCaychihue         -1.10     0.132      -8.36 1.09e-16
 5 communityChoque            -0.778    0.117      -6.68 3.04e-11
 6 communityDiamante           1.06     0.109       9.67 1.00e-21
 7 communityHuepetuhe         -0.694    0.0732     -9.48 5.96e-21
 8 communityIsla de los Va…    1.12     0.245       4.57 5.18e- 6
 9 communityMasenawa           1.20     0.401       3.00 2.74e- 3
10 communityPalotoa Teparo     0.350    0.148       2.36 1.82e- 2
# ℹ 13 more rows</code></pre>
</div>
</div>
</section><section id="dummy-or-indicator-variables" class="slide level2"><h2>Dummy or indicator variables</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23 × 5
   term                     estimate std.error statistic  p.value
   &lt;chr&gt;                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)                0.614     0.0644     9.54  3.55e-21
 2 communityBoca Isiriwe      1.20      0.159      7.56  5.77e-14
 3 communityBoca Manu         0.833     0.129      6.43  1.56e-10
 4 communityCaychihue        -1.10      0.132     -8.36  1.09e-16
 5 communityChoque           -0.778     0.117     -6.68  3.04e-11
 6 communityDiamante          1.06      0.109      9.67  1.00e-21
 7 communityHuepetuhe        -0.694     0.0732    -9.48  5.96e-21
 8 communityIsla de los Va…   1.12      0.245      4.57  5.18e- 6
 9 communityMasenawa          1.20      0.401      3.00  2.74e- 3
10 communityPalotoa Teparo    0.350     0.148      2.36  1.82e- 2
11 communityPuerto Azul       1.22      0.230      5.27  1.45e- 7
12 communityPuerto Luz        0.494     0.0991     4.98  6.67e- 7
13 communityPunquiri         -0.678     0.176     -3.84  1.26e- 4
14 communityPuquiri           0.0842    0.192      0.439 6.61e- 1
15 communityQuebrada Neuva   -0.812     0.0966    -8.41  7.21e-17
16 communityQueros           -0.707     0.245     -2.89  3.93e- 3
17 communityQuimiri          -0.621     0.274     -2.26  2.38e- 2
18 communityQuincemil        -0.822     0.0858    -9.57  2.55e-21
19 communitySalvacion        -0.732     0.0850    -8.61  1.31e-17
20 communitySan Lorenzo      -0.245     0.124     -1.98  4.82e- 2
21 communitySetapo            0.517     0.319      1.62  1.05e- 1
22 communityShintuya          0.130     0.122      1.07  2.86e- 1
23 communityShipitiari        0.532     0.161      3.30  9.65e- 4</code></pre>
</div>
</div>
<div style="font-size:0.9em;">
<ul>
<li>When the categorical explanatory variable has many levels, they’re encoded to <strong>dummy</strong> or <strong>indicator variables</strong>
</li>
<li>Each coefficient describes the expected difference between log mercury concentrations in that particular community compared to the baseline community</li>
</ul>
</div>
</section><section id="categorical-predictor-with-3-levels" class="slide level2"><h2>Categorical predictor with 3+ levels</h2>
<p>Here is how you code the indicator variables.</p>
<div style="font-size:0.5em;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="margin-left: auto; margin-right: auto;">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">community</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">BI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">BM</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Cay</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Cho</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Dia</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Hue</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Isl</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Mas</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Boca Colorado</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Boca Isiriwe</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boca Manu</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Caychihue</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Choque</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diamante</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huepetuhe</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Isla de los Valles</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Masenawa</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: center; width: 10em; color: white !important; background-color: rgba(68, 1, 84, 255) !important;">0</td>
<td style="text-align: left; width: 10em; color: white !important; background-color: rgba(122, 209, 81, 255) !important;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>etc. for the other communities. Note Boca Colorado, the <em>referent community</em>, =0 for all vars. This is closely related to <strong>one-hot encoding</strong>.</p>
</div>
</section><section id="relationship-between-mercury-and-community" class="slide level2"><h2>Relationship between mercury and community</h2>
<div style="font-size:0.4em;">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<div class="sourceCode" id="cb37"><pre class="sourceCode numberSource tiny number-lines code-with-copy"><code class="sourceCode"><span id="cb37-1"><a></a># A tibble: 23 × 5</span>
<span id="cb37-2"><a></a>   term                     estimate std.error statistic  p.value</span>
<span id="cb37-3"><a></a>   &lt;chr&gt;                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;</span>
<span id="cb37-4"><a></a> 1 (Intercept)                0.614     0.0644     9.54  3.55e-21</span>
<span id="cb37-5"><a></a> 2 communityBoca Isiriwe      1.20      0.159      7.56  5.77e-14</span>
<span id="cb37-6"><a></a> 3 communityBoca Manu         0.833     0.129      6.43  1.56e-10</span>
<span id="cb37-7"><a></a> 4 communityCaychihue        -1.10      0.132     -8.36  1.09e-16</span>
<span id="cb37-8"><a></a> 5 communityChoque           -0.778     0.117     -6.68  3.04e-11</span>
<span id="cb37-9"><a></a> 6 communityDiamante          1.06      0.109      9.67  1.00e-21</span>
<span id="cb37-10"><a></a> 7 communityHuepetuhe        -0.694     0.0732    -9.48  5.96e-21</span>
<span id="cb37-11"><a></a> 8 communityIsla de los Va…   1.12      0.245      4.57  5.18e- 6</span>
<span id="cb37-12"><a></a> 9 communityMasenawa          1.20      0.401      3.00  2.74e- 3</span>
<span id="cb37-13"><a></a>10 communityPalotoa Teparo    0.350     0.148      2.36  1.82e- 2</span>
<span id="cb37-14"><a></a>11 communityPuerto Azul       1.22      0.230      5.27  1.45e- 7</span>
<span id="cb37-15"><a></a>12 communityPuerto Luz        0.494     0.0991     4.98  6.67e- 7</span>
<span id="cb37-16"><a></a>13 communityPunquiri         -0.678     0.176     -3.84  1.26e- 4</span>
<span id="cb37-17"><a></a>14 communityPuquiri           0.0842    0.192      0.439 6.61e- 1</span>
<span id="cb37-18"><a></a>15 communityQuebrada Neuva   -0.812     0.0966    -8.41  7.21e-17</span>
<span id="cb37-19"><a></a>16 communityQueros           -0.707     0.245     -2.89  3.93e- 3</span>
<span id="cb37-20"><a></a>17 communityQuimiri          -0.621     0.274     -2.26  2.38e- 2</span>
<span id="cb37-21"><a></a>18 communityQuincemil        -0.822     0.0858    -9.57  2.55e-21</span>
<span id="cb37-22"><a></a>19 communitySalvacion        -0.732     0.0850    -8.61  1.31e-17</span>
<span id="cb37-23"><a></a>20 communitySan Lorenzo      -0.245     0.124     -1.98  4.82e- 2</span>
<span id="cb37-24"><a></a>21 communitySetapo            0.517     0.319      1.62  1.05e- 1</span>
<span id="cb37-25"><a></a>22 communityShintuya          0.130     0.122      1.07  2.86e- 1</span>
<span id="cb37-26"><a></a>23 communityShipitiari        0.532     0.161      3.30  9.65e- 4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div class="tiny">
<ul>
<li>
<strong>Boca Colorado</strong> hair mercury levels are expected, on average, to be <strong>0.614 log ppm</strong>. The estimated geometric mean hair mercury level among residents of <strong>Boca Colorado</strong> is <span class="math inline">\(e^{0.614} \approx \mathbf{1.85}\)</span> ppm.</li>
<li>
<strong>Boca Isiriwe</strong> hair mercury levels are expected, on average, to be <strong>1.2 log ppm higher</strong> than <em>Boca Colorado</em> levels, at <strong>1.814 log ppm</strong> on average. The estimated geometric mean hair mercury level among residents of <strong>Boca Isiriwe</strong> is <span class="math inline">\(100(e^{1.2}-1) \approx \mathbf{232\%}\)</span> higher than among residents of <strong>Boca Colorado</strong>. (Note: 1.85+2.32*1.85=6.142, and <span class="math inline">\(\exp^{0.614+1.2}=6.13\)</span>)</li>
<li>
<strong>Caychihue</strong> hair mercury levels are expected, on average, to be <strong>1.10 log ppm lower</strong> than <em>Boca Colorado</em> levels, at <strong>-0.486 log ppm</strong> on average. The estimated geometric mean hair mercury level among residents of <strong>Caychihue</strong> is <span class="math inline">\(100(1-\exp^{-1.1}) \approx \mathbf{67\%}\)</span> lower than among residents of <strong>Boca Colorado</strong>.</li>
<li>etc. It can be nice to have a table showing the estimated mean (along with uncertainty measures – coming soon) for each community, and a plot can also be useful.</li>
</ul>
</div>
</div>
</section><section id="regression-and-anova" class="slide level2"><h2>Regression and ANOVA</h2>
<div style="font-size:0.8em;">
<p>You might be wondering how this model differs from the ANOVA model we just presented when exploring how community is related to mercury levels. In fact, the two models are equivalent! In our ANOVA discussion, we specified our model as <span class="math display">\[y_{ij}=\mu_i+\varepsilon_{ij}\]</span> with a separate mean <span class="math inline">\(\mu_i\)</span> for each community, <span class="math inline">\(\mu_1, \mu_2, \ldots, \mu_{23}\)</span>.</p>
<p>Here, we fit the same model with a slightly different <strong>coding scheme</strong>, where we define the regression model intercept <span class="math inline">\(\beta_0\)</span> to be the mean for the <strong>reference</strong> community, Boca Colorado, and the regression model parameters <span class="math inline">\(\beta_1, \beta_2, \ldots, \beta_{22}\)</span> each measure the difference in mercury levels between Boca Colorado and the community of interest.</p>
</div>
</section><section id="anova-as-regression" class="slide level2"><h2>ANOVA as Regression</h2>
<div style="font-size:0.8em;">
<p>Our model thus is <span class="math display">\[y_i=\beta_0 + \beta_1\text{Boca Isiriwe}_i + \beta_2\text{Boca Manu}_i + \ldots + \beta_{22}\text{Shipitiari}_i + \varepsilon_i\]</span> where <span class="math inline">\(\text{Boca Manu}_i\)</span> is an indicator variable that takes value 1 if the measurement is from a resident of Boca Manu, and it takes value 0 otherwise.</p>
</div>
</section><section id="section-11" class="slide level2" data-background-color="white"><h2></h2>
<p>The mean for each community is given below.</p>
<p>Boca Colorado: <span class="math inline">\(\beta_0\)</span></p>
<p>Boca Isiriwe: <span class="math inline">\(\beta_0+\beta_1\)</span></p>
<p>Boca Manu: <span class="math inline">\(\beta_0 + \beta_2\)</span> … Shipitiari: <span class="math inline">\(\beta_0+\beta_{22}\)</span></p>
<p>In the ANOVA model, the Boca Colorado mean was <span class="math inline">\(\mu_1\)</span>, the Boca Isiriwe mean was <span class="math inline">\(\mu_2\)</span>, etc. There is a 1:1 correspondence between the parameters in the two formulations with <span class="math inline">\(\mu_1=\beta_0,\)</span> <span class="math inline">\(\mu_2=\beta_0+\beta_1\)</span>, etc.</p>
</section><section id="correspondence-between-regression-and-anova" class="slide level2"><h2>Correspondence between regression and ANOVA</h2>
<p>Here we can compare the F test from the regression model with that from ANOVA.</p>
<p>Regression:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a>res <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(lhairHg<span class="sc">~</span>community, <span class="at">data =</span> mercury))</span>
<span id="cb38-2"><a></a><span class="fu">print</span>(res<span class="sc">$</span>fstatistic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     value      numdf      dendf 
  52.81756   22.00000 2285.00000 </code></pre>
</div>
</div>
</section><section id="section-12" class="slide level2" data-background-color="white"><h2></h2>
<p>ANOVA:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">summary</span>(<span class="fu">aov</span>(lhairHg<span class="sc">~</span>community,<span class="at">data=</span>mercury))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
community     22  909.6   41.34   52.82 &lt;2e-16 ***
Residuals   2285 1788.7    0.78                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
1775 observations deleted due to missingness</code></pre>
</div>
</div>
<p>We get the same F statistic and degrees of freedom fitting the model using either parameterization!</p>


</section></section>
</div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p><a href="https://sta198-fa26-2.github.io/">🔗 sta198-fa26-2.github.io</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="../site_libs/revealjs/dist/reveal.js"></script><!-- reveal.js plugins --><script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script><script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script><script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script><script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script><script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script><script src="../site_libs/revealjs/plugin/notes/notes.js"></script><script src="../site_libs/revealjs/plugin/search/search.js"></script><script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script><script src="../site_libs/revealjs/plugin/math/math.js"></script><script>window.define = window.backupDefine; window.backupDefine = undefined;</script><script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': true,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script><script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script><script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/sta198-fa26-2\.github\.io\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>


</body></html>