{
  "hash": "d4664ecec9ca0a805a278b7027764ec9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic Regression\"\nsubtitle: \"Introduction to Global Health Data Science\"\nauthor: \"Prof. Amy Herring\"\nformat:\n  revealjs:\n    output-file: w12-l03-logistic-slides.html\n    footer: \"[🔗 sta198-fa26-2.github.io](https://sta198-fa26-2.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    pdf-separate-fragments: true\n    toc: false\n  html:\n    code-link: true\neditor_options:\n  chunk_output_type: console\n---\n\n\n\n## Our question\n\nWe will use the same **2024 U.S. birth records** introduced in the birth weight labs.\n\n**How are maternal characteristics associated with birth before 37 completed weeks, called preterm birth?**\n\n- Outcome: **preterm birth**, defined as `combgest < 37`.\n- Predictors: maternal age group, pre-pregnancy BMI category, smoking during pregnancy, gestational diabetes, and plurality.\n\nThis is an analysis of associations in observational data.\n\n*Source: [NCHS 2024 natality public-use data](https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm)*\n\n## Preparing the birth records\n\nThe lab used term births only. Here we must **include preterm births** to study the outcome.\n\n\n\nWe keep valid gestational ages, maternal ages, and known values of the predictors. Unknown smoking status, BMI, and gestational diabetes status are excluded. We draw a new sample of 10,000 births; the earlier lab's term-only sample cannot answer this question.\n\n## Variables of interest\n\n<div style=\"font-size:0.7em;\">\n\n\n| Variable | In the data | In our analysis |\n|:--|:--|:--|\n| Gestational age | `combgest` | `preterm`: Yes if less than 37 weeks |\n| Maternal age | `mager` | `<15`, `15–39`, or `40+` years |\n| Pre-pregnancy BMI | `bmi_r` | Underweight (<18.5), normal (18.5–24.9), overweight (25–29.9), obese (≥30) |\n| Smoking during pregnancy | `cig_rec` | `smoking`: No or Yes |\n| Gestational diabetes | `rf_gdiab` | `gest_diabetes`: No or Yes |\n| Plurality | `dplural` | Singleton or multiple birth |\n\n`bmi_r` measures **pre-pregnancy** BMI; its three obesity codes are combined here. Ages 40 and above are in `40+`, so the middle group ends at 39.\n\nA birth at **37 completed weeks** belongs to the **term birth** group.\n\n</div>\n\n## How many births in our sample are preterm?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanalysis_births %>%\n  count(preterm) %>%\n  mutate(percent = scales::percent(n / sum(n), accuracy = 0.1)) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|preterm |    n|percent |\n|:-------|----:|:-------|\n|No      | 8826|88.3%   |\n|Yes     | 1174|11.7%   |\n\n\n:::\n:::\n\n\n**Which outcome should we code as the event of interest?** Here `Yes` is the second factor level, so the fitted model targets the probability of preterm birth.\n\n## Preterm birth and smoking\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nanalysis_births %>%\n  ggplot(aes(x = smoking, fill = preterm)) +\n  geom_bar(position = \"fill\") +\n  scale_y_continuous(labels = scales::label_percent()) +\n  scale_fill_manual(values = c(\"No\" = \"#B9AEC8\", \"Yes\" = \"#012169\")) +\n  labs(x = \"Smoking during pregnancy\", y = \"Proportion of births\",\n       fill = \"Preterm\")\n```\n\n::: {.cell-output-display}\n![](w12-l03-logistic_files/figure-revealjs/preterm-by-smoking-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n## Preterm birth and gestational diabetes\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nanalysis_births %>%\n  ggplot(aes(x = gest_diabetes, fill = preterm)) +\n  geom_bar(position = \"fill\") +\n  scale_y_continuous(labels = scales::label_percent()) +\n  scale_fill_manual(values = c(\"No\" = \"#B9AEC8\", \"Yes\" = \"#012169\")) +\n  labs(x = \"Gestational diabetes\", y = \"Proportion of births\",\n       fill = \"Preterm\")\n```\n\n::: {.cell-output-display}\n![](w12-l03-logistic_files/figure-revealjs/preterm-by-diabetes-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n## Preterm birth and plurality\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nanalysis_births %>%\n  ggplot(aes(x = plurality, fill = preterm)) +\n  geom_bar(position = \"fill\") +\n  scale_y_continuous(labels = scales::label_percent()) +\n  scale_fill_manual(values = c(\"No\" = \"#B9AEC8\", \"Yes\" = \"#012169\")) +\n  labs(x = \"Plurality\", y = \"Proportion of births\", fill = \"Preterm\")\n```\n\n::: {.cell-output-display}\n![](w12-l03-logistic_files/figure-revealjs/preterm-by-plurality-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n## Preterm birth and pre-pregnancy BMI\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nanalysis_births %>%\n  ggplot(aes(x = bmi_category, fill = preterm)) +\n  geom_bar(position = \"fill\") +\n  scale_x_discrete(limits = c(\"Underweight\", \"Normal\", \"Overweight\", \"Obese\")) +\n  scale_y_continuous(labels = scales::label_percent()) +\n  scale_fill_manual(values = c(\"No\" = \"#B9AEC8\", \"Yes\" = \"#012169\")) +\n  labs(x = \"Pre-pregnancy BMI category\", y = \"Proportion of births\",\n       fill = \"Preterm\")\n```\n\n::: {.cell-output-display}\n![](w12-l03-logistic_files/figure-revealjs/preterm-by-bmi-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n## Preterm birth and maternal age group\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nanalysis_births %>%\n  ggplot(aes(x = age_group, fill = preterm)) +\n  geom_bar(position = \"fill\") +\n  scale_x_discrete(limits = c(\"<15\", \"15-39\", \"40+\")) +\n  scale_y_continuous(labels = scales::label_percent()) +\n  scale_fill_manual(values = c(\"No\" = \"#B9AEC8\", \"Yes\" = \"#012169\")) +\n  labs(x = \"Maternal age group (years)\", y = \"Proportion of births\",\n       fill = \"Preterm\")\n```\n\n::: {.cell-output-display}\n![](w12-l03-logistic_files/figure-revealjs/preterm-by-age-group-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n**Question:** Why can we describe associations from these plots but not infer that a predictor caused a preterm birth?\n\n## Framing the outcome\n\nFor birth $i$, define\n\n$$Y_i=\\begin{cases}1 & \\text{if gestational age is less than 37 weeks},\\\\\n0 & \\text{otherwise.}\\end{cases}$$\n\nEach $Y_i$ has two possible values. We can model it with a Bernoulli distribution:\n\n$$Y_i\\sim\\operatorname{Bernoulli}(\\pi_i),\\qquad\n\\pi_i=P(Y_i=1\\mid X_i).$$\n\nThe probability $\\pi_i$ can depend on the birth's predictors $X_i$. This relaxes our assumption about previous binomial data, in which everyone needed to have the same probability $\\pi$ of the outcome.\n\n## Why not ordinary linear regression?\n\nIf we model $\\pi_i$ directly with a straight line, a prediction could be less than 0 or greater than 1.\n\nWe need a model that permits a linear combination of predictors **and** produces valid probabilities between 0 and 1.\n\n**Logistic regression** connects the linear predictor to the probability through the logit function.\n\n## Three pieces of a generalized linear model\n\n1. **Outcome distribution:** $Y_i\\sim\\operatorname{Bernoulli}(\\pi_i)$.\n\n2. **Linear predictor:** $\\eta_i=\\beta_0+\\beta_1 X_{1i}+\\cdots+\\beta_k X_{ki}$.\n\n3. **Link function:** $\\operatorname{logit}(\\pi_i)=\\eta_i$.\n\nOrdinary linear regression also has these three pieces, but uses a normal distribution and the identity link.\n\n## Log odds\n\nFor an event with probability $\\pi$:\n\n$$\\text{odds}=\\frac{\\pi}{1-\\pi},\\qquad\n\\operatorname{logit}(\\pi)=\\log\\left(\\frac{\\pi}{1-\\pi}\\right).$$\n\n- $\\pi=0.5$ gives odds of $1$ and log odds of $0$.\n- $\\pi<0.5$ gives negative log odds.\n- $\\pi>0.5$ gives positive log odds.\n\nThe logit is defined for $0<\\pi<1$.\n\n## The logit function\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l03-logistic_files/figure-revealjs/logit-plot-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\n## From log odds back to probability\n\nThe inverse logit converts **any** linear predictor $\\eta_i$ into a probability:\n\n$$\\pi_i=\\frac{\\exp(\\eta_i)}{1+\\exp(\\eta_i)}\n=\\frac{1}{1+\\exp(-\\eta_i)}.$$\n\nWhen $\\eta_i=0$, the probability is $0.5$. A positive value produces a probability above $0.5$; a negative value produces a probability below $0.5$.\n\n## What is an indicator variable?\n\n<div style=\"font-size:0.85em;\">\n\n\nAn **indicator variable** records whether a condition is true (1) or false (0). For example,\n\n$$\nI(\\text{maternal age}<15)=\n\\begin{cases}\n1 & \\text{if the mother is younger than 15},\\\\\n0 & \\text{if the mother is 15 or older}.\n\\end{cases}\n$$\n\n| Maternal age | $I(\\text{age}<15)$ |\n|--:|--:|\n| 14 | 1 |\n| 15 | 0 |\n| 25 | 0 |\n| 45 | 0 |\n\n\n</div>\n\n## {background-color=\"white\"}\n\n\n<div style=\"font-size:0.85em;\">\n\n\n$$\nI(\\text{maternal age}>40)=\n\\begin{cases}\n1 & \\text{if the mother is older than 40},\\\\\n0 & \\text{if the mother is 40 or younger}.\n\\end{cases}\n$$\n\n| Maternal age | $I(\\text{age}\\ge40)$ |\n|--:|--:|\n| 14 | 0 |\n| 15 | 0 |\n| 25 | 0 |\n| 45 | 1 |\n\n</div>\n\n\n## {background-color=\"white\"}\n\n\n<div style=\"font-size:0.85em;\">\n\nSo looking at both indicator variables together, we understand the age group of the participant.\n\n| Maternal age | $I(\\text{age}<15)$ | $I(\\text{age}\\ge40)$ |\n|--:|--:|--:|\n| 14 | 1 | 0 |\n| 15 | 0 | 0 |\n| 25 | 0 | 0 |\n| 45 | 0 | 1 |\n\n\nIn a logistic regression, the indicator lets us compare mothers **under 15** with the reference group, mothers **15-39**. Its exponentiated coefficient is the odds ratio for that comparison. Similarly, we can also compare older mothers to the reference group.\n\n\n</div>\n\n\n## A model with maternal age group\n\nUse ages **15–39** as the reference group. The model adds one indicator for ages under 15 and another for ages 40 or older:\n\n$$\\operatorname{logit}(\\pi_i)=\\beta_0\n+\\beta_1 I(\\text{age}<15)_i\n+\\beta_2 I(\\text{age}\\ge40)_i.$$\n\nThe intercept $\\beta_0$ is the log odds of preterm birth for the 15–39 group. We call this model an *unadjusted model* because it only assesses the effects of a single predictor, maternal age.\n\n\n## Fit the age-group model\n\n<div style=\"font-size:0.75em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nage_fit <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  fit(preterm ~ age_group, data = analysis_births)\n\ntidy(age_fit, conf.int = TRUE) %>%\n  mutate(across(where(is.numeric), ~round(.x, 3))) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|term         | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)  |   -2.046|     0.032|   -63.631|   0.000|   -2.110|    -1.984|\n|age_group<15 |    0.948|     1.155|     0.820|   0.412|   -2.059|     3.004|\n|age_group40+ |    0.519|     0.127|     4.096|   0.000|    0.265|     0.762|\n\n\n:::\n:::\n\n\nThe model estimates one coefficient for **under 15 versus 15–39** and another for **40+ versus 15–39**.\n\n</div>\n\n\n## Odds ratios for the age groups\n\nThe fitted odds for ages 15–39 and 40+ are\n\n$$\\text{odds}_{15\\text{–}39}=\\exp(\\beta_0),\\qquad\n\\text{odds}_{40+}=\\exp(\\beta_0+\\beta_2).$$\n\nThus $\\exp(\\beta_2)$ is the odds ratio for **40+ versus 15–39**. Similarly, $\\exp(\\beta_1)$ compares **under 15 versus 20–39**.\n\nThese comparisons are for **groups**, rather than for a one-year or ten-year difference.\n\n## Tests and confidence intervals\n\nThe two coefficient tests ask separate questions:\n\n- $H_0:\\beta_1=0$ tests whether the **under-15** group differs from ages 15–39.\n- $H_0:\\beta_2=0$ tests whether the **40+** group differs from ages 15–39.\n\nThe test used is based on a $z$-score constructed by taking our estimate, subtracting 0, and then dividing by the standard deviation of our estimate.\n\n## Tests and confidence intervals\n\nExponentiating each coefficient and its confidence limits gives the odds ratio and its confidence interval for that comparison.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(age_fit, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  select(term, estimate, conf.low, conf.high, p.value) %>%\n  mutate(across(where(is.numeric), ~round(.x, 3))) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|term         | estimate| conf.low| conf.high| p.value|\n|:------------|--------:|--------:|---------:|-------:|\n|age_group<15 |    2.579|    0.128|    20.166|   0.412|\n|age_group40+ |    1.680|    1.303|     2.142|   0.000|\n\n\n:::\n:::\n\n\n*The usual model standard errors treat birth records as independent; births from the same multiple pregnancy will violate this assumption.*\n\n## Interpreting results\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term         | estimate| conf.low| conf.high| p.value|\n|:------------|--------:|--------:|---------:|-------:|\n|age_group<15 |    2.579|    0.128|    20.166|   0.412|\n|age_group40+ |    1.680|    1.303|     2.142|   0.000|\n\n\n:::\n:::\n\n\nMothers aged $<15$ do not have significantly different risk of preterm birth as mothers aged 15-39.  Mothers aged 40+ have 1.68 (1.30, 2.14) times the odds of preterm birth as their counterparts aged 15-39.\n\n\n\n## Multiple logistic regression\n\n<div style=\"font-size:0.75em;\">\n\n\nNow include the five predictors. We call this type of model a *multiple logistic regression model* or an *adjusted* model. The age and BMI categories enter the model through indicator variables:\n\n$$\n\\begin{aligned}\n\\log\\left(\\frac{\\pi_i}{1-\\pi_i}\\right)\n={}& \\beta_0\n+\\beta_1 I(\\text{age}_i<15)\n+\\beta_2 I(\\text{age}_i\\ge 40)\\\\\n&+\\beta_3 I(\\text{BMI}_i=\\text{Underweight})\n+\\beta_4 I(\\text{BMI}_i=\\text{Overweight})\\\\\n&+\\beta_5 I(\\text{BMI}_i=\\text{Obese})\n+\\beta_6 I(\\text{smoking}_i=\\text{Yes})\\\\\n&+\\beta_7 I(\\text{gestational diabetes}_i=\\text{Yes})\n+\\beta_8 I(\\text{plurality}_i=\\text{Multiple birth}).\n\\end{aligned}\n$$\n\nReference group: **ages 15–39**, **normal BMI**, **no smoking**, **no gestational diabetes**, and **singleton**.\n\n</div>\n\n## Fit the multiple logistic model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbirth_fit <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  fit(preterm ~ age_group + bmi_category + smoking +\n        gest_diabetes + plurality,\n      data = analysis_births)\n```\n:::\n\n\nWe use `exponentiate = TRUE` to turn the coefficients into odds ratios. Each estimate compares one category with its reference category while holding the other predictors fixed.\n\n## Adjusted odds ratios for age and BMI\n\n<div style=\"font-size:0.75em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(birth_fit, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(str_starts(term, \"age_group\") |\n           str_starts(term, \"bmi_category\")) %>%\n  select(term, estimate, conf.low, conf.high, p.value) %>%\n  mutate(across(where(is.numeric), ~round(.x, 3))) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|term                    | estimate| conf.low| conf.high| p.value|\n|:-----------------------|--------:|--------:|---------:|-------:|\n|age_group<15            |    3.427|    0.169|    26.845|   0.287|\n|age_group40+            |    1.615|    1.238|     2.083|   0.000|\n|bmi_categoryUnderweight |    1.858|    1.265|     2.663|   0.001|\n|bmi_categoryOverweight  |    1.139|    0.966|     1.342|   0.122|\n|bmi_categoryObese       |    1.335|    1.145|     1.556|   0.000|\n\n\n:::\n:::\n\n\nEach age-group estimate compares with **ages 15–39**. Each BMI estimate compares with **normal pre-pregnancy BMI**. For each comparison, we assume no other predictor values change.\n\n</div>\n\n\n## {background-color=\"white\"}\n\n\n<div style=\"font-size:0.75em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                    | estimate| conf.low| conf.high| p.value|\n|:-----------------------|--------:|--------:|---------:|-------:|\n|age_group<15            |    3.427|    0.169|    26.845|   0.287|\n|age_group40+            |    1.615|    1.238|     2.083|   0.000|\n|bmi_categoryUnderweight |    1.858|    1.265|     2.663|   0.001|\n|bmi_categoryOverweight  |    1.139|    0.966|     1.342|   0.122|\n|bmi_categoryObese       |    1.335|    1.145|     1.556|   0.000|\n\n\n:::\n:::\n\n\nMothers aged 40+ have 1.62 (1.24, 2.08) times the odds of preterm birth as mothers aged 15-39, adjusting for BMI, smoking status, gestational diabetes status, and plurality. Underweight mothers have 1.86 (1.27, 2.66) times the odds of preterm birth as their normal weight counterparts, and obese mothers have 1.34 (1.15, 1.56) times the odds of preterm birth as their normal weight counterparts, adjusting for maternal age, smoking status, gestational diabetes status, and plurality. Thus both age and BMI are predictors of the probability of preterm birth.\n</div>\n\n\n\n\n## Adjusted odds ratios for the other predictors\n\n<div style=\"font-size:0.75em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(birth_fit, conf.int = TRUE, exponentiate = TRUE) %>%\n  filter(term != \"(Intercept)\",\n         !str_starts(term, \"age_group\"),\n         !str_starts(term, \"bmi_category\")) %>%\n  select(term, estimate, conf.low, conf.high, p.value) %>%\n  mutate(across(where(is.numeric), ~round(.x, 3))) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|term                    | estimate| conf.low| conf.high| p.value|\n|:-----------------------|--------:|--------:|---------:|-------:|\n|smokingYes              |    1.893|    1.355|     2.598|   0.000|\n|gest_diabetesYes        |    1.346|    1.091|     1.650|   0.005|\n|pluralityMultiple birth |   12.013|    9.480|    15.264|   0.000|\n\n\n:::\n:::\n\n\nFor example, `smokingYes` compares reported smoking with no smoking among births with the same age group, BMI category, diabetes status, and plurality.\n\n</div>\n\n## {background-color=\"white\"}\n\n<div style=\"font-size:0.75em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                    | estimate| conf.low| conf.high| p.value|\n|:-----------------------|--------:|--------:|---------:|-------:|\n|smokingYes              |    1.893|    1.355|     2.598|   0.000|\n|gest_diabetesYes        |    1.346|    1.091|     1.650|   0.005|\n|pluralityMultiple birth |   12.013|    9.480|    15.264|   0.000|\n\n\n:::\n:::\n\n\nMaternal smoking, gestational diabetes, and higher-order pregnancies also convey greater risk of preterm birth. Women smoking during pregnancy have 1.89 (1.36, 2.60) times the odds of preterm birth as their nonsmoking counterparts, after adjustment for maternal age, BMI, gestational diabetes status, and the multiplicity of the pregnancy. Similarly, gestational diabetes is associated with 1.35 (1.09, 1.65) times the odds of preterm birth, and a multiple pregnancy is associated with a whopping 12.0 (9.5, 15.3) times the odds of preterm birth, after adjusting for the other factors in the model.\n\n</div>\n\n\n# Why Did the Odds Ratio Change?\n\n## Simple and Multiple Logistic Regression\n\n<div style=\"font-size:0.75em;\">\n\n\n:::: {.columns}\n\n::: {.column width=\"48%\"}\n\n**Simple (unadjusted) model**\n\n$$\n\\begin{aligned}\n\\operatorname{logit}\\{P(Y_i=1\\mid X_i)\\}\n&= \\alpha_0+\\alpha_1X_i.\n\\end{aligned}\n$$\n\nFor a one-unit increase in $X$, the estimated **crude odds ratio** is\n\n$$\n\\widehat{OR}_{\\text{crude}}=e^{\\hat{\\alpha}_1}.\n$$\n\n:::\n\n::: {.column width=\"48%\"}\n\n**Multiple (adjusted) model**\n\n$$\n\\begin{aligned}\n\\operatorname{logit}\\{P(Y_i=1\\mid X_i,\\mathbf Z_i)\\}\n&= \\beta_0+\\beta_1X_i\\\\\n&\\quad+\\beta_2Z_{2i}+\\cdots+\\beta_pZ_{pi}.\n\\end{aligned}\n$$\n\nHolding the other predictors constant, the estimated **adjusted odds ratio** is\n\n$$\n\\widehat{OR}_{\\text{adjusted}}=e^{\\hat{\\beta}_1}.\n$$\n\n:::\n\n::::\n\n</div>\n\n## The Models Compare Different Groups\n\nThe two odds ratios answer different questions.\n\n- **Crude OR:** How do the odds of $Y=1$ compare for groups that differ by one unit in $X$, without accounting for other predictors?\n\n- **Adjusted OR:** How do the odds compare for groups that differ by one unit in $X$ but have the **same values of the other predictors**?\n\nFor binary $X$, this compares $X=1$ with $X=0$.\n\nThe adjusted interpretation assumes the model does not include interactions involving $X$.\n\n## Confounding\n\n<div style=\"font-size:0.85em;\">\n\n\nA **confounder** is a variable that creates a noncausal association between the predictor of interest and the outcome.\n\nFor example, a third variable $Z$ may influence both $X$ and $Y$:\n\n$$\nX \\leftarrow Z \\rightarrow Y.\n$$\n\n- The groups defined by $X$ differ in their distribution of $Z$.\n- Because $Z$ also predicts $Y$, the crude association mixes the relationship of interest with differences in $Z$.\n- Adjusting for $Z$ compares groups with the **same value of $Z$**.\n\nSubject-matter knowledge helps us decide which variables to adjust for.\n\n</div>\n\n## How Can Confounding Change an Association?\n\n<div style=\"font-size:0.75em;\">\n\n\nConfounding can make an association appear **stronger**, **weaker**, or even point in the **opposite direction**.\n\n| Pattern | What can happen after appropriate adjustment? |\n|:--|:--|\n| Crude association exaggerated | The OR moves closer to 1. |\n| Crude association masked | The OR moves further from 1. |\n| Crude association reversed | The OR changes from above 1 to below 1, or vice versa. |\n\nA reversal between an overall association and associations within subgroups is an example of **Simpson's paradox**.\n\nA change in the estimated OR alone does **not** establish that a variable is a confounder.\n\n</div>\n\n## A Simulated Example of Confounding\n\nSuppose $Z$ influences both $X$ and $Y$.\n\nFor each observation $i=1,\\ldots,n$:\n\n$$\n\\begin{aligned}\nZ_i &\\sim \\operatorname{Bernoulli}(0.5),\\\\[6pt]\n\\operatorname{logit}\\!\\left\\{P(X_i=1\\mid Z_i)\\right\\}\n&= -1+2Z_i,\\\\[6pt]\n\\operatorname{logit}\\!\\left\\{P(Y_i=1\\mid X_i,Z_i)\\right\\}\n&= -1+0.5X_i+1.5Z_i.\n\\end{aligned}\n$$\n\nHere, $X_i$ and $Y_i$ are binary, and\n$\\operatorname{logit}(p)=\\log\\{p/(1-p)\\}$.\n\nThus, $Z$ predicts both $X$ and $Y$, while $X$ also predicts $Y$.\n\n## {background-color=\"white\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2024)\nn <- 20000\nz <- rbinom(n, 1, 0.5)\nx <- rbinom(n, 1, plogis(-1 + 2 * z))\ny <- rbinom(n, 1, plogis(-1 + 0.5 * x + 1.5 * z))\n\nor_confounding_data <- data.frame(\n  x,\n  y = factor(y, levels = c(0, 1)),\n  z\n)\n```\n:::\n\n\n- $X=1$ is more common among those with $Z=1$.\n- $Z=1$ also increases the probability of $Y=1$.\n- Holding $Z$ constant, the true OR for $X$ is $e^{0.5}\\approx1.65$.\n\n## Compare the Crude and Adjusted Odds Ratios\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nor_confounding_simple <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  fit(y ~ x, data = or_confounding_data)\n\nor_confounding_adjusted <- logistic_reg() %>%\n  set_engine(\"glm\") %>%\n  fit(y ~ x + z, data = or_confounding_data)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n|Model    | Estimated OR| 95% CI: lower| 95% CI: upper|\n|:--------|------------:|-------------:|-------------:|\n|Crude    |        3.042|         2.872|         3.223|\n|Adjusted |        1.645|         1.540|         1.757|\n:::\n\n\nBoth models use the **same observations**.\n\n## What Happened in This Example?\n\nThe simulation was constructed so that $Z$ influences both $X$ and $Y$.\n\n- In the simple model, $X$ partly stands in for $Z$.\n- Some of the higher odds of $Y=1$ among those with $X=1$ reflect their greater probability of having $Z=1$.\n- After adjustment, the estimated OR should be near the true conditional OR of **1.65**.\n\nFor this data-generating mechanism, the population crude OR is approximately **3.05**, compared with the conditional OR of **1.65**.\n\nThe simulated estimates will vary around these values.\n\n## Interpreting a Change After Adjustment\n\n1. **Compare the same observations.** Added predictors may have missing values, causing the adjusted model to use a smaller sample.\n\n2. **Use subject-matter knowledge.** Decide whether a variable could create a noncausal association between $X$ and $Y$.\n\n3. **Interpret the adjusted OR conditionally.** State which variables are being held constant.\n\n4. **Avoid causal conclusions from adjustment alone.** Including additional predictors does not automatically make an association causal.\n\n\n## Homework (Practice)\n\n[**IMS Chapter 9**](https://openintrostat.github.io/ims/model-logistic.html#sec-chp09-exercises)\n\n- Problem 3\n\n\n",
    "supporting": [
      "w12-l03-logistic_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}