{
  "hash": "7b2a047aec0a67cb3fde7c475ad2a027",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Model Fitting and Interpretation: Part II\"\nsubtitle: \"Introduction to Global Health Data Science\"\ndate: \"2026-10-19\"\nformat:\n  revealjs:\n    output-file: w09-01-fit-interp-slides.html \n    footer: \"[🔗 sta198-fa26-2.github.io](https://sta198-fa26-2.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    pdf-separate-fragments: true\n    toc: false\n  html:\n    code-link: true\nfilters: \n  - ../remove-fmt-skip.lua\neditor_options: \n  chunk_output_type: console\n---\n\n\n## Working with the log transformed response\n\n<div style=\"font-size:0.8em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlHgfit <- linear_reg() %>% \n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc, data = mercury)\nlHgfit %>% tidy(conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 7\n#>   term        estimate std.error statistic  p.value conf.low conf.high\n#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n#> 1 (Intercept)    0.280    0.0213      13.1 7.49e-38    0.238     0.321\n#> 2 assets_sc     -0.358    0.0216     -16.5 3.90e-58   -0.400    -0.315\n```\n\n\n:::\n\n```{.r .cell-code}\nlHgfit %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 12\n#>   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n#>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n#> 1     0.106         0.106  1.02      274. 3.90e-58     1 -3316. 6638. 6655.\n#>   deviance df.residual  nobs\n#>      <dbl>       <int> <int>\n#> 1    2407.        2298  2300\n```\n\n\n:::\n:::\n\n\n</div>\n\n## Slope and intercept\n\n$$\n\\widehat{\\text{lhairHg}}_i\n  = 0.280 - 0.358\\,\\text{assets\\_sc}_i\n$$\n\n\n<div style=\"font-size:0.8em;\">\n\n::: {.incremental}\n\n- **Slope:** When assets are one standard deviation higher, the log hair mercury level is expected to be lower, on average, by 0.358 log ppm.\n  - perhaps not a very useful statement given the scale\n- **Intercept:** Individuals with household assets at the mean level (`assets_sc`=0) are expected to have hair mercury concentrations of 0.280 log ppm, on average\n  - Remember `assets_sc` was standardized, so `assets_sc`=0 does not mean \"no assets\" but instead means \"average assets\" as it corresponds to an assets z-score of 0. \n  \n:::\n\n</div>\n\n## Slope and intercept: easy/standard case\n\n<div style=\"font-size:0.8em;\">\n\nInterpretation is a little easier without a log transformation. Suppose our outcome $y$ is exam score, and the predictor $x$ is hours studied, and we fit a linear model and get the following estimated line.\n\n::: {.large}\n$$\\widehat{y}_{i} = 60 + 5 \\times x_{i}$$\n:::\n\n</div>\n\n<div style=\"font-size:0.7em;\">\n\n::: {.incremental}\n\n- **Slope:**  For each additional hour of study, the exam score is expected to be higher, on average, by 5 points.\n\n- **Intercept:** Individuals who do not study are expected to have exam scores of 60 points, on average\n\n- Note: now you can see the danger of extrapolating beyond the range of the data. We don't expect someone who studies 20 hours to have an exam score of 160 on a 100-point scale -- at some point, mastery (hopefully not futility!) is reached.\n\n:::\n\n</div>\n\n# Better Interpretation in Models with Log Transformation\n\n## Working with logs\n\n- Subtraction and logs: $log(a) − log(b) = log(a / b)$\n\n\n- Natural logarithm: $e^{log(x)} = x$\n\n\n- We can use these identities to \"undo\" the log transformation\n\n## Interpreting the slope\n\nThe slope coefficient for the log transformed model is -0.358, meaning the log mercury difference between people whose household incomes are one SD apart is predicted to be -0.358 (95% CI=(-0.400,-0.315)) log ppm.\n\n::: {.fragment}\n::: {.question}\nUsing this information, and properties of logs that we just reviewed, fill in the blanks in the following alternate interpretation of the slope:\n\n>For each additional SD the household assets are greater, the hair mercury concentration is expected to be `___` , on average, by a factor of `___`.\n:::\n:::\n\n## {background-color=\"white\"}\n\n<div style=\"font-size:0.75em;\">\n\n\n>For each additional increase in scaled assets, hair mercury content is expected to be `___` , on average, by a factor of `___`.\n\n$$ \\log(\\text{hair Hg for assets x+1}) - \\log(\\text{hair Hg for assets x}) = -0.358 $$\n\n::: {.fragment}\n$$ \\log\\left(\\frac{\\text{hair Hg for assets x+1}}{\\text{hair Hg for assets x}}\\right) = -0.358 $$\n:::\n\n::: {.fragment}\n$$ e^{\\log\\left(\\frac{\\text{Hg for assets x+1}}{\\text{Hg for assets x}}\\right)} = e^{-0.358} $$\n:::\n\n::: {.fragment}\n$$ \\frac{\\text{Hg for assets x+1}}{\\text{Hg for assets x}} \\approx 0.70 $$\n:::\n\n::: {.fragment}\nWhen assets are one standard deviation higher, the hair Hg is expected to be lower, on average, by a factor of 0.70.\n:::\n\n</div>\n\n## You said I didn't need a calculator!\n\n<div style=\"font-size:0.85em;\">\n\n\nYup, R can do this for you!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc, data = mercury)\nfit %>% tidy(exponentiate=TRUE, conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 7\n#>   term        estimate std.error statistic  p.value conf.low conf.high\n#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n#> 1 (Intercept)    1.32     0.0213      13.1 7.49e-38    1.27      1.38 \n#> 2 assets_sc      0.699    0.0216     -16.5 3.90e-58    0.670     0.730\n```\n\n\n:::\n:::\n\n\nWhen assets are one standard deviation higher, the hair Hg is expected to be lower, on average, by a factor of 0.70 (95% CI=(0.67, 0.73)).\n\n</div>\n\n## The Geometric Mean\n\n<div style=\"font-size:0.85em;\">\n\nThe **geometric mean** averages positive values on the log scale, then converts back:\n\n$$\n\\text{Geometric mean of } y\n= e^{\\,\\text{mean}(\\log y)}\n$$\n\n::: {.incremental}\n\n- Our model predicts the **mean of log hair mercury** at a given asset score.\n- Exponentiating that prediction gives the **geometric mean hair mercury** in ppm.\n- Therefore, $e^{-0.358}\\approx 0.70$ compares **two predicted geometric means**: at an asset score one standard deviation higher, the geometric mean is about **70% as high**, or **30% lower**.\n\n:::\n\n::: {.fragment}\n\nBecause mercury concentrations are right-skewed, the geometric mean is generally **lower than the arithmetic mean**. They should not be interpreted as the same quantity, strictly speaking.\n\n:::\n\n</div>\n\n## {background-color=\"white\"}\n\n\n\n**When is a geometric mean useful?**\n\n- For positive, right-skewed measurements, such as many exposure concentrations.\n- When we want to describe **proportional differences**: “30% lower” rather than “0.89 ppm lower.”\n- When a few very high values would strongly pull up the arithmetic mean.\n\nUse the **arithmetic mean** when the question is about the average amount in ppm or a total across people. A geometric mean requires positive values.\n\n\n\n## From a ratio to a percentage\n\nWe found that a one-standard-deviation increase in assets multiplies the predicted **geometric mean** hair mercury concentration by\n\n$$e^{-0.358} \\approx 0.70.$$\n\n::: {.incremental}\n\n- **0.70 times as high** means **70% as high**.\n- $100\\%(1-0.70)=30\\%$ lower.\n\n:::\n\n**Interpretation:** People whose household asset score is one standard deviation higher have a predicted geometric mean hair mercury concentration **about 30% lower**.\n\n## A reusable rule\n\nIf we fit a model for $\\log(y)$ and the slope is $\\widehat\\beta_1$:\n\n$$\n\\text{Multiplier for a one-unit increase in }x = e^{\\widehat\\beta_1}\n$$\n\nFor a model with a natural log-transformed response, a one-unit increase\nin a predictor corresponds to:\n\n- A **$100(e^{\\hat{\\beta}}-1)\\%$ increase** in the geometric mean of\n  the response if $\\hat{\\beta}>0$.\n\n- A **$100(1-e^{\\hat{\\beta}})\\%$ decrease** in the geometric mean of\n  the response if $\\hat{\\beta}<0$.\n\nThese interpretations hold other predictors fixed. For a categorical\npredictor, the comparison is with the reference category.\n\n\n\n## Let R do the conversion\n\n<div style=\"font-size:0.5em;\">\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n\n**Code**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(lHgfit$fit, conf.int = TRUE) %>%\n  filter(term == \"assets_sc\") %>%\n  mutate(\n    multiplier = exp(estimate),\n    percent_change = 100 * (exp(estimate) - 1),\n    ci_low = 100 * (exp(conf.low) - 1),\n    ci_high = 100 * (exp(conf.high) - 1)\n  ) %>%\n  select(term, multiplier, percent_change, ci_low, ci_high) %>%\n  mutate(across(where(is.numeric), ~round(.x, 1)))\n```\n:::\n\n\n:::\n\n::: {.column width=\"45%\"}\n\n**Output**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 5\n#>   term      multiplier percent_change ci_low ci_high\n#>   <chr>          <dbl>          <dbl>  <dbl>   <dbl>\n#> 1 assets_sc        0.7          -30.1    -33     -27\n```\n\n\n:::\n:::\n\n\n:::\n\n::::\n\n\n\n</div>\n\n\nThe estimate is approximately **−30.1%**. The 95% confidence interval is approximately **−33.0% to −27.0%**.\n\n\n## Interpreting the confidence interval\n\nFor a one-standard-deviation difference in household assets:\n\n$$\n95\\%\\ \\text{CI for the multiplier:}\\quad\n\\left(e^{-0.400},\\ e^{-0.315}\\right) \\approx (0.67,\\ 0.73).\n$$\n\n::: {.incremental}\n\n- The predicted geometric mean hair mercury concentration is estimated to be **27% to 33% lower** at the higher asset score.\n- The interval excludes a multiplier of **1**, equivalent to excluding a percentage change of **0%**.\n\n:::\n\n## What about the intercept?\n\n$$\n\\widehat{\\log(\\text{hair Hg})}\n   = 0.280 - 0.358\\,\\text{assets\\_sc}\n$$\n\n::: {.incremental}\n\n- At `assets_sc = 0` (average assets): $e^{0.280}\\approx\\mathbf{1.32}$ ppm.\n- At `assets_sc = 1`: $e^{0.280-0.358}\\approx\\mathbf{0.92}$ ppm.\n- Compare: $0.92/1.32\\approx 0.70$, or about **30% lower**.\n\n:::\n\n::: {.fragment}\n\nThese are predictions for the **geometric mean**, not the arithmetic mean mercury concentration in ppm.\n\n:::\n\n\n## Correlation does not imply causation\n\nRemember this when interpreting model coefficients!\n\n![](https://upload.wikimedia.org/wikipedia/commons/9/93/Correlation_vs_causation.png){width=65%}\n\n::: {.footnote}\nIllustration: [Rcragun, Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Correlation_vs_causation.png), CC BY 3.0\n:::\n\n## {background-color=\"white\"}\n\n\n![](https://imgs.xkcd.com/comics/correlation.png){width=65%}\n\n::: {.footnote}\nSource: [xkcd, “Correlation”](https://xkcd.com/552/)\n:::\n\n# Estimation Details\n\n## Linear model with a single predictor\n\n<div style=\"font-size:0.75em;\">\n\n\n- We're interested in $\\beta_0$ (population parameter for the intercept) and $\\beta_1$ (population parameter for the slope) in the following model:\n\n$$y_{i} = \\beta_0 + \\beta_1~x_{i}+\\varepsilon_i$$\n\nwhere $\\varepsilon$ represents random error around our mean\n\n::: {.fragment}\n- Tough luck, you can't have them...\n:::\n\n::: {.fragment}\n- So we use sample statistics to estimate them, using the notation  $b$ or $\\widehat{\\beta}$ to distinguish our estimates from the true parameters $\\beta$\n\n$\\widehat{y}_{i} = b_0 + b_1~x_{i}$ or $\\widehat{y}_i = \\widehat{\\beta}_0 + \\widehat{\\beta}_1~x_i$\n:::\n\n</div>\n\n## Least squares regression\n\n- The regression line minimizes the sum of squared residuals (the residuals are estimates of the error $\\varepsilon_i$).\n\n- If $e_i = y_i - \\hat{y}_i$, then, the regression line minimizes \n$\\sum_{i = 1}^n e_i^2$.\n\n- Why do we square the residuals?\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/least-squares-illustration-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Visualizing residuals\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/vis-res-1-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n## Visualizing residuals (cont.)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/vis-res-2-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n## Visualizing residuals (cont.)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/vis-res-3-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n\n## How well does the model fit? $R^2$\n\n<div style=\"font-size:0.7em;\">\n\n\nThe **coefficient of determination**, $R^2$, measures the proportion of variation in the response $y$ that is explained by the regression model.\n\n$$\nR^2\n=\n1 -\n\\frac{\\sum_{i=1}^n (y_i-\\widehat{y}_i)^2}\n     {\\sum_{i=1}^n (y_i-\\bar{y})^2}\n$$\n\n- $\\sum (y_i-\\widehat{y}_i)^2$: variation **not explained** by the model\n- $\\sum (y_i-\\bar{y})^2$: **total variation** in $y$\n\n::: {.fragment}\n$R^2$ ranges from **0 to 1**.\n\n- $R^2 = 0$: the model explains none of the variation in $y$\n- $R^2 = 1$: the model explains all of the variation in $y$\n:::\n\n::: {.fragment}\nFor simple linear regression with one predictor:\n\n$$\nR^2 = r^2\n$$\n:::\n\n</div>\n\n## {background-color=\"white\"}\n\n<div style=\"font-size:0.85em;\">\n\nWe can get $R^2$ from the glance function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc, data = mercury)\nfit %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 12\n#>   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n#>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n#> 1     0.106         0.106  1.02      274. 3.90e-58     1 -3316. 6638. 6655.\n#>   deviance df.residual  nobs\n#>      <dbl>       <int> <int>\n#> 1    2407.        2298  2300\n```\n\n\n:::\n:::\n\n\nWhile $R^2=0.106$ may seem quite low (the corresponding estimated correlation between $x$ and $y$ is $\\sqrt{0.106}=0.33$), it's actually not too alarming given that we have observational data from humans with highly variable activities and exposures.\n\n</div>\n\n\n## Properties of least squares regression\n\n<div style=\"font-size:0.65em;\">\n\n\n- The regression line goes through the center of mass point, the coordinates corresponding to average $x$ and average $y$, $(\\bar{x}, \\bar{y})$:  \n$$\\bar{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\bar{x} ~ \\rightarrow ~ \\hat{\\beta}_0 = \\bar{y} - \\hat{\\beta}_1 \\bar{x}$$\n\n::: {.fragment}\n- The slope has the same sign as the correlation coefficient: $\\hat{\\beta}_1 = r \\frac{s_y}{s_x}$\n  - $s_x$ is the standard deviation of the explanatory variable $x$, and $s_y$ is the standard deviation of the response variable $y$\n  - If $y$ varies a lot more than $x$ does (large $s_y$ relative to $s_x$), the slope will be steeper for the same correlation — a small change in $x$ corresponds to a much bigger typical change in $y$\n  - In our example, $s_x$ is the standard deviation of `assets_sc` (which is 1, since it was standardized), and $s_y$ is the standard deviation of `lhairHg`\n:::\n\n::: {.fragment}\n- The sum of the residuals is zero: $\\sum_{i = 1}^n e_i = 0$\n:::\n\n::: {.fragment}\n- The residuals and $x$ values are uncorrelated\n:::\n\n</div>\n\n\n\n# Model checking\n\n\n## \"Linear\" models\n\n- We're fitting a \"linear\" model, which assumes a linear relationship between our explanatory and response variables.\n- But how do we assess this?\n- We saw residual plots earlier -- let's dive in with more detail now!\n\n## Graphical diagnostic: residuals plot (ppm units)\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/residuals-plot-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\nhg_asset_fit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(hairHg ~ assets_sc, data = mercury)\nhg_asset_fit_aug <- augment(hg_asset_fit$fit)\nggplot(hg_asset_fit_aug, mapping = aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.5) +\n  geom_hline(yintercept = 0, color = \"gray\", lty = \"dashed\") +\n  labs(x = \"Predicted mercury (ppm)\", y = \"Residuals\")\n```\n:::\n\n\n## Augment\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhg_asset_fit_aug\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2,300 × 9\n#>    .rownames hairHg assets_sc[,1] .fitted .resid     .hat .sigma    .cooksd\n#>    <chr>      <dbl>         <dbl>   <dbl>  <dbl>    <dbl>  <dbl>      <dbl>\n#>  1 1          1.97         -0.837    3.05 -1.08  0.000750   2.77 0.0000571 \n#>  2 3          1.10          0.197    2.12 -1.03  0.000452   2.77 0.0000312 \n#>  3 11         5.34         -0.280    2.55  2.79  0.000471   2.77 0.000239  \n#>  4 13         1.57         -0.280    2.55 -0.981 0.000471   2.77 0.0000296 \n#>  5 14         2.02         -0.280    2.55 -0.528 0.000471   2.77 0.00000855\n#>  6 15         0.599        -0.280    2.55 -1.95  0.000471   2.77 0.000117  \n#>  7 16         0.883         0.826    1.56 -0.682 0.000737   2.77 0.0000224 \n#>  8 17         0.902         0.826    1.56 -0.663 0.000737   2.77 0.0000211 \n#>  9 19         1.42         -1.27     3.43 -2.01  0.00116    2.77 0.000308  \n#> 10 21         1.05         -1.27     3.43 -2.39  0.00116    2.77 0.000433  \n#> # ℹ 2,290 more rows\n#> # ℹ 1 more variable: .std.resid <dbl>\n```\n\n\n:::\n:::\n\n\n:::\n\n## More on `augment()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglimpse(hg_asset_fit_aug)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Rows: 2,300\n#> Columns: 9\n#> $ .rownames  <chr> \"1\", \"3\", \"11\", \"13\", \"14\", \"15\", \"16\", \"17\", \"19\", \"21\", \"…\n#> $ hairHg     <dbl> 1.9652, 1.0951, 5.3366, 1.5683, 2.0218, 0.5993, 0.8829, 0.9…\n#> $ assets_sc  <dbl[,1]> <matrix[26 x 1]>\n#> $ .fitted    <dbl> 3.045165, 2.124332, 2.549503, 2.549503, 2.549503, 2.549…\n#> $ .resid     <dbl> -1.0799648, -1.0292319, 2.7870974, -0.9812028, -0.5277029, …\n#> $ .hat       <dbl> 0.0007495801, 0.0004516563, 0.0004705556, 0.0004705556, 0.0…\n#> $ .sigma     <dbl> 2.769771, 2.769779, 2.769252, 2.769787, 2.769841, 2.769564,…\n#> $ .cooksd    <dbl> 5.708620e-05, 3.122263e-05, 2.385430e-04, 2.956514e-05, 8.5…\n#> $ .std.resid <dbl> -0.3901294, -0.3717471, 1.0066782, -0.3544029, -0.1906022, …\n```\n\n\n:::\n:::\n\n\n\n\n## Looking for...\n\n- Residuals distributed randomly around 0\n- With no visible pattern along the x or y axes\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Not hoping for...\n\n::: {.large}\n**Fan shapes**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-10-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n(Evidence of non-constant variance in residuals across the range of predicted values)\n\n## Not looking for...\n\n::: {.large}\n**Groups of patterns**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n(Evidence of a missing predictor)\n\n## Not looking for...\n\n::: {.large}\n**Other non-random structure**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n## Not looking for...\n\n::: {.large}\n**Any patterns!**\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## {background-color=\"white\"}\n\n\n::: {.question}\nWhat patterns does the residual plot reveal that should make us question whether a linear model is a good fit for modeling the relationship between mercury (ppm) and assets?\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n# Exploring linearity\n\n## Data: Mercury\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Mercury vs. assets\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n## Mercury vs assets\n\n::: {.question}\nWhich plot shows a more linear relationship?\n:::\n\n::: {.small}\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::::\n\n:::\n\n## Mercury and Assets, residuals\n\n::: {.question}\nWhich plot shows a residuals that are uncorrelated with predicted values from the model? Also, what is the unit of the residuals?\n:::\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-fit-interp_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::::\n\n## Transforming the data\n\n::: {.incremental}\n- We saw that `hairHg` has a right-skewed distribution, and the residuals of that model don't look great.\n- In these situations a transformation applied to the response variable may be useful.\n- In order to decide which transformation to use, we should examine the distribution of the response variable.\n- The extremely right skewed distribution suggests that a log transformation may \nbe useful.\n    - log = natural log, $ln$\n    - Default base of the `log` function in R is the natural log: <br>\n    `log(x, base = exp(1))`\n:::\n\n## Transformations\n\n<div style=\"font-size:0.8em;\">\n\n\n::: {.incremental}\n- Non-constant variance is one of the most common model violations, however it is usually fixable by transforming the response (y) variable.\n- The most common transformation when the response variable is right skewed is the log transform: $log(y)$, especially useful when the response variable is \n(extremely) right skewed.\n- This transformation is also useful for variance stabilization.\n- When using a log transformation on the response variable the interpretation of \nthe slope changes: *\"For each unit increase in x, y is expected on average to be higher/lower by a factor of $e^{\\hat{\\beta}_1}$.\"*\n- When the response is log-transformed, a one-unit increase in $x$ multiplies the predicted **geometric mean** of $y$ by $e^{\\hat{\\beta}_1}$. This corresponds to a percentage change of $100(e^{\\hat{\\beta}_1}-1)\\%$; a negative result means a decrease.\n- Another useful transformation is the square root: $\\sqrt{y}$, especially \nuseful when the response variable is a count.\n:::\n\n</div>\n\n## Transform, or learn more?\n\n- Data transformations may also be useful when the relationship is non-linear\n- However in those cases a polynomial regression may be more appropriate\n  + This is beyond the scope of this course, but you're welcomed to try it on your own, and I'd be happy to provide further guidance!\n\n\n\n## Aside: when $y = 0$\n\nIn some cases the value of the response variable might be 0, and\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlog(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] -Inf\n```\n\n\n:::\n:::\n\n\n::: {.fragment}\nThe trick is to add a very small number to the value of the response variable for these cases so that the `log` function can still be applied:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlog(0 + 0.00001)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] -11.51293\n```\n\n\n:::\n:::\n\n:::\n\n::: {.fragment}\nIf there are a lot of 0 values for $y$, this trick is not such a good idea, and you may need to take an alternative approach (e.g., a zero-inflated model).\n:::\n\n\n\n## Homework (Practice)\n\n[**IMS Chapter 7**](https://openintrostat.github.io/ims/model-slr.html#sec-chp7-exercises)\n\n- Problem 7\n- Problem 8\n- Problem 12\n- Problem 22\n- Problem 23\n\n",
    "supporting": [
      "w09-01-fit-interp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}