{
  "hash": "83ba17e324181ddc5744176a9b4e5197",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Model Fitting and Interpretation\"\nsubtitle: \"Introduction to Global Health Data Science\"\ndate: \"2026-10-14\"\nformat:\n  revealjs:\n    output-file: w08-02-fitting-interpretation-slides.html \n    footer: \"[🔗 sta198-fa26-2.github.io](https://sta198-fa26-2.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    pdf-separate-fragments: true\n    toc: false\n  html:\n    code-link: true\nfilters: \n  - ../remove-fmt-skip.lua\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n\n\n\n# Models with numeric explanatory variables\n\n## Mercury and Assets\n\nAre mercury concentrations in hair related to household socioeconomic position, as measured by assets?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(readr)\nmercury <- readr::read_csv(\"../data/mercury_reg.csv\")\nmercury <-\n  mercury %>%\n  # scale() subtracts the mean and divides by the SD to make the units \"standard deviations\" like a z-score\n  mutate(assets_sc=scale(SESassets)) %>%\n  #another variable we may use later\n  mutate(form_min_sc=scale(FM_buffer)) %>%\n  #so I don't have to remember coding\n  mutate(sex,sex_cat=ifelse(sex==1,\"Male\",\"Female\")) %>%\n  mutate(native,native_cat=ifelse(native==1,\"Native\",\"Non-native\")) %>%\n  mutate(hairHg=exp(lhairHg))\n```\n:::\n\n\n\n\n## Goal: Predict mercury from assets\n\n$$\\widehat{y}_{i} = \\widehat{\\beta}_0 + \\widehat{\\beta}_1 \\times x_{i}$$\nHere $y_i$ represents log hair mercury for subject $i$, and $x_i$ represents standardized household assets.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w08-02-fitting-interpretation_files/figure-revealjs/hg_asset_plot-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## How did we know to transform using the log?\n\n<div style=\"font-size:0.7em;\">\n\nIn the previous notes, we saw that the distribution of Hg in hair had a strong right skew.\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# lhairHg is the natural log of mercury in hair\n# this code puts it back on the ppm scale\nggplot(data = mercury, aes(x = exp(lhairHg))) +\n  geom_histogram() +\n  labs(x = \"Mercury (ppm)\", y = NULL)\n```\n\n::: {.cell-output-display}\n![](w08-02-fitting-interpretation_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n</div>\n\n## Assumptions of the Regression Model\n\nThe linear model actually does not require hair mercury itself to be approximately normal. Instead, it needs for the distribution of $y\\mid x$, the conditional distribution of hair mercury given all the predictor variables, to be aproximately normal. This is the same as saying that the errors in the model are approximately normally distributed.\n\nIt's pretty easy to use a histogram to check the distribution of $y$, but how about the distribution of $y \\mid x$?  That's not terribly complicated once you know how to fit a regression model, and we will work through an example of how to check it in the modeling process.\n\n## Are household assets related to hair mercury?\n\n- **Response:** hair mercury concentration, in ppm ($y_i$), contained in the variable `hairHg`\n- **Explanatory variable:** a household assets score ($x_i$), contained in the variable `assets_sc`\n  - A value of **0** on `assets_sc` means average assets in the dataset.\n  - A value of **1** means one standard deviation above that average.\n\nWhat pattern do you expect to see?\n\n\n## Look at the data first\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n<div style=\"font-size:0.6em;\">\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(mercury, aes(x = assets_sc, y = hairHg)) +\n  geom_point(alpha = 0.15, color = \"#285B78\") +\n  geom_smooth(method = \"lm\", se = FALSE, \n              color = \"#8E2C90\") +\n  labs(\n    title = \"Hair mercury and household assets\",\n    x = \"Household assets (standardized)\",\n    y = \"Hair mercury (ppm)\"\n  ) \n```\n:::\n\n\n</div>\n\n:::\n\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w08-02-fitting-interpretation_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n:::\n\n::::\n\n\n::: {.question}\nDoes the line slope upward or downward? What does that tell us about the association?\n:::\n\n\n## Goal: Predict mercury from assets\n\nThe model itself is given by $$y_i=\\beta_0+\\beta_1x_i+\\varepsilon_i,$$ where $\\varepsilon_i$ represents a Gaussian error term, which implies that $y_i$ itself (hair Hg) follows a Gaussian distribution conditional on the predictor $x_i$ (assets).\n\nThe typical hypothesis of interest is $$H_0:  \\beta=0,$$ which corresponds to no (linear) relationship between the predictor $x$ and response $y$, against the alternative $$H_0: \\beta \\neq 0.$$\n\n## $t$-test from a linear model\n\n<div style=\"font-size:0.6em;\">\n\n\nFor the linear model\n\n$$\ny_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i,\n$$\n\na $t$-test evaluates whether $X$ is associated with $Y$:\n\n$$\nH_0: \\beta_1 = 0\n\\qquad \\text{versus} \\qquad\nH_A: \\beta_1 \\ne 0.\n$$\n\nThe test statistic compares the estimated coefficient with its uncertainty:\n\n$$\nt = \\frac{\\widehat{\\beta}_1-0}{\\operatorname{SE}(\\widehat{\\beta}_1)}.\n$$\n\nUnder $H_0$,\n\n$$\nT \\sim t_{n-p},\n$$\nwhere $p$ is the number of parameters in the mean specification of the model (here, $p=2$ as we have $\\beta_0$ and $\\beta_1$ in the mean; $n$ is the number of observations used to fit the model).\n\nA large $|t|$—and correspondingly small $p$-value—provides evidence that $X$ is associated with $Y$.\n\n</div>\n\n\n## {background-color=\"white\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](../img/tidymodels.png){fig-align='center' width=98%}\n:::\n:::\n\n\n## Step 1: Specify model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Linear Regression Model Specification (regression)\n#> \n#> Computational engine: lm\n```\n\n\n:::\n:::\n\n\n## Step 2: Set model fitting *engine*\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") # lm: linear model\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Linear Regression Model Specification (regression)\n#> \n#> Computational engine: lm\n```\n\n\n:::\n:::\n\n\n## Step 3: Fit model & estimate parameters\n\n... using **formula syntax**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(hairHg ~ assets_sc, data = mercury)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> parsnip model object\n#> \n#> \n#> Call:\n#> stats::lm(formula = hairHg ~ assets_sc, data = data)\n#> \n#> Coefficients:\n#> (Intercept)    assets_sc  \n#>      2.3001      -0.8905\n```\n\n\n:::\n:::\n\n\n## A closer look at model output\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n#> parsnip model object\n#> \n#> \n#> Call:\n#> stats::lm(formula = hairHg ~ assets_sc, data = data)\n#> \n#> Coefficients:\n#> (Intercept)    assets_sc  \n#>      2.3001      -0.8905\n```\n\n\n:::\n:::\n\n\n::: {.large}\n$$\\widehat{y}_{i} = 2.30 - 0.89 \\times x_{i}$$\n\n$$\n\\widehat{\\text{hairHg}}_i\n  = 2.30 - 0.89\\,\\text{assets\\_sc}_i\n$$\n:::\n\n## The hat!\n\nThe $\\widehat{y}$ is read \"y-hat\" and indicates that we are dealing with a model-predicted value rather than the actual observation in the data. Whenever we have a predicted or estimated value, such as $\\widehat{\\text{hairHg}}_i$ or $\\widehat{\\beta}_1$, it will wear a hat to remind us that it is an estimate and not an observed value.\n\n\n## A tidy look at model output\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(hairHg ~ assets_sc, data = mercury) %>%\n  tidy(conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 7\n#>   term  estimate std.error statistic   p.value conf.low conf.high\n#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n#> 1 (Int…    2.30     0.0577      39.8 2.71e-264     2.19     2.41 \n#> 2 asse…   -0.891    0.0585     -15.2 6.68e- 50    -1.01    -0.776\n```\n\n\n:::\n:::\n\n\n<div style=\"font-size:0.7em;\">\n\n\nThe key quantity here is the slope for assets, which represents the relationship between household assets and hair mercury. The estimate and standard error provided in the output are used to evaluate the hypothesis $H_0: \\beta_1=0$, which states that there is no (linear) relationship between assets and mercury. The p-value for this hypothesis test is given by the p.value column for the asset row; the statistic column is calculated by dividing the estimate column entries by their standard errors. We have to do more digging to get the right degrees of freedom for the test, though.\n\n\n</div>\n\n## A tidy look at model output\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(hairHg ~ assets_sc, data = mercury) %>%\n  tidy(conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 7\n#>   term  estimate std.error statistic   p.value conf.low conf.high\n#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n#> 1 (Int…    2.30     0.0577      39.8 2.71e-264     2.19     2.41 \n#> 2 asse…   -0.891    0.0585     -15.2 6.68e- 50    -1.01    -0.776\n```\n\n\n:::\n:::\n\n\n<div style=\"font-size:0.7em;\">\n\n\nWe can also look at the 95% confidence interval for $\\beta_1$, which is given here by $(-1.01,-0.78)$ -- because it does not contain the null value 0, we can say there is evidence of a relationship between assets and hair mercury.\n\n\n</div>\n\n## A closer look at model output\n\n<div style=\"font-size:0.7em;\">\n\n\nThe tidy output sweeps a few quantities  under the rug, but we can tease them out using the glance function from `broom` instead.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"1\"}\nHgfit <- linear_reg() %>% #naming my model! remember for later!\n  set_engine(\"lm\") %>%\n  fit(hairHg ~ assets_sc, data = mercury)\nHgfit %>% tidy(conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 7\n#>   term  estimate std.error statistic   p.value conf.low conf.high\n#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n#> 1 (Int…    2.30     0.0577      39.8 2.71e-264     2.19     2.41 \n#> 2 asse…   -0.891    0.0585     -15.2 6.68e- 50    -1.01    -0.776\n```\n\n\n:::\n\n```{.r .cell-code  code-line-numbers=\"1\"}\nHgfit %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 12\n#>   r.squared adj.r.squared sigma statistic  p.value    df logLik\n#>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl>\n#> 1    0.0916        0.0912  2.77      232. 6.68e-50     1 -5605.\n#>      AIC    BIC deviance df.residual  nobs\n#>    <dbl>  <dbl>    <dbl>       <int> <int>\n#> 1 11217. 11234.   17623.        2298  2300\n```\n\n\n:::\n:::\n\n\nHere we see the $df=n-p$ for the t-test in the df.residual column. nobs contains the number of observations used in model fitting. So $n-p=2300-2=2298$.\n\n</div>\n\n## A closer look at model output\n\n<div style=\"font-size:0.7em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nHgfit %>% tidy(conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 7\n#>   term  estimate std.error statistic   p.value conf.low conf.high\n#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n#> 1 (Int…    2.30     0.0577      39.8 2.71e-264     2.19     2.41 \n#> 2 asse…   -0.891    0.0585     -15.2 6.68e- 50    -1.01    -0.776\n```\n\n\n:::\n\n```{.r .cell-code}\nHgfit %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 12\n#>   r.squared adj.r.squared sigma statistic  p.value    df logLik\n#>       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl>\n#> 1    0.0916        0.0912  2.77      232. 6.68e-50     1 -5605.\n#>      AIC    BIC deviance df.residual  nobs\n#>    <dbl>  <dbl>    <dbl>       <int> <int>\n#> 1 11217. 11234.   17623.        2298  2300\n```\n\n\n:::\n:::\n\n\n\nNote a different statistic is presented here -- it is the square of the statistic from tidy (there was some rounding). If you take a regression course, you will learn this statistic, the square of the t-statistic, follows an $F$ distribution, which is widely used in linear models. \n\n</div>\n\n## What does the slope mean?\n\n$$\n\\widehat{\\text{hairHg}}_i\n  = 2.30 - 0.89\\,\\text{assets\\_sc}_i\n$$\n\nHere `hairHg` is in **ppm**, so predicted values and differences in predicted values are also in **ppm**. \n\n::: {.incremental}\n- Consider two asset scores that differ by **one standard deviation**.\n- The person with the higher asset score has a predicted hair mercury concentration **0.89 ppm lower**, on average.\n- This is an association. The fitted line alone cannot tell us whether assets cause the difference.\n:::\n\n## What does the intercept mean?\n\n$$\n\\widehat{\\text{hairHg}}_i\n  = 2.30 - 0.89\\,\\text{assets\\_sc}_i\n$$\n\n::: {.incremental}\n- `assets_sc = 0` means **average household assets**.\n- At that asset score, the predicted hair mercury concentration is **2.30 ppm**.\n- At `assets_sc = 1`, the predicted concentration is $2.30 - 0.89 = 1.41$ ppm.\n:::\n\n::: {.question}\nWhat would the line predict at `assets_sc = -1`?\n:::\n\n\n## What does the model output add?\n\n<div style=\"font-size:0.8em;\">\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nHgfit %>% tidy(conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 2 × 7\n#>   term  estimate std.error statistic   p.value conf.low conf.high\n#>   <chr>    <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n#> 1 (Int…    2.30     0.0577      39.8 2.71e-264     2.19     2.41 \n#> 2 asse…   -0.891    0.0585     -15.2 6.68e- 50    -1.01    -0.776\n```\n\n\n:::\n:::\n\n\nFor the asset slope, look for:\n\n- **estimate:** the fitted change in ppm for a one-standard-deviation increase in assets;\n- **conf.low / conf.high:** endpoints of a 95% confidence interval for that slope;\n- **p.value:** a test of $H_0:\\beta_1 = 0$ against $H_A:\\beta_1 \\ne 0$.\n\n**Before relying on the usual confidence interval and test, check the model's assumptions.**\n\n</div>\n\n\n## Can we trust the model? Check the residuals!\n\n<div style=\"font-size:0.8em;\">\n\nWe saved the model as the object `Hgfit` on a prior slide.  Tidymodels is going to make it very easy for me to `join` information from the fitted models, including the predicted mercury levels (`.fitted`) and the residuals (`.resid`), to my original data, using the `append()` function. Then, to look at how well the model does, I create a plot with the predicted mercury levels on the x-axis and the residuals on the y-axis, and I hope to see a lot of random scatter centered around the value 0.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(Hgfit$fit) %>%\n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.18, color = \"#285B78\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray40\") +\n  labs(\n    x = \"Predicted hair mercury (ppm)\",\n    y = \"Residual (ppm)\",\n    title = \"Residuals from the model in ppm\"\n  ) \n```\n:::\n\n\n</div>\n\n## {background-color=\"white\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w08-02-fitting-interpretation_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n::: {.question}\nIs the vertical spread of the residuals about the same across fitted values?\n:::\n\n## Are the residuals approximately normal?\n\n<div style=\"font-size:0.8em;\">\n\nWe can also check a Q-Q (quantile-quantile) plot, which compares the model’s residuals with values expected from a normal distribution, by plotting the quantiles of the residuals in our sample against the quantiles of a normal distribution. Points roughly following the line suggest approximate normality; clear curves or departures at the ends suggest the residuals are not normally distributed. What do you think here?\n\n</div>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n<div style=\"font-size:0.7em;\">\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(Hgfit$fit) %>%\n  # sample denotes the \"sample quantiles\"\n  ggplot(aes(sample = .resid)) +\n  stat_qq(color = \"#285B78\",\n          alpha = 0.4) +\n  stat_qq_line(color = \"#8E2C90\") +\n  labs(\n    x = \"Theoretical normal quantiles\",\n    y = \"Residuals (ppm)\"\n  )\n```\n:::\n\n\n</div>\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w08-02-fitting-interpretation_files/figure-revealjs/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n\n\n## Tradeoffs: easy interpretation, bad model\n\n- On the **ppm scale**, the slope and intercept are easy to explain\n- Mercury has a strong right tail, and the spread of residuals changes across fitted values\n- That makes the usual confidence interval and $t$ test for this raw-scale model not trustworthy\n- A different scale for the response may give a more suitable model\n\n## A look ahead: a transformed response\n\nLet's compare the residuals from a model with a log (ln) transformation. The log transformation is often useful when we have right-skewed data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlHgfit <- linear_reg() %>% \n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc, data = mercury)\naugment(lHgfit$fit) %>%\n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = 0.18, color = \"#8E2C90\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"gray40\") +\n  labs(\n    x = \"Predicted log(hair mercury)\",\n    y = \"Residual on the log scale\",\n    title = \"Residuals after fitting log(hair mercury)\"\n  ) \n```\n:::\n\n\n\n## {background-color=\"white\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w08-02-fitting-interpretation_files/figure-revealjs/unnamed-chunk-19-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n::: {.question}\nHow does the spread compare with the previous residual plot?\n:::\n\n## Checking the new Q-Q plot\n\nDoes the Q-Q plot look better after the log transformation?\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n<div style=\"font-size:0.7em;\">\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(lHgfit$fit) %>%\n  # sample denotes the \"sample quantiles\"\n  ggplot(aes(sample = .resid)) +\n  stat_qq(color = \"#285B78\",\n          alpha = 0.4) +\n  stat_qq_line(color = \"#8E2C90\") +\n  labs(\n    x = \"Theoretical normal quantiles\",\n    y = \"Residuals (ppm)\"\n  )\n```\n:::\n\n\n</div>\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w08-02-fitting-interpretation_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n::::\n\n\n## Takeaways\n\n1. A slope describes the change in a **predicted response** for a one-unit increase in the explanatory variable.\n2. An intercept is the prediction when the explanatory variable equals **zero**; here, zero means *average assets*.\n3. Model checking tells us whether the simple line is adequate for inference.\n\n**Next:** how a log transformation changes interpretation\n\n\n\n## Homework (Practice)\n\n[**IMS Chapter 7**](https://openintrostat.github.io/ims/model-slr.html#sec-chp7-exercises)\n\n- Problem 3\n- Problem 4\n- Problem 17\n\n\n\n",
    "supporting": [
      "w08-02-fitting-interpretation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/font-awesome/css/all.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/font-awesome/css/v4-shims.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/panelset/panelset.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/panelset/panelset.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}