{
  "hash": "d02704d8eba7dbc59c7443d86a92ebe6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Regression and Interaction\"\nsubtitle: \"Introduction to Global Health Data Science\"\ndate: \"2026-10-26\"\nformat:\n  revealjs:\n    output-file: w09-01-multreg-interact-slides.html\n    footer: \"[🔗 sta198-fa26-2.github.io](https://sta198-fa26-2.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    pdf-separate-fragments: true\n    toc: false\n  html:\n    code-link: true\nfilters: \n  - ../remove-fmt-skip.lua\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(ggtext)\nlibrary(knitr)\nlibrary(kableExtra)\noptions(dplyr.print_min = 10, dplyr.print_max = 6)\nmercury <- readr::read_csv(\"../data/mercury_reg.csv\")\nmercury <-\n  mercury %>%\n  # scale() subtracts the mean and divides by the SD to make the units \"standard deviations\" like a z-score\n  mutate(assets_sc=scale(SESassets)) %>%\n    #another variable we may use later\n  mutate(form_min_sc=scale(FM_buffer)) %>%\n  #so I don't have to remember coding\n  mutate(sex,sex_cat=ifelse(sex==1,\"Male\",\"Female\")) %>%\n  mutate(native,native_cat=ifelse(native==1,\"Native\",\"Non-native\")) \n# limit to one observation per household (household ID=1)\nmercury1 <-\n  mercury %>%\n  filter(withinid==1)\n```\n:::\n\n\n\n# The linear model with multiple predictors\n\n## Multiple explanatory variables\n\n<div style=\"font-size:0.8em;\">\n\n\nWe previously explored how the relationship between assets and mercury in hair depended on whether a person lives in a native community.\n\n\n</div>\n\n::: {.panel-tabset}\n\n## Plot\n\n:::: {.columns}\n\n::: {.column width=\"20%\"}\n\n<div style=\"font-size:0.7em;\">\n\n::: {.question}\nHow, if at all, does the relationship between hair mercury and household assets of individuals vary by whether or not they live in a town classified as native?\n:::\n\n</div>\n\n\n:::\n\n::: {.column width=\"80%\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-multreg-interact_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n::: {.fragment}\n\n<div style=\"font-size:0.6em;\">\n\nThis is an example of an interaction effect -- the relationship between assets and mercury depends on the value of a third variable, community type. \n\n</div>\n\n:::\n\n:::\n\n::::\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = mercury, aes(x = assets_sc, y = lhairHg, color = native_cat)) +\n  geom_point(alpha = 0.1) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(\n    title = \"Hair mercury as a function of assets, by village type\",\n    subtitle = \"Peruvian Amazon\",\n    x = \"Household assets (standardized)\",\n    y = \"Hair mercury (log ppm)\",\n    color = NULL\n  ) +\n  scale_color_manual(values = c(\"#E48957\", \"#071381\"))\n```\n:::\n\n\n:::\n\n\n## Multiple explanatory variables\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-multreg-interact_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=70%}\n:::\n:::\n\n\n<div style=\"font-size:0.6em;\">\n\n\nThis figure corresponds to the model\n\n$$y_i=\\beta_0+\\beta_1 x_i + \\beta_2 z_i + \\beta_3 x_iz_i + \\varepsilon_i,$$\n\nwhere $y_i$ represents log hair mercury for subject $i$, $x_i$ represents standardized assets, $z_i=1$ if an individual lives in a non-native community and $z_i=0$ otherwise, and $x_iz_i$ is the interaction between assets and community status.\n\n\nA natural question is whether the slopes of these lines are significantly different -- do we have evidence of different relationships between assets and hair mercury for those living in native and non-native communities? \n\n</div>\n\n## {background-color=\"white\"}\n\n$$y_i=\\beta_0+\\beta_1 x_i + \\beta_2 z_i + \\beta_3 x_iz_i + \\varepsilon_i$$\n\n- $y_i$ log hair mercury for subject $i$\n- $x_i$ represents standardized assets \n- $z_i=1$ for non-native community and $z_i=0$ otherwise\n\nFitting this model, we get $$\\widehat{y}_i=\\widehat{\\beta}_0+\\widehat{\\beta}_1 x_i + \\widehat{\\beta}_2 z_i + \\widehat{\\beta}_3 x_iz_i$$ so the equations of the two lines in the figure are\n\nNative:  $\\widehat{y}_i=\\widehat{\\beta}_0+\\widehat{\\beta}_1 x_i$\n\nNon-Native: $\\widehat{y}_i=(\\widehat{\\beta}_0+\\widehat{\\beta}_2) + (\\widehat{\\beta}_1 + \\widehat{\\beta}_3) x_i$\n\n## {background-color=\"white\"}\n\n<div style=\"font-size:0.6em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc + native_cat + assets_sc*native_cat,\n      data = mercury) %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                      estimate std.error statistic  p.value\n  <chr>                        <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                  0.845    0.0575     14.7  9.93e-47\n2 assets_sc                   -0.295    0.0430     -6.85 9.33e-12\n3 native_catNon-native        -0.807    0.0626    -12.9  9.10e-37\n4 assets_sc:native_catNon-…    0.217    0.0519      4.18 2.99e- 5\n```\n\n\n:::\n:::\n\n\nNative:  $\\widehat{y}_i=0.845 -0.295x_i$\n\nNon-Native: $\\widehat{y}_i=(0.845-0.807) + (-0.295+0.217) x_i=0.038-0.078x_i$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w09-01-multreg-interact_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=40%}\n:::\n:::\n\n\nYou can see that at the mean asset level ($x_i=0$), those in non-native communities have lower hair Hg levels, and in native communities we see a stronger relationship between assets and hair Hg, with little change in hair Hg as a function of assets in non-native communities, but a decrease with increasing assets in native communities.\n\n</div>\n\n## Comparing model fit\n\n<div style=\"font-size:0.55em;\">\n\nLet's fit the assets-only model and compare it to the fit of this model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit1 <- \n  linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc,\n      data = mercury)\n\nfit2 <- \n  linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc + native_cat + assets_sc*native_cat,\n      data = mercury) \n\nfit1 %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl>\n1     0.106         0.106  1.02      274. 3.90e-58     1 -3316.\n    AIC   BIC deviance df.residual  nobs\n  <dbl> <dbl>    <dbl>       <int> <int>\n1 6638. 6655.    2407.        2298  2300\n```\n\n\n:::\n\n```{.r .cell-code}\nfit2 %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df logLik\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>  <dbl>\n1     0.208         0.207 0.964      201. 1.28e-115     3 -3177.\n    AIC   BIC deviance df.residual  nobs\n  <dbl> <dbl>    <dbl>       <int> <int>\n1 6365. 6394.    2134.        2296  2300\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nWe see the **adjusted** $R^2$ has increased from 0.11 in the assets-only model to 0.21 in the model that contains community status and the interaction. Adjusted $R^2$ is preferred to the standard $R^2$ in a model with more than one predictor; $R^2$ can never decrease when more variables are added, so it can be suboptimal at identifying predictors that are not helpful; adjusted $R^2$ adds a penalty for having \"too many\" variables in a model.\n\n</div>\n\n## Evaluating the interaction term\n\nWe can also conduct a formal hypothesis test of whether the interaction term improves our model $y_i=\\beta_0+\\beta_1 x_i + \\beta_2 z_i + \\beta_3 x_iz_i + \\varepsilon_i$ by evaluating $H_0: \\beta_3=0$ against the alternative $H_0: \\beta_3 \\neq 0$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit2 %>% tidy(confint=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                      estimate std.error statistic  p.value\n  <chr>                        <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                  0.845    0.0575     14.7  9.93e-47\n2 assets_sc                   -0.295    0.0430     -6.85 9.33e-12\n3 native_catNon-native        -0.807    0.0626    -12.9  9.10e-37\n4 assets_sc:native_catNon-…    0.217    0.0519      4.18 2.99e- 5\n```\n\n\n:::\n:::\n\n\nIf we look at the last line of output, corresponding to the interaction term, we see that the p-value is quite small, which leads us to reject the null hypothesis and conclude that the interaction term does add to the model fit.\n\n## Sex\n\nAnother variable that may help explain variability in hair Hg levels is sex. Let's add it to see if that helps ($male_i=1$ if male and 0 if not). Our model now is $y_i=\\beta_0+\\beta_1 x_i + \\beta_2 z_i + \\beta_3 x_iz_i + \\beta_4 \\text{male}_i + \\varepsilon_i$. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit3 <- \n  linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ assets_sc + native_cat + assets_sc*native_cat + sex_cat,\n      data = mercury) \nfit3 %>% tidy(confint=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  term                      estimate std.error statistic  p.value\n  <chr>                        <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                0.847      0.0602    14.1   3.61e-43\n2 assets_sc                 -0.295      0.0430    -6.85  9.66e-12\n3 native_catNon-native      -0.807      0.0627   -12.9   1.08e-36\n4 sex_catMale               -0.00460    0.0420    -0.109 9.13e- 1\n5 assets_sc:native_catNon-…  0.217      0.0519     4.18  3.04e- 5\n```\n\n\n:::\n\n```{.r .cell-code}\nfit3 %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df logLik\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>  <dbl>\n1     0.208         0.206 0.964      151. 1.95e-114     4 -3177.\n    AIC   BIC deviance df.residual  nobs\n  <dbl> <dbl>    <dbl>       <int> <int>\n1 6367. 6401.    2134.        2295  2300\n```\n\n\n:::\n:::\n\n\n\n## next\n\nwork through the model with and without interaction and the hypothesis test. first check the $R^2$ from assets-only model and compare to this one using glance. then do interaction test to see if we need that.\n\n\n## Multiple explanatory variables\n\n\nCode to fit this model is given below.\n\n\n## todo\n\nAmy this is from the multiple regression part of the first diagnostics lecture in 2022\n\nI fixed up the simple regression notes with more details, so now I can build from here.\n\nYou need the interaction. we can evaluate that, and interpret the different lines. Then add a predictor for which we don't need an interaction -- I have a more advanced model and can point out male isn't important, can do a test of that, can note the $R^2$ improved maybe due to age (mercury doesn't leave right?), talk about 1-year vs 10-year increase in age and rescale age?  Give interpretation conditional on other stuff in model held fixed.\n\n## {background-color=\"white\"}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit <- linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(lhairHg ~ native_cat+age+assets_sc+sex_cat+native_cat*assets_sc,\n      data = mercury) \nfit %>%\n  tidy(exponentiate=TRUE,conf.int=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  term   estimate std.error statistic  p.value conf.low conf.high\n  <chr>     <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Inte…    1.84    0.0673     9.08   2.25e-19    1.61      2.10 \n2 nativ…    0.450   0.0619   -12.9    8.48e-37    0.399     0.508\n3 age       1.01    0.00123    7.50   9.10e-14    1.01      1.01 \n4 asset…    0.747   0.0426    -6.86   9.14e-12    0.687     0.812\n5 sex_c…    1.00    0.0415     0.0563 9.55e- 1    0.924     1.09 \n6 nativ…    1.22    0.0513     3.91   9.42e- 5    1.11      1.35 \n```\n\n\n:::\n\n```{.r .cell-code}\nfit %>% glance() %>% print(width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df logLik\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>  <dbl>\n1     0.227         0.225 0.952      135. 2.54e-125     5 -3144.\n    AIC   BIC deviance df.residual  nobs\n  <dbl> <dbl>    <dbl>       <int> <int>\n1 6302. 6342.    2078.        2291  2297\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "w09-01-multreg-interact_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/font-awesome/css/all.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/font-awesome/css/v4-shims.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/panelset/panelset.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/panelset/panelset.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}