{
  "hash": "82cfeaaf7540ae7e1454d3dfc5b750a9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Categorical Data and Contingency Tables\"\nsubtitle: \"Introduction to Global Health Data Science\"\nauthor: \"Prof. Amy Herring\"\nformat:\n  revealjs:\n    output-file: w12-l01-contingency-tables-slides.html\n    footer: \"[🔗 sta198-fa26-2.github.io](https://sta198-fa26-2.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    pdf-separate-fragments: true\n    toc: false\n  html:\n    code-link: true\neditor_options:\n  chunk_output_type: console\n---\n\n<!-- Save this file beside the slides.scss used by your other lectures.\n     Render slides with: quarto render categorical-data.qmd --to revealjs\n     Render notes with: quarto render categorical-data.qmd --to html\n     The common plotting setup is included inline.\n-->\n\n# Introduction to contingency tables\n\n\n\n## Recall our termite-raiding ant data\n\nRecall our termite-raiding ant data:\n\n<div style=\"height: 40px;\"></div>\n\n| | **Carried Back** | **Carried Away** | **Not Carried** |\n|:--|:--:|:--:|:--:|\n| **Lightly Injured** | 45 | 0 | 5 |\n| **Heavily Injured** | 5 | 5 | 20 |\n\n<div style=\"overflow:hidden; height:250px; margin-top:20px;\">\n  <img src=\"../img/mantabele.jpg\" alt=\"Termite-raiding ants\"\n       style=\"width:100%; height:auto; transform:translateY(-80px);\">\n</div>\n\n\n\n\n\n## Contingency tables\n\nA *contingency table* displays the relationship between two categorical variables.\n\nHere, each observation is an ant. The variables are **injury severity** and **carrying outcome**.\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n## Dataset: one row per ant (subset of 15 rows)\n\n\n\n<div style=\"font-size:0.6em;\">\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Injury          |Outcome      |\n|:---------------|:------------|\n|Lightly injured |Carried back |\n|Lightly injured |Carried back |\n|Lightly injured |Carried back |\n|Lightly injured |Carried back |\n|Lightly injured |Carried back |\n|Lightly injured |Carried back |\n|Lightly injured |Carried back |\n|Heavily injured |Not carried  |\n|Lightly injured |Carried back |\n|Heavily injured |Carried away |\n|Heavily injured |Not carried  |\n|Heavily injured |Not carried  |\n|Heavily injured |Not carried  |\n|Lightly injured |Carried back |\n|Lightly injured |Carried back |\n\n\n:::\n:::\n\n\n</div>\n\n## Visualizing injury severity and carrying outcome\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables_files/figure-revealjs/viz-ants-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nants %>%\n  ggplot(aes(y = Injury, fill = Outcome)) +\n  geom_bar(position = position_fill(reverse = TRUE)) +\n  #reverse equals true puts carried back on the left\n  scale_y_discrete(limits = c(\"Heavily injured\", \"Lightly injured\")) + #this line puts light injury as the top row to match our contingency table formatting\n  labs(x = \"Proportion\", y = \"Injury severity\",\n       title = \"Carrying outcome by injury severity\") +\n  scale_fill_manual(values = c(\n    \"Carried back\" = \"#7FBB9E\",  # Neptune Green\n    \"Carried away\" = \"#60373D\",  # Red Mahogany\n    \"Not carried\" = \"#133955\"   # Poseidon\n  ))\n```\n:::\n\n\n:::\n\n## Are injury severity and carrying outcome related?\n\nIf there were no association, we would expect approximately the same proportions of the three outcomes in both injury groups.\n\nAre the differences in this sample evidence of an association, or could they reflect random variation?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables_files/figure-revealjs/viz-ants-repeat-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n\n\n## Typical questions with $r\\times c$ contingency tables\n\n- Is there an association between the row variable and the column variable?\n  - Here, $r=2$ injury groups and $c=3$ carrying outcomes.\n- How strong is the association?\n\n$H_0:$ injury severity and carrying outcome are independent.\n\n$H_A:$ injury severity and carrying outcome are associated.\n\n# Tests for association\n\n\n\n# Fisher's exact test\n\n\n\n## Fisher's exact test\n\nFisher's exact test assesses whether two categorical variables are associated.\n\nIt does not require large expected cell counts, so it is useful when a contingency table includes small counts, as is the case here.\n\nThe test can be computationally expensive for large tables.\n\n## How Fisher's exact test works\n\n<div style=\"font-size:0.8em;\">\n\nWe condition on the observed **margins**, the row and column totals:\n\n- 50 lightly injured ants and 30 heavily injured ants;\n- 50 carried back, 5 carried away, and 25 not carried.\n\nConsider all possible tables with those same margins. Under $H_0$, each table has a probability.\n\nThe two-sided p-value sums the probabilities of tables whose null probabilities are less than or equal to that of our observed table.\n\n</div>\n\n::: {.notes}\nR documentation for the fixed-margins test and probability ordering:\nhttps://stat.ethz.ch/R-manual/R-devel/library/stats/html/fisher.test.html\n:::\n\n## Tables with the same margins\n\n<div style=\"font-size:0.65em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Observed table**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | <span style=\"color: blue;\">50</span> |\n| Heavily injured | 5 | 5 | 20 | <span style=\"color: blue;\">30</span> |\n| Total | <span style=\"color: blue;\">50</span> | <span style=\"color: blue;\">5</span> | <span style=\"color: blue;\">25</span> | <span style=\"color: blue;\">80</span> |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**A <span style=\"color: red;\">more extreme</span> table with the same margins**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | <span style=\"color: red;\">50</span> | 0 | <span style=\"color: red;\">0</span> | <span style=\"color: blue;\">50</span> |\n| Heavily injured | <span style=\"color: red;\">0</span> | 5 | <span style=\"color: red;\">25</span> | <span style=\"color: blue;\">30</span> |\n| Total | <span style=\"color: blue;\">50</span> | <span style=\"color: blue;\">5</span> | <span style=\"color: blue;\">25</span> | <span style=\"color: blue;\">80</span> |\n\n:::\n\n::::\n\n</div>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Fisher's exact test for the ant data\n\n<div style=\"font-size:0.8em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nant_tab #view the table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                  \n#>                   Carried back Carried away Not carried\n#>   Lightly injured           45            0           5\n#>   Heavily injured            5            5          20\n```\n\n\n:::\n\n```{.r .cell-code}\nant_fisher <- fisher.test(ant_tab)\nant_fisher\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tFisher's Exact Test for Count Data\n#> \n#> data:  ant_tab\n#> p-value = 2.576e-11\n#> alternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nThe p-value is approximately $2.58\\times10^{-11}$.\n\nThere is strong evidence of an association between injury severity and carrying outcome.\n\n</div>\n\n# $\\chi^2$ (chi-squared) test\n\n\n\n## $\\chi^2$ test\n\nThe chi-squared test compares **observed** cell counts with the counts **expected** if $H_0$ were true.\n\nIts p-value uses an approximation that depends on the expected counts. For this course, use the guideline that every expected cell count should be at least 5.\n\nWe will calculate the expected counts and test statistic for the ant table, then check that guideline.\n\n## Marginal probabilities\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"48%\" style=\"background-color: #eaf4ef; padding: 0.6em; border-radius: 10px; box-sizing: border-box;\"}\n\n\nInjury severity: \n\n- $P(\\text{lightly injured})=50/80$ \n\n- $P(\\text{heavily injured})=30/80$\n\n:::\n\n::: {.column width=\"48%\" style=\"background-color: #f5ebee; padding: 0.6em; border-radius: 10px; box-sizing: border-box;\"}\n\n\nCarrying outcome: \n\n- $P(\\text{back})=50/80$\n\n- $P(\\text{away})=5/80$\n\n- $P(\\text{not carried})=25/80$.\n\n:::\n\n::::\n\n</div>\n\n## Expected counts under independence\n\nSuppose $H_0$ is true: injury severity and carrying outcome are independent.\n\nWhat is the probability that an ant is **lightly injured and carried back**? Recall that under independence, $P(A \\cap B)=P(A)P(B)$.\n\n<div style=\"font-size:0.65em;\">\n\n\n::: {.fragment}\n$$\nP(\\text{lightly injured and carried back})\n=P(\\text{lightly injured})P(\\text{carried back})\n=\\frac{50}{80}\\times\\frac{50}{80}.\n$$\n:::\n\n</div>\n\n## From probabilities to expected counts\n\nMultiply the probability by the number of ants:\n\n$$\nE_{\\text{light, back}}\n=\\frac{50}{80}\\times\\frac{50}{80}\\times80\n=31.25.\n$$\n\nIn general, for any cell:\n\n$$\nE=\\frac{\\text{row total}\\times\\text{column total}}{\\text{grand total}}.\n$$\n\n## Building the expected table\n\n$E_{\\text{light, back}}=\\frac{50\\times50}{80}=31.25$\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | <span style=\"color: red;\">31.25</span> |  |  | 50 |\n| Heavily injured |  |  |  | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n\n\n## Building the expected table\n\n$E_{\\text{light, away}}=\\frac{50\\times5}{80}=3.125$\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.25 | <span style=\"color: red;\">3.125</span> |  | 50 |\n| Heavily injured |  |  |  | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n\n\n## Building the expected table\n\n$E_{\\text{light, not carried}}=50-31.25-3.125=15.625$\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | <span style=\"color: red;\">15.625</span> | 50 |\n| Heavily injured |  |  |  | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n\n\n## Building the expected table\n\n$E_{\\text{heavy, back}}=50-31.25=18.75$\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | <span style=\"color: red;\">18.75</span> |  |  | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n\n\n## Building the expected table\n\n$E_{\\text{heavy, away}}=5-3.125=1.875$\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | <span style=\"color: red;\">1.875</span> |  | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n\n## Building the expected table\n\n$E_{\\text{heavy, not carried}}=30-18.75-1.875=9.375$\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | <span style=\"color: red;\">9.375</span> | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n\n\n## The expected table under $H_0$\n\nIf injury severity and carrying outcome were independent, these would be the expected counts:\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n## Comparing observed and expected tables\n\n<div style=\"font-size:0.65em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Observed**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Expected under $H_0$**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::::\n\n</div>\n\nThe observed table differs from the expected table. How can we summarize those differences?\n\n## Comparing observed and expected tables\n\n<div style=\"font-size:0.65em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Observed**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Expected under $H_0$**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::::\n\n</div>\n\nThe $\\chi^2$ test compares observed frequencies, $O$, with expected frequencies, $E$, in each cell.\n\n## Comparing observed and expected tables\n\n<div style=\"font-size:0.65em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Observed**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Expected under $H_0$**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::::\n\n</div>\n\nLarge differences, $O-E$, provide evidence against $H_0$.\n\n## Comparing observed and expected tables\n\n<div style=\"font-size:0.65em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Observed**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Expected under $H_0$**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::::\n\n</div>\n\nWe square the differences, $(O-E)^2$, so that positive and negative differences do not cancel each other out.\n\n## Comparing observed and expected tables\n\n<div style=\"font-size:0.65em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Observed**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Expected under $H_0$**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::::\n\n</div>\n\nWe divide each squared difference by $E$ to account for the scale of the expected count: $\\frac{(O-E)^2}{E}$\n\n## The $\\chi^2$ test statistic\n\n<div style=\"font-size:0.65em;\">\n\nOur test statistic is\n\n$$\nX^2=\\sum_{i=1}^{rc}\\frac{(O_i-E_i)^2}{E_i}.\n$$\n\nHere, there are $r\\times c=2\\times3=6$ cells, excluding the totals:\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n**Observed**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 0 | 5 | 50 |\n| Heavily injured | 5 | 5 | 20 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::: {.column width=\"50%\"}\n\n**Expected under $H_0$**\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\n:::\n\n::::\n\n\n\n$$\nX^2=\\frac{(45-31.25)^2}{31.25}\n+\\frac{(0-3.125)^2}{3.125}\n+\\cdots+\\frac{(20-9.375)^2}{9.375}\n=43.73.\n$$\n</div>\n\n## Checking the expected counts\n\n| Injury | Carried back | Carried away | Not carried | Total |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 31.250 | 3.125 | 15.625 | 50 |\n| Heavily injured | 18.750 | 1.875 | 9.375 | 30 |\n| Total | 50 | 5 | 25 | 80 |\n\nThe expected counts for **carried away** are 3.125 and 1.875, both below 5.\n\nUse **Fisher's exact test** for the main conclusion. The chi-squared calculations illustrate the method, but the large-sample approximation may be unreliable here.\n\n## The $\\chi^2$ distribution\n\n- Under $H_0$, the test statistic is approximately chi-squared when expected counts are sufficiently large.\n- The degrees of freedom are $(r-1)(c-1)=(2-1)(3-1)=2$.\n- The distribution is asymmetric and takes nonnegative values.\n- Larger statistics provide more evidence against $H_0$, so the p-value is an area in the **right tail**.\n\n## Calculating the $\\chi^2$ statistic in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nobserved_chisq_statistic <- ants %>%\n  specify(Injury ~ Outcome) %>%\n  calculate(stat = \"Chisq\")\n\nobserved_chisq_statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Response: Injury (factor)\n#> Explanatory: Outcome (factor)\n#> # A tibble: 1 × 1\n#>    stat\n#>   <dbl>\n#> 1  43.7\n```\n\n\n:::\n:::\n\n\nThe statistic is approximately **43.7**.\n\n## Simulating the null distribution\n\nWe can generate a null distribution by permuting carrying outcomes among the ants, keeping the margins fixed.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(1234)\nnull_distribution_simulated <- ants %>%\n  specify(Injury ~ Outcome) %>%\n  hypothesize(null = \"independence\") %>%\n  generate(reps = 5000, type = \"permute\") %>%\n  calculate(stat = \"Chisq\")\n```\n:::\n\n\n## The theoretical null distribution\n\nThe theoretical approximation uses a $\\chi^2_2$ distribution.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nant_hypothesis <- ants %>%\n  specify(Injury ~ Outcome) %>%\n  hypothesize(null = \"independence\")\n```\n:::\n\n\nRemember that two expected counts are below 5. We will compare this approximation with the simulated null distribution.\n\n## Visualizing the simulated null distribution\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables_files/figure-revealjs/ant-viz-sim-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnull_distribution_simulated %>%\n  visualize() +\n  shade_p_value(observed_chisq_statistic, direction = \"greater\")\n```\n:::\n\n\n:::\n\n## Visualizing the theoretical null distribution\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables_files/figure-revealjs/ant-viz-theory-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nant_hypothesis %>%\n  visualize(method = \"theoretical\") +\n  shade_p_value(observed_chisq_statistic, direction = \"greater\")\n```\n:::\n\n\n:::\n\n## Comparing both null distributions\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables_files/figure-revealjs/ant-viz-both-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnull_distribution_simulated %>%\n  visualize(method = \"both\") +\n  shade_p_value(observed_chisq_statistic, direction = \"greater\")\n```\n:::\n\n\n:::\n\n## The chi-squared approximation for the ant data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# This returns an approximate p-value.\nant_chisq <- chisq.test(ant_tab, correct = FALSE)\nant_chisq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's Chi-squared test\n#> \n#> data:  ant_tab\n#> X-squared = 43.733, df = 2, p-value = 3.187e-10\n```\n\n\n:::\n:::\n\n\n$X^2=43.73$ on 2 degrees of freedom, with an approximate p-value of $3.19\\times10^{-10}$.\n\nBecause two expected counts are small, use the earlier **Fisher p-value** for inference. Both calculations suggest a strong association.\n\n::: {.notes}\nThe warning about a potentially incorrect approximation is expected for these\ndata. The global chunk settings suppress warnings on the slides, but the\nlimitation is stated explicitly in the slide text. Yates' correction applies\nonly to 2 x 2 tables, not this 2 x 3 table.\nhttps://stat.ethz.ch/R-manual/R-devel/library/stats/html/chisq.test.html\n:::\n\n## A very small p-value and simulation\n\nWith 5,000 permutations, we may see no simulated statistics as large as 43.73. That does **not** mean the true p-value is zero.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_extreme <- sum(\n  null_distribution_simulated$stat >= observed_chisq_statistic$stat\n)\np_sim <- (n_extreme + 1) / (nrow(null_distribution_simulated) + 1)\np_sim\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 0.00019996\n```\n\n\n:::\n:::\n\n\nIf none are as extreme, this adjusted estimate is $1/5001\\approx0.0002$. Fisher's exact test can resolve the much smaller p-value for this table.\n\n# How strong is the association?\n\n\n\n## The Odds Ratio\n\n<div style=\"font-size:0.8em;\">\n\n\nAn odds ratio compares two groups that have a **binary** outcome.\n\nFor the ants, compare **carried back** with **not carried back**. The latter combines carried away and not carried.\n\n| Injury | Carried back | Not carried back | Total |\n|:--|--:|--:|--:|\n| Lightly injured | 45 | 5 | 50 |\n| Heavily injured | 5 | 25 | 30 |\n| Total | 50 | 30 | 80 |\n\nThis asks whether injury severity is associated with being carried back. It uses all 80 ants, but it summarizes the original three outcomes as two.\n\nLet $B$ mean carried back and $L$ mean lightly injured. Then $\\overline{L}$ means heavily injured.\n\n</div>\n\n## What are the Odds?\n\n<div style=\"font-size:0.7em;\">\n\n\nThe **odds of an event** compare how often it happens with how often it does **not** happen:\n\n</div>\n\n<div style=\"font-size:0.5em;\">\n\n$$\n\\text{Odds of being carried back}\n=\\frac{P(B)}{1-P(B)}\n=\\frac{\\text{number carried back}}{\\text{number not carried back}}.\n$$\n\n| Injury | Carried back | Not carried back | Probability | Odds |\n|:--|--:|--:|--:|--:|\n| Lightly injured | 45 | 5 | $45/50=0.90$ | $\\frac{\\frac{45}{50}}{\\frac{5}{50}}=\\frac{45}{5}=9$ to $1$ |\n| Heavily injured | 5 | 25 | $5/30\\approx0.17$ | $\\frac{\\frac{5}{50}}{\\frac{25}{50}}=\\frac{5}{25}=1$ to $5$ |\n\n</div>\n\n<div style=\"font-size:0.7em;\">\n\nFor lightly injured ants, **9 to 1 odds** means that for every one ant *not* carried back, nine were carried back.\n\n</div>\n\n## The odds ratio (OR)\n\n\n\n$$\nOR=\\frac{P(B\\mid L)/[1-P(B\\mid L)]}\n        {P(B\\mid \\overline{L})/[1-P(B\\mid \\overline{L})]}.\n$$\n\nThe OR ranges from 0 to $\\infty$.\n\n- $OR=1$: the two groups have equal odds of being carried back.\n- $OR>1$: lightly injured ants have higher odds.\n- $OR<1$: lightly injured ants have lower odds.\n\n## Odds ratio from a contingency table\n\n<div style=\"font-size:0.65em;\">\n\n| | Group 1 | Group 2 |\n|:--|--:|--:|\n| Outcome present | $a$ | $b$ |\n| Outcome absent | $c$ | $d$ |\n\nThe estimated probabilities are\n\n$$\n\\widehat P_1=\\frac{a}{a+c},\n\\qquad\n\\widehat P_2=\\frac{b}{b+d}.\n$$\n\nFor Group 1, the probability of the outcome being absent is\n$1-\\widehat P_1=c/(a+c)$. Thus its odds are\n\n$$\n\\frac{\\widehat P_1}{1-\\widehat P_1}\n=\n\\frac{a/(a+c)}{c/(a+c)}\n=\n\\frac{a}{c}.\n$$\n\nSimilarly, the odds for Group 2 are\n$\\dfrac{b/(b+d)}{d/(b+d)}=\\dfrac{b}{d}$. Dividing the two odds gives\n\n$$\n\\widehat{OR}\n=\n\\frac{a/c}{b/d}\n=\n\\frac{ad}{bc}.\n$$\n\n</div>\n\n## Odds ratio for being carried back\n\nThe odds of being carried back are\n\n$$\n\\text{Lightly injured: }\\frac{45}{5}=9,\n\\qquad\n\\text{Heavily injured: }\\frac{5}{25}=0.2.\n$$\n\n$$\n\\widehat{OR}=\\frac{9}{0.2}=45.\n$$\n\nIn this sample, lightly injured ants have **45 times the odds** of being carried back compared with heavily injured ants.\n\nThis compares odds, rather than probabilities.\n\n## Odds ratio using the formula\n\n<div style=\"font-size:0.8em;\">\n\n\nHere, the outcome is **carried back**. “Not carried back” includes ants carried away or not carried at all.\n\n| | Lightly injured (Group 1) | Heavily injured (Group 2) |\n|:--|--:|--:|\n| Carried back | $a=45$ | $b=5$ |\n| Not carried back | $c=5$ | $d=25$ |\n\nSubstitute these counts into the formula:\n\n$$\n\\widehat{OR}\n=\\frac{ad}{bc}\n=\\frac{45(25)}{5(5)}\n=\\frac{1125}{25}\n=45.\n$$\n\nThe odds of being carried back were **45 times as high** for lightly injured ants as for heavily injured ants.\n\n</div>\n\n## Creating the binary outcome in R\n\n<div style=\"font-size:0.75em;\">\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nants_binary <- ants %>%\n  mutate(\n    Carried_back = if_else(Outcome == \"Carried back\", \"Yes\", \"No\"),\n    Carried_back = factor(Carried_back, levels = c(\"Yes\", \"No\"))\n  )\n\nant_binary_tab <- table(ants_binary$Injury, ants_binary$Carried_back)\nant_binary_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                  \n#>                   Yes No\n#>   Lightly injured  45  5\n#>   Heavily injured   5 25\n```\n\n\n:::\n:::\n\n\nRows are ordered lightly injured, heavily injured. Columns are ordered Yes, No. This makes the OR compare lightly injured with heavily injured ants.\n\n</div>\n\n## Estimating an OR and a 95% confidence interval\n\n<div style=\"font-size:0.7em;\">\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nant_or_result <- fisher.test(ant_binary_tab)\nant_or_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tFisher's Exact Test for Count Data\n#> \n#> data:  ant_binary_tab\n#> p-value = 3.476e-11\n#> alternative hypothesis: true odds ratio is not equal to 1\n#> 95 percent confidence interval:\n#>   10.29032 212.82087\n#> sample estimates:\n#> odds ratio \n#>   41.32031\n```\n\n\n:::\n:::\n\n\n\n\nThe estimated OR (conditional MLE) is **41.3**, with a 95% CI of **(10.3, 212.8)**.\n\nThe CI excludes 1, providing evidence that the odds of being carried back differ by injury severity.\n\n`fisher.test()` reports a conditional maximum likelihood estimate, which differs slightly from the sample cross-product estimate of 45.\n\n</div>\n\n\n\n# Practice: pneumococcal serotypes and survival\n\n\n\n## Practice: the serotype data\n\n<div style=\"font-size:0.8em;\">\n\n\nA Scottish study examined the association between pneumococcal serotype and survival following infection.\n\n| Serotype | Survived | Died | Total |\n|:--|--:|--:|--:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n1. Identify the two categorical variables and the dimensions of this table.\n2. State the null and alternative hypotheses for a test of association.\n\n</div>\n\n## Practice: expected counts\n\n<div style=\"font-size:0.8em;\">\n\n\n| Serotype | Survived | Died | Total |\n|:--|--:|--:|--:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n3. Calculate the expected number of deaths for serotype 31 under $H_0$.\n4. Calculate the other expected counts. Is the chi-squared approximation appropriate under our course guideline?\n5. What are the degrees of freedom?\n\n::: {.notes}\nExpected survivors and deaths, respectively:\nSerotype 10: 37.46875, 6.53125.\nSerotype 15: 61.3125, 10.6875.\nSerotype 20: 90.265625, 15.734375.\nSerotype 31: 28.953125, 5.046875.\nAll expected counts exceed 5. The degrees of freedom are 3.\n:::\n\n</div>\n\n## Practice: enter the data in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npneu_counts <- tibble(\n  Serotype = rep(c(\"Serotype 10\", \"Serotype 15\",\n                  \"Serotype 20\", \"Serotype 31\"), each = 2),\n  Survival = rep(c(\"Survived\", \"Died\"), 4),\n  n = c(37, 7, 60, 12, 97, 9, 24, 10)\n)\n\npneu <- pneu_counts %>% uncount(n)\npneu_tab <- table(pneu$Serotype, pneu$Survival)\n```\n:::\n\n\nThe dataset contains one row per person. `pneu_tab` contains the cell counts.\n\n## Practice: tests of association\n\n6. Use Fisher's exact test and the chi-squared test. Compare their conclusions and interpret the p-values in context.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Run the tests, then interpret the results.\nfisher.test(pneu_tab)\nchisq.test(pneu_tab)\n```\n:::\n\n\n::: {.notes}\nThe chi-squared statistic is approximately 9.322 on 3 degrees of freedom,\nwith p-value 0.02530. Fisher's p-value is approximately 0.02658.\nBoth provide evidence of an association at the 0.05 level.\n:::\n\n## Practice: odds ratio\n\n7. Compare serotypes **20 and 31**. Calculate the sample odds ratio for **death**, comparing serotype 20 with serotype 31.\n8. Use R to obtain an odds ratio and 95% CI. Interpret them and explain whether the CI supports an association.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npneu_20_31 <- pneu %>%\n  filter(Serotype %in% c(\"Serotype 20\", \"Serotype 31\")) %>%\n  mutate(\n    Serotype = factor(Serotype, levels = c(\"Serotype 20\", \"Serotype 31\")),\n    Survival = factor(Survival, levels = c(\"Died\", \"Survived\"))\n  )\n\n# Check the row and column order before interpreting the OR.\ntable(pneu_20_31$Serotype, pneu_20_31$Survival)\nfisher.test(table(pneu_20_31$Serotype, pneu_20_31$Survival))\n```\n:::\n\n\n::: {.notes}\nThe sample OR is $(9\\times24)/(97\\times10)=0.2227$.\nR's conditional OR is approximately 0.23, with 95% CI approximately\n(0.07, 0.69). Serotype 20 is associated with lower odds of death than\nserotype 31. The CI excludes 1. This comparison concerns odds, not risk.\n:::\n\n## Practice: another comparison\n\n9. Compare serotypes **10 and 31** using Fisher's exact test. What do you conclude?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npneu_10_31 <- pneu %>%\n  filter(Serotype %in% c(\"Serotype 10\", \"Serotype 31\"))\n\nfisher.test(table(pneu_10_31$Serotype, pneu_10_31$Survival))\n```\n:::\n\n\nIf you test several serotype pairs, consider how multiple comparisons affect the chance of a false positive.\n",
    "supporting": [
      "w12-l01-contingency-tables_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}