{
  "hash": "329cad404aa623cf305d42028afa3996",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Categorical Data - Contingency Tables\"\nsubtitle: \"Introduction to Global Health Data Science\"\nauthor: \"Prof. Amy Herring\"\nformat:\n  revealjs:\n    output-file: categorical-data-slides.html\n    footer: \"[🔗 sta198-fa26-2.github.io](https://sta198-fa26-2.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    pdf-separate-fragments: true\n    toc: false\n  html:\n    code-link: true\nfilters: \n  - ../remove-fmt-skip.lua\neditor_options: \n  chunk_output_type: console\n---\n\n<!-- Save this file beside the slides.scss used by your other lectures.\n     Render slides with: quarto render categorical-data.qmd --to revealjs\n     Render notes with: quarto render categorical-data.qmd --to html\n     The common plotting setup is included inline.\n-->\n\n\n\n# Introduction to contingency tables\n\n## Motivating example: *Streptococcus pneumoniae*\n\n<div style=\"font-size:0.8em;\">\n\nInfections due to *Streptococcus pneumoniae* remain a substantial source of morbidity and mortality in both developing and developed countries despite a century of research and the development of therapeutic interventions such as multiple classes of antibiotics and vaccination. The World Health Organization estimates that in developing countries 814,000 children under the age of five die annually from invasive pneumococcal disease (IPD), with an estimated 1.6 million deaths affecting all ages globally.\n\n\nSeveral recent studies have identified associations between pneumococcal serotypes (species variations) and patient outcomes from IPD.  We consider data from a Scottish study of pneumococcal serotypes and mortality.\n\n</div>\n\n## Contingency tables\n\nA *contingency table* is a display format for showing the relationship between two categorical variables. Below is a contingency table for a subset of serotypes from the Scottish study.\n\n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n## Dataset (Random sample of observations printed)\n\n<div style=\"font-size:0.6em;\">\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Serotype    |Survived        |\n|:-----------|:---------------|\n|Serotype 10 |Survived        |\n|Serotype 15 |Survived        |\n|Serotype 31 |Did not survive |\n|Serotype 20 |Survived        |\n|Serotype 15 |Survived        |\n|Serotype 31 |Survived        |\n|Serotype 15 |Did not survive |\n|Serotype 20 |Survived        |\n|Serotype 20 |Survived        |\n|Serotype 20 |Survived        |\n|Serotype 20 |Survived        |\n|Serotype 20 |Survived        |\n|Serotype 15 |Survived        |\n|Serotype 15 |Survived        |\n|Serotype 20 |Did not survive |\n|Serotype 15 |Survived        |\n|Serotype 15 |Survived        |\n|Serotype 15 |Survived        |\n|Serotype 20 |Survived        |\n|Serotype 15 |Did not survive |\n\n\n:::\n:::\n\n\n</div>\n\n## Visualizing Serotypes and Survival\n\n\nHere's the relationship in the sample data.\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables-old_files/figure-revealjs/vizpneu-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npneu %>%\n  ggplot(aes(y = Serotype, fill = Survived)) +\n  geom_bar(position = \"fill\") +\n  labs(x=\"Proportion\",\n       title=\"Survival by Streptococcus Serotype\") + \n  scale_fill_manual(values=c(\"#638B27\",\"#BBA2B6\"))\n```\n:::\n\n\n:::\n\n## Are serotype and survival related?\n\nIf there were no relationship between serotype and survival, we'd expect to see the lavender bars all the same length across the serotypes. Are the differences we see here reflecting actual differences in population-level survival across serotypes, or are they just a function of random variation?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables-old_files/figure-revealjs/vizpneu-repeat-3-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Typical questions of interest with $r \\times c$ contingency tables\n\n- Is there an association between the row variable (indexed by $r$) and the column variable (indexed by $c$)?\n\n  - In our case, $r=4$ (4 serotypes) and $c=2$ (survived or died). We could easily reverse rows and columns with no ill effects.\n\n- How strong is any association?\n\nHere, we would like to test $H_0:$ pneumococcal serotype is unrelated to mortality against the alternative $H_A:$  pneumococcal serotype is related to mortality\n\n# Tests for Association\n\n# Fisher's Exact Test\n\n## Fisher's Exact Test\n\nFisher's exact test is a great first choice for testing a relationship between two variables in a contingency table.  While it has been around for almost 100 years, it was originally used only for very small samples due to the computational burden involved (this concern has been largely alleviated by modern computing). This test was invented by the same person for whom the F test we studied recently was named (Fisher made many important contributions to statistics).\n\n## Fisher's Exact Test\n\n<div style=\"font-size:0.8em;\">\n\nFisher's exact test is fairly intuitive.  The way it works is that we assume the column and row totals are fixed (so for our pneumococcus example, we condition on having 38 deaths and 218 survivors and that we have 34 in serotype 31, 44 in serotype 10, 72 in serotype 15, and 106 in serotype 20).  Then, we construct all possible contingency tables with the same margins, and then sum up the probabilities of all tables with null probabilities less than or equal to that of our observed table to get the p-value (recall the p-value is the probability of the observed data, or more extreme data, occurring under the null hypothesis). \n\nMargins:  row and column totals\n\nObviously, this was no fun before modern computing.\n\n</div>\n\n## Tables with the same margins\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nOur table:\n\n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nA more extreme table with same margins:\n\n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | <span style=\"color: red;\">38</span> | <span style=\"color: red;\">6</span> | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | <span style=\"color: red;\">23</span> | <span style=\"color: red;\">11</span> | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n## A more extreme table\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nOur table:\n\n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nA more extreme table with same margins:\n\n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | <span style=\"color: red;\">44</span> | <span style=\"color: red;\">0</span> | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | <span style=\"color: red;\">17</span> | <span style=\"color: red;\">17</span> | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n## Conducting the test for Pneumococcus data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfisher.test(pneu$Serotype,pneu$Survived)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tFisher's Exact Test for Count Data\n#> \n#> data:  pneu$Serotype and pneu$Survived\n#> p-value = 0.02658\n#> alternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nHere we conclude that the rows and columns of our table are not independent. That is, we conclude that there is a relationship between serotype and survival.\n\n# $\\chi^2$ (Chi-Squared) Test\n\n## $\\chi^2$ Test\n\n<div style=\"font-size:0.8em;\">\n\nWe can also test our null hypothesis that serotype is unrelated to survival using a $\\chi^2$ test.\n\nThe chi-squared approximation depends on the **expected** cell counts under $H_0$. For this course, use the guideline that every expected cell count should be at least 5. Fisher's exact test does not require large expected counts.\n\nYates' continuity correction applies to $2\\times2$ tables. In R, `chisq.test()` uses it by default for those tables. It does not apply to our $4\\times2$ table.\n\nFor *very* large samples, Fisher's exact test can still be too computationally expensive, and the $\\chi^2$ test has nice connections to the logistic regression models we will study later in the course.\n\nIn addition, the chi-squared test has a very nice motivation in terms of comparing observed proportions in the data to the proportions we would expect if $H_0$ were true.\n\n</div>\n\n\n\n::: {.notes}\nThe source notes used observed counts greater than 10 and described Yates'\ncorrection as a response to small counts. The relevant quantities are expected\ncounts, and R applies the continuity correction by default only to 2 x 2 tables.\nSee the R documentation:\nhttps://stat.ethz.ch/R-manual/R-devel/library/stats/html/chisq.test.html\nhttps://stat.ethz.ch/R-manual/R-devel/library/stats/html/fisher.test.html\n:::\n\n## Marginal probabilities\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(pneu$Serotype, pneu$Survived) %>%\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|            | Did not survive| Survived|\n|:-----------|---------------:|--------:|\n|Serotype 10 |               7|       37|\n|Serotype 15 |              12|       60|\n|Serotype 20 |               9|       97|\n|Serotype 31 |              10|       24|\n\n\n:::\n:::\n\n\nSome summaries of *marginal* probabilities will be helpful as we consider the data.\n\nSurvived:  $\\frac{37+60+97+24}{37+60+97+24+7+12+9+10}=\\frac{218}{256}=85.2\\%$ survived \n\nPrevalence of serotypes: serotype 10:  $\\frac{44}{256}=17.2\\%$; \nserotype 15:  $\\frac{72}{256}=28.1\\%$; \nserotype 20:  $\\frac{106}{256}=41.4\\%$; \nserotype 31:  $\\frac{34}{256}=13.3\\%$\n\n## $\\chi^2$ Test \nSuppose that $H_0$ is true, and serotype of infection and survival are independent events. In that case, how would we calculate the probability that a patient had serotype 10 and survived?\n\n## Back to probability!\n\nRemember for two independent events, $P(A \\cap B)=P(A)P(B)$.\n\nAnother handy probability law in this setting is the law of total probability, e.g. $P(A)+P(A^c)=1$.\n\nWe can use these probability rules to calculate what our table would be expected to look like, given *fixed margins* (i.e., the same number of survivors and infections of each serotype as we have here), if $H_0$ is true. When $H_0$ is true, the  serotype is independent of survival.\n\n## $\\chi^2$ Test\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nLet's create the table we would expect to see if $H_0$ were true.\n\n<span style=\"color: red;\">?</span> = expected # who survived and had serotype 10 if $H_0$ true\n\n<span style=\"color: red;\">?</span> = probability of being both serotype 10 and surviving times number of study participants = P(Serotype 10) $\\times$ P(Survived) $\\times$ 256\n\n<span style=\"color: red;\">?</span> = $\\frac{44}{256}\\times\\frac{218}{256}\\times 256=37.5$\n\n:::\n\n::: {.column width=\"50%\"}\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | <span style=\"color: red;\">?</span> | | 44 |\n| Serotype 15 | | | 72 |\n| Serotype 20 | | | 106  |\n| Serotype 31 | | | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n## $\\chi^2$ Test\n\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n<span style=\"color: red;\">?</span> can be obtained by subtraction as 44-37.5\n\n:::\n\n::: {.column width=\"50%\"}\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | <span style=\"color: red;\">?</span> | 44 |\n| Serotype 15 | | | 72 |\n| Serotype 20 | | | 106  |\n| Serotype 31 | | | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n## $\\chi^2$ Test\n\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n<span style=\"color: red;\">?</span> = expected # who survived and had serotype 15 if $H_0$ true\n\n<span style=\"color: red;\">?</span> = probability of being both serotype 15 and surviving times number of study participants = P(Serotype 15) $\\times$ P(Survived) $\\times$ 256\n\n<span style=\"color: red;\">?</span> = $\\frac{72}{256}\\times\\frac{218}{256}\\times 256=61.3$\n\n:::\n\n::: {.column width=\"50%\"}\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | <span style=\"color: red;\">?</span> | | 72 |\n| Serotype 20 | | | 106  |\n| Serotype 31 | | | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n## $\\chi^2$ Test\n\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n<span style=\"color: red;\">?</span> can be obtained by subtraction as 72-61.3\n\n:::\n\n::: {.column width=\"50%\"}\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3 | <span style=\"color: red;\">?</span> | 72 |\n| Serotype 20 | | | 106  |\n| Serotype 31 | | | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n## $\\chi^2$ Test\n\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n<span style=\"color: red;\">?</span> = expected # who survived and had serotype 20 if $H_0$ true\n\n<span style=\"color: red;\">?</span> = probability of being both serotype 20 and surviving times number of study participants = P(Serotype 20) $\\times$ P(Survived) $\\times$ 256\n\n<span style=\"color: red;\">?</span> = $\\frac{106}{256}\\times\\frac{218}{256}\\times 256=90.3$\n\nThe remainder of the entries in the table can be obtained now by subtraction.\n\n:::\n\n::: {.column width=\"50%\"}\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   <span style=\"color: red;\">?</span> | | 106  |\n| Serotype 31 | | | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n## $\\chi^2$ Test\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | <span style=\"color: red;\">106-90.3</span> | 106  |\n| Serotype 31 | | | 34|\n| Total | 218 | 38 | 256 |\n\n## $\\chi^2$ Test\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | <span style=\"color: red;\">$34\\times\\frac{218}{256}$</span> | | 34|\n| Total | 218 | 38 | 256 |\n\n## $\\chi^2$ Test\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | <span style=\"color: red;\">$34-34\\times\\frac{218}{256}$</span> | 34|\n| Total | 218 | 38 | 256 |\n\n## $\\chi^2$ Test\n\nThus if $H_0$ is true, we would expect to see a table like this. Expected counts are calculated at full precision and then rounded to one decimal place.\n\n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | 5.0 | 34|\n| Total | 218 | 38 | 256 |\n\n## Comparing Observed and Expected Tables\n  \n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nObserved Table\n    \n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nExpected Table under $H_0$\n    \n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | 5.0 | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\nSo we do observe some different proportions than we would expect under $H_0$, in particular for serotypes 20 and 31. Is this \"different enough\" for us to raise an alarm about one or more serotypes?\n\n## Comparing Observed and Expected Tables\n  \n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nObserved Table\n    \n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nExpected Table under $H_0$\n    \n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | 5.0 | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n\n- The $\\chi^2$ test compares the observed frequencies, $O$, in each cell of the table to the expected frequencies, $E$, if $H_0$ is true.\n\n## Comparing Observed and Expected Tables\n  \n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nObserved Table\n    \n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nExpected Table under $H_0$\n    \n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | 5.0 | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n\n- If differences between what we observe and expect, $O-E$, are large enough, we reject $H_0$.\n\n## Comparing Observed and Expected Tables\n  \n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nObserved Table\n    \n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nExpected Table under $H_0$\n    \n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | 5.0 | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n- To combine differences across table cells, we need to square them (so that extra deaths in one serotype are not cancelled out by fewer deaths in another serotype) before adding them up.\n\n## Comparing Observed and Expected Tables\n  \n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nObserved Table\n    \n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nExpected Table under $H_0$\n    \n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | 5.0 | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\n- In addition, we need to *scale* the differences.  That is, seeing 5 'extra' deaths is a big deal if our study only contains 10 participants and is not a big deal if our study contains 100,000 participants, so we divide by $E$ to examine relative differences\n\n## Comparing Observed and Expected Tables\n  \n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nObserved Table\n    \n| Serotype | Survived | Died | Total |\n|:-----|-----:|------:|-----:|\n| Serotype 10 | 37 | 7 | 44 |\n| Serotype 15 | 60 | 12 | 72 |\n| Serotype 20 | 97 | 9 | 106 |\n| Serotype 31 | 24 | 10 | 34 |\n| Total | 218 | 38 | 256 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nExpected Table under $H_0$\n    \n| | Survived | Died | Total |\n|:------|------:|-------:|--------:|\n| Serotype 10 | 37.5 | 6.5 | 44 |\n| Serotype 15 | 61.3| 10.7 | 72 |\n| Serotype 20 |   90.3 | 15.7  | 106  |\n| Serotype 31 | 29.0 | 5.0 | 34|\n| Total | 218 | 38 | 256 |\n\n:::\n\n::::\n\n</div>\n\n\nOur test statistic is $X^2=\\sum_{i=1}^{rc} \\frac{(O_i-E_i)^2}{E_i},$ where $r\\times c=rc$ is the number of cells in the table (not including any totals, so there are 8 cells here). So here that's $$\\frac{(37-37.5)^2}{37.5}+\\frac{(7-6.5)^2}{6.5}+ \\cdots + \\frac{(10-5.0)^2}{5.0}$$\n\n## $\\chi^2$ Test\n  \n  - The distribution of this sum is approximated by a chi-squared distribution with $(r-1)(c-1)$ degrees of freedom, written ${\\chi^2}_{(r-1)(c-1)}$\n  \n  - Like the $F$ distribution, there is a different $\\chi^2$ distribution for each degrees of freedom, and chi-squared distribution is not symmetric\n\n- Like the $F$ distribution, all the mass is above 0, and to calculate the p-value we look at the area in the right tail only.\n\n## $\\chi^2$ Statistic\n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nobserved_chisq_statistic <- pneu %>%\n  specify(Serotype ~ Survived) %>%\n  calculate(stat = \"Chisq\")\n```\n:::\n\n\nBefore we calculate the p-value corresponding to this test statistic, we can visualize the distribution of $\\chi^2_{(4-1)(2-1)}=\\chi^2_3$ statistics we would see under $H_0$.\n\n## Simulating the null distribution\n\nWe can visualize the null distribution in two ways: by looking at the $\\chi^2_3$ distribution directly or by randomly sampling to generate the null distribution. First, let's consider a simulated null distribution. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# generate the null distribution using randomization\nnull_distribution_simulated <- pneu %>%\n  specify(Serotype ~ Survived) %>%\n  hypothesize(null = \"independence\") %>%\n  generate(reps = 5000, type = \"permute\") %>%\n  calculate(stat = \"Chisq\")\n```\n:::\n\n\n\n## The theoretical null distribution\n\nNext we can use the $\\chi^2_3$ distribution as an approximation to the null distribution.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Specify the test for use with the theoretical approximation.\nnull_distribution_theoretical <- pneu %>%\n  specify(Serotype ~ Survived) %>%\n  hypothesize(null = \"independence\") %>%\n# No permutation generation is needed for the theoretical approximation.\n  calculate(stat = \"Chisq\")\n```\n:::\n\n\n## Visualizing the simulated null distribution\n\nLet's visualize based on the simulated null distribution.\n\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables-old_files/figure-revealjs/vizsim-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# visualize the null distribution and test statistic!\nnull_distribution_simulated %>%\n  visualize() + \n  shade_p_value(observed_chisq_statistic,\n                direction = \"greater\")\n```\n:::\n\n\n:::\n\n## Visualizing the theoretical null distribution\n\nWe can also visualize based on the theoretical distribution, $\\chi^2_3$.\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables-old_files/figure-revealjs/viz2-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# visualize the theoretical null distribution and test statistic!\npneu %>%\n  specify(Serotype ~ Survived) %>%\n  hypothesize(null= \"independence\") %>%\n  visualize(method = \"theoretical\") + \n  shade_p_value(observed_chisq_statistic,\n                direction = \"greater\")\n```\n:::\n\n\n:::\n\n## Comparing both null distributions\n\nHere we can also have our cake and eat it, too!  Let's visualize both.\n\n\n::: {.panel-tabset}\n\n## Plot\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](w12-l01-contingency-tables-old_files/figure-revealjs/viz3-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n## Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# visualize both null distributions and the test statistic!\nnull_distribution_simulated %>%\n  visualize(method = \"both\") + \n  shade_p_value(observed_chisq_statistic,\n                direction = \"greater\")\n```\n:::\n\n\n:::\n\n## Conducting the chi-squared test\n\nWe can now carry out the test.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchisq_test(pneu,Serotype~Survived)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 3\n#>   statistic chisq_df p_value\n#>       <dbl>    <int>   <dbl>\n#> 1      9.32        3  0.0253\n```\n\n\n:::\n:::\n\n\nIf there were no relationship, the probability we would see a $\\chi^2_3$ test statistic as large as 9.32 or larger is just 0.0253.  So serotypes are related to survival probability.\n\n## Step-Down Tests\n\nWe can also compare pairs of serotypes. If we test multiple pairs, we should adjust for multiple comparisons before concluding which serotypes differ.  Here, we compare serotypes 20 and 31.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npneu2 <- pneu %>%\n  filter(Serotype==\"Serotype 20\" | Serotype == \"Serotype 31\")\nchisq_test(pneu2,Serotype~Survived)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 1 × 3\n#>   statistic chisq_df p_value\n#>       <dbl>    <int>   <dbl>\n#> 1      7.91        1 0.00493\n```\n\n\n:::\n:::\n\n\n# How strong is the association?\n\n## The Odds Ratio (OR)\n\nSuppose we have a disease $D$ (e.g., lung cancer) and two groups, $E$ and $E^c$, where $E$=smokers and $E^c$=nonsmokers.\n\n$$OR=\\frac{\\left\\{\\frac{Pr(D \\mid E)}{1-Pr(D \\mid E)}\\right\\}}{\\left\\{\\frac{Pr(D \\mid E^c)}{1-Pr(D \\mid E^c)}\\right\\}}$$\n\nThe OR ranges from 0 to $\\infty$.  When $OR=1$ (even odds), there is no association between two variables.\n\n## Odds Ratio\n\nConsider the following contingency table.\n\n| | Exposed | Unexposed | Total |\n|:----|:-------:|:------:|----:|\n| Disease | a | b | a+b |\n| No disease | c | d | c+d |\n| Total | a+c | b+d | a+b+c+d |\n\n$$\\widehat{Pr}(D \\mid E)=\\frac{a}{a+c}$$\n$$\\widehat{Pr}(D \\mid E^c) = \\frac{b}{b+d}$$\n\n## Odds Ratio\n\n$$\\widehat{Pr}(D \\mid E)=\\frac{a}{a+c} ~~~~~~~\\widehat{Pr}(D \\mid E^c) = \\frac{b}{b+d}$$\n$$OR=\\frac{\\left\\{\\frac{Pr(D \\mid E)}{1-Pr(D \\mid E)}\\right\\}}{\\left\\{\\frac{Pr(D \\mid E^c)}{1-Pr(D \\mid E^c)}\\right\\}}$$\n\n\n$$\\widehat{OR}=\\frac{\\left\\{\\frac{\\frac{a}{a+c}}{\\frac{c}{a+c}}\\right\\}}{\\left\\{\\frac{\\frac{b}{b+d}}{\\frac{d}{b+d}} \\right\\}} =\\frac{ad}{bc}$$\n\n## Estimating an OR and a 95% CI for it\n\n<div style=\"font-size:0.8em;\">\n\nMany R packages will estimate an odds ratio and 95% CI for it when provided a 2 $\\times$ 2 table. For now, we can take advantage of the fact that the `fisher.test` function does this automatically. First, though, we need to subset to only two serotypes. Below we subset to serotypes 20 and 31 so we get an OR comparing these two. Our null hypothesis is that the survival probabilities are the same for both serotypes, and the alternative is that they are different.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npneu2 <- pneu %>%\n  filter(Serotype==\"Serotype 20\" | Serotype == \"Serotype 31\")\n```\n:::\n\n\n</div>\n\n## Odds ratio: serotype 20 versus serotype 31\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(pneu2$Serotype, pneu2$Survived)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              \n#>               Did not survive Survived\n#>   Serotype 20               9       97\n#>   Serotype 31              10       24\n```\n\n\n:::\n\n```{.r .cell-code}\n# Columns are ordered: Did not survive, Survived.\n# The OR compares odds of death for serotype 20 versus serotype 31.\nfisher.test(table(pneu2$Serotype, pneu2$Survived))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tFisher's Exact Test for Count Data\n#> \n#> data:  table(pneu2$Serotype, pneu2$Survived)\n#> p-value = 0.003891\n#> alternative hypothesis: true odds ratio is not equal to 1\n#> 95 percent confidence interval:\n#>  0.07201804 0.69330783\n#> sample estimates:\n#> odds ratio \n#>  0.2257481\n```\n\n\n:::\n:::\n\n\n$\\widehat{OR}=0.23$ with a 95% CI of (0.07, 0.69). Those infected with serotype 20 have just 0.23 (95% CI=(0.07, 0.69)) times the odds of death as those infected with serotype 31.\n\n## Comparing serotypes 10 and 31\n\nNow we can quantify other differences. For example, we may wish to evaluate whether serotype 10 and serotype 31 have the same survival probability or not.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npneu3 <- pneu %>%\n  filter(Serotype==\"Serotype 10\" | Serotype == \"Serotype 31\")\ntable(pneu3$Serotype, pneu3$Survived)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>              \n#>               Did not survive Survived\n#>   Serotype 10               7       37\n#>   Serotype 31              10       24\n```\n\n\n:::\n:::\n\n\n## Fisher's exact test: serotypes 10 and 31\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfisher.test(table(pneu3$Serotype, pneu3$Survived))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tFisher's Exact Test for Count Data\n#> \n#> data:  table(pneu3$Serotype, pneu3$Survived)\n#> p-value = 0.1758\n#> alternative hypothesis: true odds ratio is not equal to 1\n#> 95 percent confidence interval:\n#>  0.128805 1.546707\n#> sample estimates:\n#> odds ratio \n#>    0.45881\n```\n\n\n:::\n:::\n\n\nWhat do you conclude?\n",
    "supporting": [
      "w12-l01-contingency-tables-old_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}