{
  "hash": "7edbb376fa413b0906fb8956c4babe7c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Paradoxes and Fallacies\"\nsubtitle: \"Introduction to Global Health Data Science\"\nauthor: \"Prof. Amy Herring\"\nformat:\n  revealjs:\n    output-file: w12-l02-paradox.html\n    footer: \"[🔗 sta198-fa26-2.github.io](https://sta198-fa26-2.github.io/)\"\n    theme: slides.scss\n    transition: fade\n    slide-number: true\n    pdf-separate-fragments: true\n    toc: false\n  html:\n    code-link: true\neditor_options:\n  chunk_output_type: console\n---\n\n# Berkson's Fallacy\n\n## Berkson's Fallacy\n\n\n\n<div style=\"font-size:0.8em;\">\n\n:::: {.columns}\n\n::: {.column width=\"45%\"}\n\nDue to ease of data collection, a restricted sample is often used to test a hypothesis of interest. We illustrate a common problem with this approach.\n\nResearchers are interested in HIV-positive women on antiretroviral therapy in sub-Saharan Africa. They would like to know whether a new pregnancy is related to the probability of having an AIDS-defining event.\n\n:::\n\n::: {.column width=\"5%\"}\n\n:::\n\n::: {.column width=\"50%\"}\n\nThey recruit women from a large network of health care clinics and find the following.\n\n| | AIDS | No AIDS | Total |\n|:--|--:|--:|--:|\n| Pregnant | 31 | 44 | 75 |\n| Not pregnant | 124 | 99 | 223 |\n| Total | 155 | 143 | 298 |\n\nThe estimated $\\widehat{OR}$ is $\\frac{31\\times99}{44\\times124}=0.56$, with a 95% CI of $(0.32,0.99)$. Should HIV-positive women on antiretroviral therapy try to get pregnant to prevent an AIDS-defining event?\n\n:::\n\n::::\n\n</div>\n\n## Berkson's Fallacy\n\nNow we consider all HIV-positive women in the area, including those who did not visit a health clinic during the study period.\n\n| | AIDS | No AIDS | Total |\n|:--|--:|--:|--:|\n| Pregnant | 44 | 175 | 219 |\n| Not pregnant | 248 | 990 | 1238 |\n| Total | 292 | 1165 | 1457 |\n\nThe estimated $\\widehat{OR}$ is $\\frac{44\\times990}{175\\times248}=1.00$, with a 95% CI of $(0.68,1.44)$. What happened?\n\n## Berkson's Fallacy\n\n\n<div style=\"font-size:0.8em;\">\n\nThe bias in the clinic sample comes from differences in the probability of visiting a clinic.\n\n| Diagnosis | With clinic visit | Total women | $P(\\text{visit})$ |\n|:--|--:|--:|--:|\n| Pregnant and AIDS | 31 | 44 | $31/44=0.70$ |\n| Pregnant only | 44 | 175 | $44/175=0.25$ |\n| AIDS only | 124 | 248 | $124/248=0.50$ |\n| Neither | 99 | 990 | $99/990=0.10$ |\n\nThe spurious relationship created by selecting this clinic sample is called *Berkson's fallacy*. It is a danger with clinic or hospital samples.\n\n</div>\n\n# Simpson's Paradox\n\n## Multiple Contingency Tables\n\nPreviously, we analyzed $r\\times c$ tables to quantify an association between two factors. Now we consider that relationship in the presence of a third factor.\n\nWhen might this be useful?\n\n- We have a $2\\times2$ table at each site in a multisite study.\n- We wish to combine results from several studies in a meta-analysis.\n- A third factor may change the estimated association between two factors.\n\n## Combining Multiple Tables\n\nA third factor can affect the relationship between two factors of interest. We will examine what happens when we aggregate data across levels of that third factor.\n\nWhether to aggregate often depends on subject matter knowledge as well as statistical considerations.\n\nWe start with *Simpson's paradox*: combining groups can produce a very different conclusion from examining them separately.\n\n## Simpson's Paradox\n\n:::: {.columns}\n\n::: {.column width=\"48%\"}\n\n*Simpson's paradox* occurs when an association between two variables reverses or disappears after stratifying by a third variable.\n\n:::\n\n::: {.column width=\"48%\"}\n\n\n::: {.cell layout-align=\"left\"}\n::: {.cell-output-display}\n![](../img/simpsons1.png){fig-align='left' width=90%}\n:::\n:::\n\n\n:::\n\n::::\n\n## COVID Delta cases: the overall picture\n\n<div style=\"font-size:0.8em;\">\n\n\nPublic Health England recorded confirmed and provisional Delta cases in England from February 1 through August 2, 2021. The outcome here is **death within 28 days of a positive specimen**, among reported cases with a known age.\n\n“Vaccinated” means at least 21 days after a first dose, including people who received two doses.\n\n| Vaccination status | Deaths | Reported cases | Deaths / cases |\n|:--|--:|--:|--:|\n| Vaccinated | 481 | 117,114 | **0.41%** |\n| Unvaccinated | 253 | 151,052 | **0.17%** |\n\nThe odds of death among vaccinated individuals were $\\frac{481(151052)}{117114(253)}=2.13$ times the odds among unvaccinated individuals. What might explain the higher *overall* risk among vaccinated cases? Was the vaccine harming people?\n\n*Source: [Public Health England, Technical Briefing 20, Table 5 (2021)](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1009243/Technical_Briefing_20.pdf). Counts exclude cases with unknown age and vaccination categories other than the two shown.*\n\n</div>\n\n## Reported Delta cases under age 50\n\n<div style=\"font-size:0.9em;\">\n\n\n| Vaccination status | Death | No death | Total |\n|:--|--:|--:|--:|\n| Vaccinated | 21 | 89,786 | 89,807 |\n| Unvaccinated | 48 | 147,564 | 147,612 |\n\nAmong reported cases, the percentage who died was\n\n- **0.023%** for vaccinated people;\n- **0.033%** for unvaccinated people.\n\nThe odds ratio for death, vaccinated versus unvaccinated, is\n\n$$\n\\widehat{OR}\n=\\frac{21(147{,}564)}{89{,}786(48)}\n\\approx 0.72.\n$$\n\nConclusion: vaccines look good here\n\n</div>\n\n## Reported Delta cases age 50 or older\n\n<div style=\"font-size:0.8em;\">\n\n\n| Vaccination status | Death | No death | Total |\n|:--|--:|--:|--:|\n| Vaccinated | 460 | 26,847 | 27,307 |\n| Unvaccinated | 205 | 3,235 | 3,440 |\n\nAmong reported cases, the percentage who died was **1.68% vaccinated** versus **5.96% unvaccinated**.\n\n$$\n\\widehat{OR}\n=\\frac{460(3{,}235)}{26{,}847(205)}\n\\approx 0.27.\n$$\n\n**Both age groups show lower percentages of death among vaccinated cases. Why does the overall comparison go the other way?**\n\n*Source: [Public Health England, Technical Briefing 20, Table 5 (2021)](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1009243/Technical_Briefing_20.pdf). “No death” is calculated as reported cases minus deaths within 28 days.*\n\n</div>\n\n## Why the aggregate reverses\n\n<div style=\"font-size:0.8em;\">\n\n\nAge 50 or older accounts for $27{,}307/117{,}114=23.3\\%$ of the vaccinated cases, but only $3{,}440/151{,}052=2.3\\%$ of the unvaccinated cases.\n\nThe older group has a much higher death percentage in **both** vaccination groups, and the older individuals in this group of reported cases are more likely to be vaccinated. The overall percentages weight the two age groups differently:\n\n$$\n\\begin{aligned}\n\\text{Vaccinated:}\\quad &\\frac{21+460}{89{,}807+27{,}307}=0.41\\% \\\\\n\\text{Unvaccinated:}\\quad &\\frac{48+205}{147{,}612+3{,}440}=0.17\\%.\n\\end{aligned}\n$$\n\nThese are **deaths among reported cases**, not death rates among all vaccinated or unvaccinated people. They do not by themselves estimate vaccine effectiveness.\n\n</div>\n\n## Another Example: Graduate Admissions\n\nImagine that your dream university, which has only two departments: English and Mathematics, admitted 30.0% of men but only 21.3% of women last year. You wonder whether the university favors male applicants.\n\nDuring visits to the English and mathematics departments, you see figures that complicate the university-wide comparison. \n\n## The English Department\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| | Rejected | Admitted |\n|:--|--:|--:|\n| Female | 29 | 21 |\n| Male | 60 | 40 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nEnglish admitted $21/50=42\\%$ of women and $40/100=40\\%$ of men. Maybe the mathematics department is driving the overall pattern.\n\n\n::: {.cell layout-align=\"left\"}\n::: {.cell-output-display}\n![](../img/lisa2.png){fig-align='left' width=60%}\n:::\n:::\n\n\n:::\n\n::::\n\n## The Department of Mathematics\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| | Rejected | Admitted |\n|:--|--:|--:|\n| Female | 89 | 11 |\n| Male | 45 | 5 |\n\n:::\n\n::: {.column width=\"50%\"}\n\nMathematics admitted $11/100=11\\%$ of women and $5/50=10\\%$ of men.\n\n\n::: {.cell layout-align=\"left\"}\n::: {.cell-output-display}\n![](../img/bart2.png){fig-align='left' width=60%}\n:::\n:::\n\n\n:::\n\n::::\n\n## UC Berkeley\n\nOverall, the university in our example admitted $(21+11)/(50+100)=21.3\\%$ of women and $(40+5)/(100+50)=30\\%$ of men. However, two thirds of the women applied to mathematics, the harder department to enter, compared with only one third of the men.\n\nA similar pattern appeared in the University of California, Berkeley's fall 1973 graduate admissions data, and the university was sued for gender discrimination. Women applied more often to departments with lower admission rates (these were generally in the humanities), and men tended to apply to departments with higher admissions rates (engineering and physical sciences). \n\n## Practice at home: kidney stone treatments\n\nA 1986 *British Medical Journal* study compared open surgery with percutaneous nephrolithotomy (PN). Here are the numbers of successful and unsuccessful procedures by stone size.\n\n<div style=\"font-size:0.82em;\">\n\n:::: {.columns}\n\n::: {.column width=\"49%\"}\n\n**Small stones**\n\n| Treatment | Success | No success |\n|:--|--:|--:|\n| Open surgery | 81 | 6 |\n| PN | 234 | 36 |\n\n:::\n\n::: {.column width=\"49%\"}\n\n**Large stones**\n\n| Treatment | Success | No success |\n|:--|--:|--:|\n| Open surgery | 192 | 71 |\n| PN | 55 | 25 |\n\n:::\n\n::::\n\n</div>\n\n## Practice at home: questions\n\nUsing the two tables on the previous slide:\n\n1. Calculate the proportion of successful procedures for each treatment, separately for small and large stones. Which treatment has the higher success proportion in each group?\n\n2. Combine the counts across stone sizes. Calculate the overall success proportion for each treatment. Does the comparison change?\n\n3. Calculate the odds ratio for success (open surgery compared with PN) for small stones, large stones, and all stones combined.\n\n4. Explain the change in the overall comparison. Which treatment was used more often for large stones?\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}